//
// Generated by Bluespec Compiler (build a026416)
//
// On Tue Jun 16 00:01:46 IST 2020
//
//
// Ports:
// Name                         I/O  size props
// RDY_inst_response_put          O     1 reg
// rx_from_stage0_deq_ena         O     1
// tx_to_stage2_enq_ena           O     1
// tx_to_stage2_enq_data          O   122
// tx_to_stage2_inst_enq_ena      O     1
// tx_to_stage2_inst_enq_data     O    32
// RDY_update_eEpoch              O     1 const
// RDY_update_wEpoch              O     1 const
// RDY_csr_misa_c                 O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// inst_response_put              I    41
// rx_from_stage0_notEmpty_b      I     1
// rx_from_stage0_first_deq_rdy_b  I     1
// rx_from_stage0_first_x         I    80
// tx_to_stage2_notFull_b         I     1 unused
// tx_to_stage2_enq_rdy_b         I     1
// tx_to_stage2_inst_notFull_b    I     1 unused
// tx_to_stage2_inst_enq_rdy_b    I     1
// csr_misa_c_c                   I     1
// EN_inst_response_put           I     1
// EN_update_eEpoch               I     1
// EN_update_wEpoch               I     1
// EN_csr_misa_c                  I     1
//
// Combinational paths from inputs to outputs:
//   (inst_response_put,
//    rx_from_stage0_notEmpty_b,
//    rx_from_stage0_first_deq_rdy_b,
//    tx_to_stage2_enq_rdy_b,
//    tx_to_stage2_inst_enq_rdy_b,
//    EN_inst_response_put,
//    EN_csr_misa_c) -> rx_from_stage0_deq_ena
//   (inst_response_put,
//    rx_from_stage0_notEmpty_b,
//    rx_from_stage0_first_deq_rdy_b,
//    rx_from_stage0_first_x,
//    tx_to_stage2_enq_rdy_b,
//    tx_to_stage2_inst_enq_rdy_b,
//    csr_misa_c_c,
//    EN_inst_response_put,
//    EN_csr_misa_c) -> tx_to_stage2_enq_ena
//   (inst_response_put,
//    rx_from_stage0_notEmpty_b,
//    rx_from_stage0_first_deq_rdy_b,
//    rx_from_stage0_first_x,
//    tx_to_stage2_enq_rdy_b,
//    tx_to_stage2_inst_enq_rdy_b,
//    csr_misa_c_c,
//    EN_inst_response_put,
//    EN_csr_misa_c) -> tx_to_stage2_enq_data
//   (inst_response_put,
//    rx_from_stage0_notEmpty_b,
//    rx_from_stage0_first_deq_rdy_b,
//    rx_from_stage0_first_x,
//    tx_to_stage2_enq_rdy_b,
//    tx_to_stage2_inst_enq_rdy_b,
//    csr_misa_c_c,
//    EN_inst_response_put,
//    EN_csr_misa_c) -> tx_to_stage2_inst_enq_ena
//   (inst_response_put,
//    rx_from_stage0_notEmpty_b,
//    rx_from_stage0_first_deq_rdy_b,
//    rx_from_stage0_first_x,
//    tx_to_stage2_enq_rdy_b,
//    tx_to_stage2_inst_enq_rdy_b,
//    csr_misa_c_c,
//    EN_inst_response_put,
//    EN_csr_misa_c) -> tx_to_stage2_inst_enq_data
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkstage1(CLK,
		RST_N,

		inst_response_put,
		EN_inst_response_put,
		RDY_inst_response_put,

		rx_from_stage0_notEmpty_b,

		rx_from_stage0_first_deq_rdy_b,

		rx_from_stage0_first_x,

		rx_from_stage0_deq_ena,

		tx_to_stage2_notFull_b,

		tx_to_stage2_enq_rdy_b,

		tx_to_stage2_enq_ena,

		tx_to_stage2_enq_data,

		tx_to_stage2_inst_notFull_b,

		tx_to_stage2_inst_enq_rdy_b,

		tx_to_stage2_inst_enq_ena,

		tx_to_stage2_inst_enq_data,

		EN_update_eEpoch,
		RDY_update_eEpoch,

		EN_update_wEpoch,
		RDY_update_wEpoch,

		csr_misa_c_c,
		EN_csr_misa_c,
		RDY_csr_misa_c);
  parameter [63 : 0] hartid = 64'b0;
  input  CLK;
  input  RST_N;

  // action method inst_response_put
  input  [40 : 0] inst_response_put;
  input  EN_inst_response_put;
  output RDY_inst_response_put;

  // action method rx_from_stage0_notEmpty
  input  rx_from_stage0_notEmpty_b;

  // action method rx_from_stage0_first_deq_rdy
  input  rx_from_stage0_first_deq_rdy_b;

  // action method rx_from_stage0_first
  input  [79 : 0] rx_from_stage0_first_x;

  // value method rx_from_stage0_deq_ena
  output rx_from_stage0_deq_ena;

  // action method tx_to_stage2_notFull
  input  tx_to_stage2_notFull_b;

  // action method tx_to_stage2_enq_rdy
  input  tx_to_stage2_enq_rdy_b;

  // value method tx_to_stage2_enq_ena
  output tx_to_stage2_enq_ena;

  // value method tx_to_stage2_enq_data
  output [121 : 0] tx_to_stage2_enq_data;

  // action method tx_to_stage2_inst_notFull
  input  tx_to_stage2_inst_notFull_b;

  // action method tx_to_stage2_inst_enq_rdy
  input  tx_to_stage2_inst_enq_rdy_b;

  // value method tx_to_stage2_inst_enq_ena
  output tx_to_stage2_inst_enq_ena;

  // value method tx_to_stage2_inst_enq_data
  output [31 : 0] tx_to_stage2_inst_enq_data;

  // action method update_eEpoch
  input  EN_update_eEpoch;
  output RDY_update_eEpoch;

  // action method update_wEpoch
  input  EN_update_wEpoch;
  output RDY_update_wEpoch;

  // action method csr_misa_c
  input  csr_misa_c_c;
  input  EN_csr_misa_c;
  output RDY_csr_misa_c;

  // signals for module outputs
  wire [121 : 0] tx_to_stage2_enq_data;
  wire [31 : 0] tx_to_stage2_inst_enq_data;
  wire RDY_csr_misa_c,
       RDY_inst_response_put,
       RDY_update_eEpoch,
       RDY_update_wEpoch,
       rx_from_stage0_deq_ena,
       tx_to_stage2_enq_ena,
       tx_to_stage2_inst_enq_ena;

  // inlined wires
  wire ff_memory_response_dequeueing_whas, tx_w_ena_whas;

  // register rg_action
  reg rg_action;
  wire rg_action_D_IN, rg_action_EN;

  // register rg_eEpoch
  reg rg_eEpoch;
  wire rg_eEpoch_D_IN, rg_eEpoch_EN;

  // register rg_prev
  reg [96 : 0] rg_prev;
  wire [96 : 0] rg_prev_D_IN;
  wire rg_prev_EN;

  // register rg_receiving_upper
  reg rg_receiving_upper;
  wire rg_receiving_upper_D_IN, rg_receiving_upper_EN;

  // register rg_wEpoch
  reg rg_wEpoch;
  wire rg_wEpoch_D_IN, rg_wEpoch_EN;

  // ports of submodule ff_memory_response_ff
  wire [40 : 0] ff_memory_response_ff_D_IN, ff_memory_response_ff_D_OUT;
  wire ff_memory_response_ff_CLR,
       ff_memory_response_ff_DEQ,
       ff_memory_response_ff_EMPTY_N,
       ff_memory_response_ff_ENQ,
       ff_memory_response_ff_FULL_N;

  // ports of submodule ff_memory_response_firstValid
  wire ff_memory_response_firstValid_D_IN,
       ff_memory_response_firstValid_EN,
       ff_memory_response_firstValid_Q_OUT;

  // rule scheduling signals
  wire CAN_FIRE_RL_ff_memory_response_dequeue,
       CAN_FIRE_RL_ff_memory_response_enqueue,
       CAN_FIRE_RL_process_instruction,
       CAN_FIRE_csr_misa_c,
       CAN_FIRE_inst_response_put,
       CAN_FIRE_rx_from_stage0_first,
       CAN_FIRE_rx_from_stage0_first_deq_rdy,
       CAN_FIRE_rx_from_stage0_notEmpty,
       CAN_FIRE_tx_to_stage2_enq_rdy,
       CAN_FIRE_tx_to_stage2_inst_enq_rdy,
       CAN_FIRE_tx_to_stage2_inst_notFull,
       CAN_FIRE_tx_to_stage2_notFull,
       CAN_FIRE_update_eEpoch,
       CAN_FIRE_update_wEpoch,
       WILL_FIRE_RL_ff_memory_response_dequeue,
       WILL_FIRE_RL_ff_memory_response_enqueue,
       WILL_FIRE_RL_process_instruction,
       WILL_FIRE_csr_misa_c,
       WILL_FIRE_inst_response_put,
       WILL_FIRE_rx_from_stage0_first,
       WILL_FIRE_rx_from_stage0_first_deq_rdy,
       WILL_FIRE_rx_from_stage0_notEmpty,
       WILL_FIRE_tx_to_stage2_enq_rdy,
       WILL_FIRE_tx_to_stage2_inst_enq_rdy,
       WILL_FIRE_tx_to_stage2_inst_notFull,
       WILL_FIRE_tx_to_stage2_notFull,
       WILL_FIRE_update_eEpoch,
       WILL_FIRE_update_wEpoch;

  // declarations used by system tasks
  // synopsys translate_off
  reg TASK_testplusargs___d290;
  reg TASK_testplusargs___d291;
  reg TASK_testplusargs___d292;
  reg [63 : 0] v__h4509;
  reg TASK_testplusargs___d22;
  reg TASK_testplusargs___d23;
  reg TASK_testplusargs___d24;
  reg [63 : 0] v__h1514;
  reg TASK_testplusargs___d118;
  reg TASK_testplusargs___d119;
  reg TASK_testplusargs___d120;
  reg [63 : 0] v__h1956;
  reg TASK_testplusargs___d154;
  reg TASK_testplusargs___d155;
  reg TASK_testplusargs___d156;
  reg [63 : 0] v__h3497;
  reg TASK_testplusargs___d184;
  reg TASK_testplusargs___d185;
  reg TASK_testplusargs___d186;
  reg [63 : 0] v__h3790;
  reg TASK_testplusargs___d241;
  reg TASK_testplusargs___d242;
  reg TASK_testplusargs___d243;
  reg [63 : 0] v__h4260;
  reg TASK_testplusargs_41_OR_TASK_testplusargs_42_A_ETC___d250;
  reg TASK_testplusargs_41_OR_TASK_testplusargs_42_A_ETC___d252;
  reg TASK_testplusargs_41_OR_TASK_testplusargs_42_A_ETC___d256;
  reg TASK_testplusargs_41_OR_TASK_testplusargs_42_A_ETC___d258;
  reg TASK_testplusargs_41_OR_TASK_testplusargs_42_A_ETC___d263;
  reg TASK_testplusargs_41_OR_TASK_testplusargs_42_A_ETC___d265;
  reg TASK_testplusargs_41_OR_TASK_testplusargs_42_A_ETC___d277;
  reg TASK_testplusargs_41_OR_TASK_testplusargs_42_A_ETC___d280;
  reg TASK_testplusargs_41_OR_TASK_testplusargs_42_A_ETC___d283;
  reg TASK_testplusargs_41_OR_TASK_testplusargs_42_A_ETC___d286;
  reg TASK_testplusargs_2_OR_TASK_testplusargs_3_AND_ETC___d35;
  reg TASK_testplusargs_2_OR_TASK_testplusargs_3_AND_ETC___d37;
  reg TASK_testplusargs_2_OR_TASK_testplusargs_3_AND_ETC___d43;
  reg TASK_testplusargs_2_OR_TASK_testplusargs_3_AND_ETC___d45;
  reg TASK_testplusargs_2_OR_TASK_testplusargs_3_AND_ETC___d49;
  reg TASK_testplusargs_2_OR_TASK_testplusargs_3_AND_ETC___d51;
  reg NOT_rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff__ETC___d123;
  reg TASK_testplusargs_54_OR_TASK_testplusargs_55_A_ETC___d176;
  reg TASK_testplusargs_54_OR_TASK_testplusargs_55_A_ETC___d179;
  reg TASK_testplusargs_84_OR_TASK_testplusargs_85_A_ETC___d190;
  reg TASK_testplusargs_84_OR_TASK_testplusargs_85_A_ETC___d191;
  reg rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d246;
  reg TASK_testplusargs_90_OR_TASK_testplusargs_91_A_ETC___d298;
  reg TASK_testplusargs_90_OR_TASK_testplusargs_91_A_ETC___d300;
  // synopsys translate_on

  // remaining internal signals
  wire [63 : 0] IF_rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_m_ETC___d169,
		rx_from_stage0_first_x_BITS_79_TO_16__q1,
		x1_avValue_snd_snd_fst_address__h3552,
		x1_avValue_snd_snd_fst_address__h3560,
		x1_avValue_snd_snd_snd_fst_address__h3563,
		x1_avValue_snd_snd_snd_fst_address__h3566,
		x1_avValue_snd_snd_snd_pc__h3294,
		x1_avValue_snd_snd_snd_pc__h3298,
		x1_avValue_snd_snd_snd_snd_pc__h3192,
		x1_avValue_snd_snd_snd_snd_snd_pc__h3259,
		x1_avValue_snd_snd_snd_snd_snd_snd_pc__h3302,
		x1_avValue_snd_snd_snd_snd_snd_snd_pc__h3306,
		x_pc__h3107,
		y_avValue_snd_snd_fst_address__h3557;
  wire [31 : 0] IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d69,
		final_instruction___1__h4103,
		final_instruction__h3085,
		pipedata_instruction__h4092,
		y_avValue_snd_snd_fst__h3273,
		y_avValue_snd_snd_snd_snd_fst__h3152,
		y_avValue_snd_snd_snd_snd_fst__h3154,
		y_avValue_snd_snd_snd_snd_fst__h3213,
		y_avValue_snd_snd_snd_snd_fst__h3215;
  wire [16 : 0] rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_CONCAT_IF_rg__ETC___d152;
  wire [15 : 0] IF_NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO__ETC___d237,
		x1_avValue_snd_snd_snd_instruction__h3295,
		x1_avValue_snd_snd_snd_instruction__h3299,
		x1_avValue_snd_snd_snd_snd_instruction__h3193,
		x1_avValue_snd_snd_snd_snd_snd_instruction__h3260,
		x1_avValue_snd_snd_snd_snd_snd_snd_instruction__h3303,
		x1_avValue_snd_snd_snd_snd_snd_snd_instruction__h3307,
		x_instruction__h3108;
  wire [14 : 0] IF_IF_ff_memory_response_ff_i_notEmpty_THEN_ff_ETC___d148,
		IF_IF_rx_fromstage0_w_data_whas__8_THEN_rx_fro_ETC___d149,
		IF_NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO__ETC___d150;
  wire [10 : 0] x1_avValue_snd_snd_fst_history__h4155;
  wire [5 : 0] cause__h3429;
  wire [1 : 0] curr_epoch__h1421,
	       x1_avValue_snd_fst_prediction__h4140,
	       x1_avValue_snd_fst_prediction__h4144,
	       x1_avValue_snd_snd_fst_prediction__h4148,
	       x1_avValue_snd_snd_fst_prediction__h4152,
	       x__h2247,
	       y__h1735,
	       y_avValue_snd_fst_prediction__h4136,
	       y_avValue_snd_snd_fst_prediction__h4128;
  wire IF_IF_ff_memory_response_ff_i_notEmpty_THEN_ff_ETC___d231,
       IF_IF_ff_memory_response_ff_i_notEmpty_THEN_ff_ETC___d274,
       IF_IF_rx_fromstage0_w_data_whas__8_THEN_rx_fro_ETC___d113,
       IF_IF_rx_fromstage0_w_data_whas__8_THEN_rx_fro_ETC___d209,
       IF_IF_rx_fromstage0_w_data_whas__8_THEN_rx_fro_ETC___d232,
       IF_NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO__ETC___d210,
       IF_NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO__ETC___d216,
       IF_NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO__ETC___d249,
       IF_NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO__ETC___d262,
       IF_NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO__ETC___d276,
       IF_NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO__ETC___d279,
       IF_NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO__ETC___d282,
       IF_NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO__ETC___d285,
       IF_NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO__ETC___d97,
       IF_ff_memory_response_ff_i_notEmpty_THEN_NOT_f_ETC___d175,
       IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d178,
       IF_rg_prev_6_BIT_11_9_THEN_rg_prev_6_BITS_14_T_ETC___d92,
       IF_rx_fromstage0_w_data_whas__8_THEN_rx_fromst_ETC___d94,
       NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO_15__ETC___d107,
       NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO_15__ETC___d196,
       NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO_15__ETC___d86,
       ff_memory_response_firstValid_read_AND_ff_memo_ETC___d19,
       rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d84,
       rg_prev_6_BITS_16_TO_15_7_EQ_rg_eEpoch_8_CONCA_ETC___d61;

  // action method inst_response_put
  assign RDY_inst_response_put = ff_memory_response_ff_FULL_N ;
  assign CAN_FIRE_inst_response_put = ff_memory_response_ff_FULL_N ;
  assign WILL_FIRE_inst_response_put = EN_inst_response_put ;

  // action method rx_from_stage0_notEmpty
  assign CAN_FIRE_rx_from_stage0_notEmpty = 1'd1 ;
  assign WILL_FIRE_rx_from_stage0_notEmpty = 1'd1 ;

  // action method rx_from_stage0_first_deq_rdy
  assign CAN_FIRE_rx_from_stage0_first_deq_rdy = 1'd1 ;
  assign WILL_FIRE_rx_from_stage0_first_deq_rdy = 1'd1 ;

  // action method rx_from_stage0_first
  assign CAN_FIRE_rx_from_stage0_first = 1'd1 ;
  assign WILL_FIRE_rx_from_stage0_first = 1'd1 ;

  // value method rx_from_stage0_deq_ena
  assign rx_from_stage0_deq_ena = ff_memory_response_dequeueing_whas ;

  // action method tx_to_stage2_notFull
  assign CAN_FIRE_tx_to_stage2_notFull = 1'd1 ;
  assign WILL_FIRE_tx_to_stage2_notFull = 1'd1 ;

  // action method tx_to_stage2_enq_rdy
  assign CAN_FIRE_tx_to_stage2_enq_rdy = 1'd1 ;
  assign WILL_FIRE_tx_to_stage2_enq_rdy = 1'd1 ;

  // value method tx_to_stage2_enq_ena
  assign tx_to_stage2_enq_ena = tx_w_ena_whas ;

  // value method tx_to_stage2_enq_data
  assign tx_to_stage2_enq_data =
	     { IF_rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_m_ETC___d169,
	       pipedata_instruction__h4092,
	       curr_epoch__h1421,
	       IF_NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO__ETC___d216,
	       cause__h3429,
	       rg_receiving_upper &&
	       IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d178,
	       IF_NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO__ETC___d237 } ;

  // action method tx_to_stage2_inst_notFull
  assign CAN_FIRE_tx_to_stage2_inst_notFull = 1'd1 ;
  assign WILL_FIRE_tx_to_stage2_inst_notFull = 1'd1 ;

  // action method tx_to_stage2_inst_enq_rdy
  assign CAN_FIRE_tx_to_stage2_inst_enq_rdy = 1'd1 ;
  assign WILL_FIRE_tx_to_stage2_inst_enq_rdy = 1'd1 ;

  // value method tx_to_stage2_inst_enq_ena
  assign tx_to_stage2_inst_enq_ena = tx_w_ena_whas ;

  // value method tx_to_stage2_inst_enq_data
  assign tx_to_stage2_inst_enq_data =
	     (!rg_action &&
	      rg_prev_6_BITS_16_TO_15_7_EQ_rg_eEpoch_8_CONCA_ETC___d61) ?
	       y_avValue_snd_snd_snd_snd_fst__h3152 :
	       y_avValue_snd_snd_snd_snd_fst__h3154 ;

  // action method update_eEpoch
  assign RDY_update_eEpoch = 1'd1 ;
  assign CAN_FIRE_update_eEpoch = 1'd1 ;
  assign WILL_FIRE_update_eEpoch = EN_update_eEpoch ;

  // action method update_wEpoch
  assign RDY_update_wEpoch = 1'd1 ;
  assign CAN_FIRE_update_wEpoch = 1'd1 ;
  assign WILL_FIRE_update_wEpoch = EN_update_wEpoch ;

  // action method csr_misa_c
  assign RDY_csr_misa_c = 1'd1 ;
  assign CAN_FIRE_csr_misa_c = 1'd1 ;
  assign WILL_FIRE_csr_misa_c = EN_csr_misa_c ;

  // submodule ff_memory_response_ff
  FIFO2 #(.width(32'd41), .guarded(32'd0)) ff_memory_response_ff(.RST(RST_N),
								 .CLK(CLK),
								 .D_IN(ff_memory_response_ff_D_IN),
								 .ENQ(ff_memory_response_ff_ENQ),
								 .DEQ(ff_memory_response_ff_DEQ),
								 .CLR(ff_memory_response_ff_CLR),
								 .D_OUT(ff_memory_response_ff_D_OUT),
								 .FULL_N(ff_memory_response_ff_FULL_N),
								 .EMPTY_N(ff_memory_response_ff_EMPTY_N));

  // submodule ff_memory_response_firstValid
  RevertReg #(.width(32'd1),
	      .init(1'd1)) ff_memory_response_firstValid(.CLK(CLK),
							 .D_IN(ff_memory_response_firstValid_D_IN),
							 .EN(ff_memory_response_firstValid_EN),
							 .Q_OUT(ff_memory_response_firstValid_Q_OUT));

  // rule RL_process_instruction
  assign CAN_FIRE_RL_process_instruction =
	     ff_memory_response_firstValid_read_AND_ff_memo_ETC___d19 &&
	     rx_from_stage0_notEmpty_b ;
  assign WILL_FIRE_RL_process_instruction = CAN_FIRE_RL_process_instruction ;

  // rule RL_ff_memory_response_enqueue
  assign CAN_FIRE_RL_ff_memory_response_enqueue =
	     EN_inst_response_put &&
	     (!ff_memory_response_dequeueing_whas ||
	      ff_memory_response_ff_EMPTY_N) ;
  assign WILL_FIRE_RL_ff_memory_response_enqueue =
	     CAN_FIRE_RL_ff_memory_response_enqueue ;

  // rule RL_ff_memory_response_dequeue
  assign CAN_FIRE_RL_ff_memory_response_dequeue =
	     ff_memory_response_dequeueing_whas &&
	     ff_memory_response_ff_EMPTY_N ;
  assign WILL_FIRE_RL_ff_memory_response_dequeue =
	     CAN_FIRE_RL_ff_memory_response_dequeue ;

  // inlined wires
  assign tx_w_ena_whas =
	     WILL_FIRE_RL_process_instruction &&
	     rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d84 &&
	     NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO_15__ETC___d196 ;
  assign ff_memory_response_dequeueing_whas =
	     WILL_FIRE_RL_process_instruction &&
	     (rg_prev[18:17] == 2'b11 || rg_action ||
	      !rg_prev_6_BITS_16_TO_15_7_EQ_rg_eEpoch_8_CONCA_ETC___d61 ||
	      !rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d84) ;

  // register rg_action
  assign rg_action_D_IN =
	     !rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d84 ||
	     !rg_action &&
	     rg_prev_6_BITS_16_TO_15_7_EQ_rg_eEpoch_8_CONCA_ETC___d61 ||
	     IF_IF_rx_fromstage0_w_data_whas__8_THEN_rx_fro_ETC___d113 ;
  assign rg_action_EN =
	     WILL_FIRE_RL_process_instruction &&
	     (NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO_15__ETC___d107 ||
	      !rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d84) ;

  // register rg_eEpoch
  assign rg_eEpoch_D_IN = ~rg_eEpoch ;
  assign rg_eEpoch_EN = EN_update_eEpoch ;

  // register rg_prev
  assign rg_prev_D_IN =
	     { x_pc__h3107,
	       x_instruction__h3108,
	       rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_CONCAT_IF_rg__ETC___d152 } ;
  assign rg_prev_EN = CAN_FIRE_RL_process_instruction ;

  // register rg_receiving_upper
  assign rg_receiving_upper_D_IN =
	     rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d84 &&
	     IF_NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO__ETC___d97 ;
  assign rg_receiving_upper_EN =
	     WILL_FIRE_RL_process_instruction &&
	     NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO_15__ETC___d86 ;

  // register rg_wEpoch
  assign rg_wEpoch_D_IN = ~rg_wEpoch ;
  assign rg_wEpoch_EN = EN_update_wEpoch ;

  // submodule ff_memory_response_ff
  assign ff_memory_response_ff_D_IN = inst_response_put ;
  assign ff_memory_response_ff_ENQ = CAN_FIRE_RL_ff_memory_response_enqueue ;
  assign ff_memory_response_ff_DEQ = CAN_FIRE_RL_ff_memory_response_dequeue ;
  assign ff_memory_response_ff_CLR = 1'b0 ;

  // submodule ff_memory_response_firstValid
  assign ff_memory_response_firstValid_D_IN = 1'd1 ;
  assign ff_memory_response_firstValid_EN =
	     ff_memory_response_dequeueing_whas ;

  // remaining internal signals
  module_fn_decompress instance_fn_decompress_0(.fn_decompress_inst(final_instruction__h3085[15:0]),
						.fn_decompress(final_instruction___1__h4103));
  assign IF_IF_ff_memory_response_ff_i_notEmpty_THEN_ff_ETC___d148 =
	     (IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d69[1:0] ==
	      2'b11) ?
	       rg_prev[14:0] :
	       (csr_misa_c_c ? rx_from_stage0_first_x[14:0] : rg_prev[14:0]) ;
  assign IF_IF_ff_memory_response_ff_i_notEmpty_THEN_ff_ETC___d231 =
	     (IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d69[1:0] ==
	      2'b11) ?
	       rx_from_stage0_first_x[12] :
	       (csr_misa_c_c ?
		  !rx_from_stage0_first_x[11] && rx_from_stage0_first_x[12] :
		  rx_from_stage0_first_x[12]) ;
  assign IF_IF_ff_memory_response_ff_i_notEmpty_THEN_ff_ETC___d274 =
	     (IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d69[1:0] ==
	      2'b11) ?
	       !rx_from_stage0_first_x[12] :
	       (csr_misa_c_c ?
		  rx_from_stage0_first_x[11] || !rx_from_stage0_first_x[12] :
		  !rx_from_stage0_first_x[12]) ;
  assign IF_IF_rx_fromstage0_w_data_whas__8_THEN_rx_fro_ETC___d113 =
	     (rx_from_stage0_first_x[15] && csr_misa_c_c) ?
	       IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d69[17:16] !=
	       2'b11 :
	       IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d69[1:0] ==
	       2'b11 ||
	       !rx_from_stage0_first_x[11] &&
	       !IF_rx_fromstage0_w_data_whas__8_THEN_rx_fromst_ETC___d94 ;
  assign IF_IF_rx_fromstage0_w_data_whas__8_THEN_rx_fro_ETC___d149 =
	     (rx_from_stage0_first_x[15] && csr_misa_c_c) ?
	       ((IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d69[17:16] ==
		 2'b11) ?
		  rx_from_stage0_first_x[14:0] :
		  rg_prev[14:0]) :
	       IF_IF_ff_memory_response_ff_i_notEmpty_THEN_ff_ETC___d148 ;
  assign IF_IF_rx_fromstage0_w_data_whas__8_THEN_rx_fro_ETC___d209 =
	     (rx_from_stage0_first_x[15] && csr_misa_c_c) ?
	       IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d69[17:16] !=
	       2'b11 :
	       IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d69[1:0] !=
	       2'b11 &&
	       csr_misa_c_c ;
  assign IF_IF_rx_fromstage0_w_data_whas__8_THEN_rx_fro_ETC___d232 =
	     (rx_from_stage0_first_x[15] && csr_misa_c_c) ?
	       rx_from_stage0_first_x[11] && rx_from_stage0_first_x[12] :
	       IF_IF_ff_memory_response_ff_i_notEmpty_THEN_ff_ETC___d231 ;
  assign IF_NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO__ETC___d150 =
	     (!rg_action &&
	      rg_prev_6_BITS_16_TO_15_7_EQ_rg_eEpoch_8_CONCA_ETC___d61) ?
	       ((rg_prev[18:17] == 2'b11) ?
		  rx_from_stage0_first_x[14:0] :
		  rg_prev[14:0]) :
	       IF_IF_rx_fromstage0_w_data_whas__8_THEN_rx_fro_ETC___d149 ;
  assign IF_NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO__ETC___d210 =
	     (!rg_action &&
	      rg_prev_6_BITS_16_TO_15_7_EQ_rg_eEpoch_8_CONCA_ETC___d61) ?
	       rg_prev[18:17] != 2'b11 :
	       IF_IF_rx_fromstage0_w_data_whas__8_THEN_rx_fro_ETC___d209 ;
  assign IF_NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO__ETC___d216 =
	     (!rg_action &&
	      rg_prev_6_BITS_16_TO_15_7_EQ_rg_eEpoch_8_CONCA_ETC___d61) ?
	       rg_prev[18:17] == 2'b11 &&
	       IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d178 :
	       IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d178 ;
  assign IF_NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO__ETC___d237 =
	     (!rg_action &&
	      rg_prev_6_BITS_16_TO_15_7_EQ_rg_eEpoch_8_CONCA_ETC___d61) ?
	       { rg_prev[18:17] != 2'b11,
		 x__h2247,
		 rg_prev[11] && rg_prev[12],
		 rg_prev[11:0] } :
	       { IF_IF_rx_fromstage0_w_data_whas__8_THEN_rx_fro_ETC___d209,
		 x1_avValue_snd_snd_fst_prediction__h4148,
		 IF_IF_rx_fromstage0_w_data_whas__8_THEN_rx_fro_ETC___d232,
		 rx_from_stage0_first_x[11:0] } ;
  assign IF_NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO__ETC___d249 =
	     (!rg_action &&
	      rg_prev_6_BITS_16_TO_15_7_EQ_rg_eEpoch_8_CONCA_ETC___d61) ?
	       rg_prev[18:17] != 2'b11 ||
	       IF_ff_memory_response_ff_i_notEmpty_THEN_NOT_f_ETC___d175 :
	       IF_ff_memory_response_ff_i_notEmpty_THEN_NOT_f_ETC___d175 ;
  assign IF_NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO__ETC___d262 =
	     (!rg_action &&
	      rg_prev_6_BITS_16_TO_15_7_EQ_rg_eEpoch_8_CONCA_ETC___d61) ?
	       rg_prev[18:17] == 2'b11 :
	       ((rx_from_stage0_first_x[15] && csr_misa_c_c) ?
		  IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d69[17:16] ==
		  2'b11 :
		  IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d69[1:0] ==
		  2'b11 ||
		  !csr_misa_c_c) ;
  assign IF_NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO__ETC___d276 =
	     (!rg_action &&
	      rg_prev_6_BITS_16_TO_15_7_EQ_rg_eEpoch_8_CONCA_ETC___d61) ?
	       !rg_prev[11] || !rg_prev[12] :
	       ((rx_from_stage0_first_x[15] && csr_misa_c_c) ?
		  !rx_from_stage0_first_x[11] || !rx_from_stage0_first_x[12] :
		  IF_IF_ff_memory_response_ff_i_notEmpty_THEN_ff_ETC___d274) ;
  assign IF_NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO__ETC___d279 =
	     (!rg_action &&
	      rg_prev_6_BITS_16_TO_15_7_EQ_rg_eEpoch_8_CONCA_ETC___d61) ?
	       rg_prev[11] && rg_prev[12] :
	       IF_IF_rx_fromstage0_w_data_whas__8_THEN_rx_fro_ETC___d232 ;
  assign IF_NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO__ETC___d282 =
	     (!rg_action &&
	      rg_prev_6_BITS_16_TO_15_7_EQ_rg_eEpoch_8_CONCA_ETC___d61) ?
	       !rg_prev[11] :
	       !rx_from_stage0_first_x[11] ;
  assign IF_NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO__ETC___d285 =
	     (!rg_action &&
	      rg_prev_6_BITS_16_TO_15_7_EQ_rg_eEpoch_8_CONCA_ETC___d61) ?
	       rg_prev[11] :
	       rx_from_stage0_first_x[11] ;
  assign IF_NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO__ETC___d97 =
	     (!rg_action &&
	      rg_prev_6_BITS_16_TO_15_7_EQ_rg_eEpoch_8_CONCA_ETC___d61) ?
	       rg_prev[18:17] == 2'b11 &&
	       IF_rg_prev_6_BIT_11_9_THEN_rg_prev_6_BITS_14_T_ETC___d92 :
	       rx_from_stage0_first_x[15] && csr_misa_c_c ||
	       rx_from_stage0_first_x[11] ||
	       IF_rx_fromstage0_w_data_whas__8_THEN_rx_fromst_ETC___d94 ;
  assign IF_ff_memory_response_ff_i_notEmpty_THEN_NOT_f_ETC___d175 =
	     ff_memory_response_ff_EMPTY_N ?
	       !ff_memory_response_ff_D_OUT[8] :
	       !inst_response_put[8] ;
  assign IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d178 =
	     ff_memory_response_ff_EMPTY_N ?
	       ff_memory_response_ff_D_OUT[8] :
	       inst_response_put[8] ;
  assign IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d69 =
	     ff_memory_response_ff_EMPTY_N ?
	       ff_memory_response_ff_D_OUT[40:9] :
	       inst_response_put[40:9] ;
  assign IF_rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_m_ETC___d169 =
	     rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d84 ?
	       x1_avValue_snd_snd_snd_fst_address__h3566 :
	       rx_from_stage0_first_x[79:16] ;
  assign IF_rg_prev_6_BIT_11_9_THEN_rg_prev_6_BITS_14_T_ETC___d92 =
	     x__h2247 <= 2'd1 ;
  assign IF_rx_fromstage0_w_data_whas__8_THEN_rx_fromst_ETC___d94 =
	     rx_from_stage0_first_x[14:13] <= 2'd1 ;
  assign NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO_15__ETC___d107 =
	     !rg_action &&
	     rg_prev_6_BITS_16_TO_15_7_EQ_rg_eEpoch_8_CONCA_ETC___d61 &&
	     (!IF_rg_prev_6_BIT_11_9_THEN_rg_prev_6_BITS_14_T_ETC___d92 ||
	      rg_prev[18:17] != 2'b11) ||
	     (rg_action ||
	      !rg_prev_6_BITS_16_TO_15_7_EQ_rg_eEpoch_8_CONCA_ETC___d61) &&
	     (IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d69[1:0] ==
	      2'b11 ||
	      csr_misa_c_c) ;
  assign NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO_15__ETC___d196 =
	     !rg_action &&
	     rg_prev_6_BITS_16_TO_15_7_EQ_rg_eEpoch_8_CONCA_ETC___d61 ||
	     !rx_from_stage0_first_x[15] ||
	     !csr_misa_c_c ||
	     IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d69[17:16] !=
	     2'b11 ;
  assign NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO_15__ETC___d86 =
	     !rg_action &&
	     rg_prev_6_BITS_16_TO_15_7_EQ_rg_eEpoch_8_CONCA_ETC___d61 ||
	     rx_from_stage0_first_x[15] && csr_misa_c_c &&
	     IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d69[17:16] ==
	     2'b11 ||
	     !rx_from_stage0_first_x[15] &&
	     IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d69[1:0] !=
	     2'b11 &&
	     csr_misa_c_c ||
	     !rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d84 ;
  assign cause__h3429 =
	     ff_memory_response_ff_EMPTY_N ?
	       ff_memory_response_ff_D_OUT[7:2] :
	       inst_response_put[7:2] ;
  assign curr_epoch__h1421 = { rg_eEpoch, rg_wEpoch } ;
  assign ff_memory_response_firstValid_read_AND_ff_memo_ETC___d19 =
	     ff_memory_response_firstValid_Q_OUT &&
	     (ff_memory_response_ff_EMPTY_N || EN_inst_response_put) &&
	     rx_from_stage0_first_deq_rdy_b &&
	     EN_csr_misa_c &&
	     tx_to_stage2_inst_enq_rdy_b &&
	     tx_to_stage2_enq_rdy_b ;
  assign final_instruction__h3085 = tx_to_stage2_inst_enq_data ;
  assign pipedata_instruction__h4092 =
	     (rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d84 &&
	      IF_NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO__ETC___d210) ?
	       final_instruction___1__h4103 :
	       final_instruction__h3085 ;
  assign rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_CONCAT_IF_rg__ETC___d152 =
	     { curr_epoch__h1421,
	       rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d84 ?
		 IF_NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO__ETC___d150 :
		 rg_prev[14:0] } ;
  assign rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d84 =
	     curr_epoch__h1421 == y__h1735 ;
  assign rg_prev_6_BITS_16_TO_15_7_EQ_rg_eEpoch_8_CONCA_ETC___d61 =
	     rg_prev[16:15] == curr_epoch__h1421 ;
  assign rx_from_stage0_first_x_BITS_79_TO_16__q1 =
	     rx_from_stage0_first_x[79:16] ;
  assign x1_avValue_snd_fst_prediction__h4140 =
	     csr_misa_c_c ?
	       y_avValue_snd_fst_prediction__h4136 :
	       rx_from_stage0_first_x[14:13] ;
  assign x1_avValue_snd_fst_prediction__h4144 =
	     (IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d69[1:0] ==
	      2'b11) ?
	       rx_from_stage0_first_x[14:13] :
	       x1_avValue_snd_fst_prediction__h4140 ;
  assign x1_avValue_snd_snd_fst_address__h3552 =
	     { rg_prev[96:35], 1'd1, rg_prev[33] } ;
  assign x1_avValue_snd_snd_fst_address__h3560 =
	     (IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d69[17:16] ==
	      2'b11) ?
	       rx_from_stage0_first_x[79:16] :
	       y_avValue_snd_snd_fst_address__h3557 ;
  assign x1_avValue_snd_snd_fst_history__h4155 =
	     (!rg_action &&
	      rg_prev_6_BITS_16_TO_15_7_EQ_rg_eEpoch_8_CONCA_ETC___d61) ?
	       rg_prev[10:0] :
	       rx_from_stage0_first_x[10:0] ;
  assign x1_avValue_snd_snd_fst_prediction__h4148 =
	     (rx_from_stage0_first_x[15] && csr_misa_c_c) ?
	       y_avValue_snd_snd_fst_prediction__h4128 :
	       x1_avValue_snd_fst_prediction__h4144 ;
  assign x1_avValue_snd_snd_fst_prediction__h4152 =
	     (!rg_action &&
	      rg_prev_6_BITS_16_TO_15_7_EQ_rg_eEpoch_8_CONCA_ETC___d61) ?
	       x__h2247 :
	       x1_avValue_snd_snd_fst_prediction__h4148 ;
  assign x1_avValue_snd_snd_snd_fst_address__h3563 =
	     (rx_from_stage0_first_x[15] && csr_misa_c_c) ?
	       x1_avValue_snd_snd_fst_address__h3560 :
	       rx_from_stage0_first_x[79:16] ;
  assign x1_avValue_snd_snd_snd_fst_address__h3566 =
	     (!rg_action &&
	      rg_prev_6_BITS_16_TO_15_7_EQ_rg_eEpoch_8_CONCA_ETC___d61) ?
	       x1_avValue_snd_snd_fst_address__h3552 :
	       x1_avValue_snd_snd_snd_fst_address__h3563 ;
  assign x1_avValue_snd_snd_snd_instruction__h3295 =
	     csr_misa_c_c ?
	       IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d69[31:16] :
	       rg_prev[32:17] ;
  assign x1_avValue_snd_snd_snd_instruction__h3299 =
	     (IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d69[1:0] ==
	      2'b11) ?
	       rg_prev[32:17] :
	       x1_avValue_snd_snd_snd_instruction__h3295 ;
  assign x1_avValue_snd_snd_snd_pc__h3294 =
	     csr_misa_c_c ? rx_from_stage0_first_x[79:16] : rg_prev[96:33] ;
  assign x1_avValue_snd_snd_snd_pc__h3298 =
	     (IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d69[1:0] ==
	      2'b11) ?
	       rg_prev[96:33] :
	       x1_avValue_snd_snd_snd_pc__h3294 ;
  assign x1_avValue_snd_snd_snd_snd_instruction__h3193 =
	     (rg_prev[18:17] == 2'b11) ?
	       IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d69[31:16] :
	       rg_prev[32:17] ;
  assign x1_avValue_snd_snd_snd_snd_pc__h3192 =
	     (rg_prev[18:17] == 2'b11) ?
	       rx_from_stage0_first_x[79:16] :
	       rg_prev[96:33] ;
  assign x1_avValue_snd_snd_snd_snd_snd_instruction__h3260 =
	     (IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d69[17:16] ==
	      2'b11) ?
	       IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d69[31:16] :
	       rg_prev[32:17] ;
  assign x1_avValue_snd_snd_snd_snd_snd_pc__h3259 =
	     (IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d69[17:16] ==
	      2'b11) ?
	       rx_from_stage0_first_x[79:16] :
	       rg_prev[96:33] ;
  assign x1_avValue_snd_snd_snd_snd_snd_snd_instruction__h3303 =
	     (rx_from_stage0_first_x[15] && csr_misa_c_c) ?
	       x1_avValue_snd_snd_snd_snd_snd_instruction__h3260 :
	       x1_avValue_snd_snd_snd_instruction__h3299 ;
  assign x1_avValue_snd_snd_snd_snd_snd_snd_instruction__h3307 =
	     (!rg_action &&
	      rg_prev_6_BITS_16_TO_15_7_EQ_rg_eEpoch_8_CONCA_ETC___d61) ?
	       x1_avValue_snd_snd_snd_snd_instruction__h3193 :
	       x1_avValue_snd_snd_snd_snd_snd_snd_instruction__h3303 ;
  assign x1_avValue_snd_snd_snd_snd_snd_snd_pc__h3302 =
	     (rx_from_stage0_first_x[15] && csr_misa_c_c) ?
	       x1_avValue_snd_snd_snd_snd_snd_pc__h3259 :
	       x1_avValue_snd_snd_snd_pc__h3298 ;
  assign x1_avValue_snd_snd_snd_snd_snd_snd_pc__h3306 =
	     (!rg_action &&
	      rg_prev_6_BITS_16_TO_15_7_EQ_rg_eEpoch_8_CONCA_ETC___d61) ?
	       x1_avValue_snd_snd_snd_snd_pc__h3192 :
	       x1_avValue_snd_snd_snd_snd_snd_snd_pc__h3302 ;
  assign x__h2247 = rg_prev[11] ? rg_prev[14:13] : 2'd1 ;
  assign x_instruction__h3108 =
	     rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d84 ?
	       x1_avValue_snd_snd_snd_snd_snd_snd_instruction__h3307 :
	       rg_prev[32:17] ;
  assign x_pc__h3107 =
	     rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d84 ?
	       x1_avValue_snd_snd_snd_snd_snd_snd_pc__h3306 :
	       rg_prev[96:33] ;
  assign y__h1735 =
	     ff_memory_response_ff_EMPTY_N ?
	       ff_memory_response_ff_D_OUT[1:0] :
	       inst_response_put[1:0] ;
  assign y_avValue_snd_fst_prediction__h4136 =
	     rx_from_stage0_first_x[11] ?
	       2'd1 :
	       rx_from_stage0_first_x[14:13] ;
  assign y_avValue_snd_snd_fst__h3273 =
	     { 16'd0,
	       IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d69[15:0] } ;
  assign y_avValue_snd_snd_fst_address__h3557 =
	     { rx_from_stage0_first_x_BITS_79_TO_16__q1[63:2],
	       1'd1,
	       rx_from_stage0_first_x_BITS_79_TO_16__q1[0] } ;
  assign y_avValue_snd_snd_fst_prediction__h4128 =
	     rx_from_stage0_first_x[11] ?
	       rx_from_stage0_first_x[14:13] :
	       2'd1 ;
  assign y_avValue_snd_snd_snd_snd_fst__h3152 =
	     { (rg_prev[18:17] == 2'b11) ?
		 IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d69[15:0] :
		 16'd0,
	       rg_prev[32:17] } ;
  assign y_avValue_snd_snd_snd_snd_fst__h3154 =
	     (rx_from_stage0_first_x[15] && csr_misa_c_c) ?
	       y_avValue_snd_snd_snd_snd_fst__h3213 :
	       y_avValue_snd_snd_snd_snd_fst__h3215 ;
  assign y_avValue_snd_snd_snd_snd_fst__h3213 =
	     { 16'd0,
	       IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d69[31:16] } ;
  assign y_avValue_snd_snd_snd_snd_fst__h3215 =
	     (IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d69[1:0] ==
	      2'b11) ?
	       IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d69 :
	       y_avValue_snd_snd_fst__h3273 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        rg_action <= `BSV_ASSIGNMENT_DELAY 1'd1;
	rg_eEpoch <= `BSV_ASSIGNMENT_DELAY 1'd0;
	rg_prev <= `BSV_ASSIGNMENT_DELAY
	    97'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */ ;
	rg_receiving_upper <= `BSV_ASSIGNMENT_DELAY 1'd0;
	rg_wEpoch <= `BSV_ASSIGNMENT_DELAY 1'd0;
      end
    else
      begin
        if (rg_action_EN) rg_action <= `BSV_ASSIGNMENT_DELAY rg_action_D_IN;
	if (rg_eEpoch_EN) rg_eEpoch <= `BSV_ASSIGNMENT_DELAY rg_eEpoch_D_IN;
	if (rg_prev_EN) rg_prev <= `BSV_ASSIGNMENT_DELAY rg_prev_D_IN;
	if (rg_receiving_upper_EN)
	  rg_receiving_upper <= `BSV_ASSIGNMENT_DELAY rg_receiving_upper_D_IN;
	if (rg_wEpoch_EN) rg_wEpoch <= `BSV_ASSIGNMENT_DELAY rg_wEpoch_D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    rg_action = 1'h0;
    rg_eEpoch = 1'h0;
    rg_prev = 97'h0AAAAAAAAAAAAAAAAAAAAAAAA;
    rg_receiving_upper = 1'h0;
    rg_wEpoch = 1'h0;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_inst_response_put)
	begin
	  TASK_testplusargs___d290 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_inst_response_put)
	begin
	  TASK_testplusargs___d291 = $test$plusargs("mstage1");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_inst_response_put)
	begin
	  TASK_testplusargs___d292 = $test$plusargs("l3");
	  #0;
	end
    TASK_testplusargs_90_OR_TASK_testplusargs_91_A_ETC___d298 =
	(TASK_testplusargs___d290 ||
	 TASK_testplusargs___d291 && TASK_testplusargs___d292) &&
	inst_response_put[8];
    TASK_testplusargs_90_OR_TASK_testplusargs_91_A_ETC___d300 =
	(TASK_testplusargs___d290 ||
	 TASK_testplusargs___d291 && TASK_testplusargs___d292) &&
	!inst_response_put[8];
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_inst_response_put)
	begin
	  v__h4509 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_inst_response_put &&
	  (TASK_testplusargs___d290 ||
	   TASK_testplusargs___d291 && TASK_testplusargs___d292))
	$write("[%10d", v__h4509, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_inst_response_put &&
	  (TASK_testplusargs___d290 ||
	   TASK_testplusargs___d291 && TASK_testplusargs___d292))
	$write("core:%2d ", hartid, "STAGE1: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_inst_response_put &&
	  (TASK_testplusargs___d290 ||
	   TASK_testplusargs___d291 && TASK_testplusargs___d292))
	$write("FetchResponse { ", "instr: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_inst_response_put &&
	  (TASK_testplusargs___d290 ||
	   TASK_testplusargs___d291 && TASK_testplusargs___d292))
	$write("'h%h", inst_response_put[40:9]);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_inst_response_put &&
	  (TASK_testplusargs___d290 ||
	   TASK_testplusargs___d291 && TASK_testplusargs___d292))
	$write(", ", "trap: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_inst_response_put &&
	  TASK_testplusargs_90_OR_TASK_testplusargs_91_A_ETC___d298)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_inst_response_put &&
	  TASK_testplusargs_90_OR_TASK_testplusargs_91_A_ETC___d300)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_inst_response_put &&
	  (TASK_testplusargs___d290 ||
	   TASK_testplusargs___d291 && TASK_testplusargs___d292))
	$write(", ", "cause: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_inst_response_put &&
	  (TASK_testplusargs___d290 ||
	   TASK_testplusargs___d291 && TASK_testplusargs___d292))
	$write("'h%h", inst_response_put[7:2]);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_inst_response_put &&
	  (TASK_testplusargs___d290 ||
	   TASK_testplusargs___d291 && TASK_testplusargs___d292))
	$write(", ", "epochs: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_inst_response_put &&
	  (TASK_testplusargs___d290 ||
	   TASK_testplusargs___d291 && TASK_testplusargs___d292))
	$write("'h%h", inst_response_put[1:0], " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_inst_response_put &&
	  (TASK_testplusargs___d290 ||
	   TASK_testplusargs___d291 && TASK_testplusargs___d292))
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction)
	begin
	  TASK_testplusargs___d22 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction)
	begin
	  TASK_testplusargs___d23 = $test$plusargs("mstage1");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction)
	begin
	  TASK_testplusargs___d24 = $test$plusargs("l1");
	  #0;
	end
    TASK_testplusargs_2_OR_TASK_testplusargs_3_AND_ETC___d35 =
	(TASK_testplusargs___d22 ||
	 TASK_testplusargs___d23 && TASK_testplusargs___d24) &&
	!rx_from_stage0_first_x[15];
    TASK_testplusargs_2_OR_TASK_testplusargs_3_AND_ETC___d37 =
	(TASK_testplusargs___d22 ||
	 TASK_testplusargs___d23 && TASK_testplusargs___d24) &&
	rx_from_stage0_first_x[15];
    TASK_testplusargs_2_OR_TASK_testplusargs_3_AND_ETC___d43 =
	(TASK_testplusargs___d22 ||
	 TASK_testplusargs___d23 && TASK_testplusargs___d24) &&
	!rx_from_stage0_first_x[12];
    TASK_testplusargs_2_OR_TASK_testplusargs_3_AND_ETC___d45 =
	(TASK_testplusargs___d22 ||
	 TASK_testplusargs___d23 && TASK_testplusargs___d24) &&
	rx_from_stage0_first_x[12];
    TASK_testplusargs_2_OR_TASK_testplusargs_3_AND_ETC___d51 =
	(TASK_testplusargs___d22 ||
	 TASK_testplusargs___d23 && TASK_testplusargs___d24) &&
	rx_from_stage0_first_x[11];
    TASK_testplusargs_2_OR_TASK_testplusargs_3_AND_ETC___d49 =
	(TASK_testplusargs___d22 ||
	 TASK_testplusargs___d23 && TASK_testplusargs___d24) &&
	!rx_from_stage0_first_x[11];
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction)
	begin
	  v__h1514 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d22 ||
	   TASK_testplusargs___d23 && TASK_testplusargs___d24))
	$write("[%10d", v__h1514, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d22 ||
	   TASK_testplusargs___d23 && TASK_testplusargs___d24))
	$write("core:%2d ", hartid, "STAGE1 : Prediction: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d22 ||
	   TASK_testplusargs___d23 && TASK_testplusargs___d24))
	$write("Stage0PC { ", "address: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d22 ||
	   TASK_testplusargs___d23 && TASK_testplusargs___d24))
	$write("'h%h", rx_from_stage0_first_x[79:16]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d22 ||
	   TASK_testplusargs___d23 && TASK_testplusargs___d24))
	$write(", ", "discard: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  TASK_testplusargs_2_OR_TASK_testplusargs_3_AND_ETC___d35)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  TASK_testplusargs_2_OR_TASK_testplusargs_3_AND_ETC___d37)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d22 ||
	   TASK_testplusargs___d23 && TASK_testplusargs___d24))
	$write(", ", "btbresponse: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d22 ||
	   TASK_testplusargs___d23 && TASK_testplusargs___d24))
	$write("BTBResponse { ", "prediction: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d22 ||
	   TASK_testplusargs___d23 && TASK_testplusargs___d24))
	$write("'h%h", rx_from_stage0_first_x[14:13]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d22 ||
	   TASK_testplusargs___d23 && TASK_testplusargs___d24))
	$write(", ", "btbhit: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  TASK_testplusargs_2_OR_TASK_testplusargs_3_AND_ETC___d43)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  TASK_testplusargs_2_OR_TASK_testplusargs_3_AND_ETC___d45)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d22 ||
	   TASK_testplusargs___d23 && TASK_testplusargs___d24))
	$write(", ", "hi: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  TASK_testplusargs_2_OR_TASK_testplusargs_3_AND_ETC___d49)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  TASK_testplusargs_2_OR_TASK_testplusargs_3_AND_ETC___d51)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d22 ||
	   TASK_testplusargs___d23 && TASK_testplusargs___d24))
	$write(", ", "history: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d22 ||
	   TASK_testplusargs___d23 && TASK_testplusargs___d24))
	$write("'h%h", rx_from_stage0_first_x[10:0], " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d22 ||
	   TASK_testplusargs___d23 && TASK_testplusargs___d24))
	$write(" }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d22 ||
	   TASK_testplusargs___d23 && TASK_testplusargs___d24))
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  !rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d84)
	begin
	  TASK_testplusargs___d118 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  !rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d84)
	begin
	  TASK_testplusargs___d119 = $test$plusargs("mstage1");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  !rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d84)
	begin
	  TASK_testplusargs___d120 = $test$plusargs("l1");
	  #0;
	end
    NOT_rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff__ETC___d123 =
	!rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d84 &&
	(TASK_testplusargs___d118 ||
	 TASK_testplusargs___d119 && TASK_testplusargs___d120);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  !rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d84)
	begin
	  v__h1956 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  NOT_rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff__ETC___d123)
	$write("[%10d", v__h1956, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  NOT_rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff__ETC___d123)
	$write("core:%2d ", hartid, "STAGE1 : Dropping Instruction");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  NOT_rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff__ETC___d123)
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction)
	begin
	  TASK_testplusargs___d154 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction)
	begin
	  TASK_testplusargs___d155 = $test$plusargs("mstage1");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction)
	begin
	  TASK_testplusargs___d156 = $test$plusargs("l0");
	  #0;
	end
    TASK_testplusargs_54_OR_TASK_testplusargs_55_A_ETC___d176 =
	(TASK_testplusargs___d154 ||
	 TASK_testplusargs___d155 && TASK_testplusargs___d156) &&
	IF_ff_memory_response_ff_i_notEmpty_THEN_NOT_f_ETC___d175;
    TASK_testplusargs_54_OR_TASK_testplusargs_55_A_ETC___d179 =
	(TASK_testplusargs___d154 ||
	 TASK_testplusargs___d155 && TASK_testplusargs___d156) &&
	IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d178;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction)
	begin
	  v__h3497 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d154 ||
	   TASK_testplusargs___d155 && TASK_testplusargs___d156))
	$write("[%10d", v__h3497, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d154 ||
	   TASK_testplusargs___d155 && TASK_testplusargs___d156))
	$write("core:%2d ",
	       hartid,
	       "STAGE1 : PC:%h: ",
	       IF_rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_m_ETC___d169);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d154 ||
	   TASK_testplusargs___d155 && TASK_testplusargs___d156))
	$write("FetchResponse { ", "instr: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d154 ||
	   TASK_testplusargs___d155 && TASK_testplusargs___d156))
	$write("'h%h",
	       IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d69);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d154 ||
	   TASK_testplusargs___d155 && TASK_testplusargs___d156))
	$write(", ", "trap: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  TASK_testplusargs_54_OR_TASK_testplusargs_55_A_ETC___d176)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  TASK_testplusargs_54_OR_TASK_testplusargs_55_A_ETC___d179)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d154 ||
	   TASK_testplusargs___d155 && TASK_testplusargs___d156))
	$write(", ", "cause: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d154 ||
	   TASK_testplusargs___d155 && TASK_testplusargs___d156))
	$write("'h%h", cause__h3429);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d154 ||
	   TASK_testplusargs___d155 && TASK_testplusargs___d156))
	$write(", ", "epochs: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d154 ||
	   TASK_testplusargs___d155 && TASK_testplusargs___d156))
	$write("'h%h", y__h1735, " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d154 ||
	   TASK_testplusargs___d155 && TASK_testplusargs___d156))
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction)
	begin
	  TASK_testplusargs___d184 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction)
	begin
	  TASK_testplusargs___d185 = $test$plusargs("mstage1");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction)
	begin
	  TASK_testplusargs___d186 = $test$plusargs("l1");
	  #0;
	end
    TASK_testplusargs_84_OR_TASK_testplusargs_85_A_ETC___d190 =
	(TASK_testplusargs___d184 ||
	 TASK_testplusargs___d185 && TASK_testplusargs___d186) &&
	rg_action;
    TASK_testplusargs_84_OR_TASK_testplusargs_85_A_ETC___d191 =
	(TASK_testplusargs___d184 ||
	 TASK_testplusargs___d185 && TASK_testplusargs___d186) &&
	!rg_action;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction)
	begin
	  v__h3790 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d184 ||
	   TASK_testplusargs___d185 && TASK_testplusargs___d186))
	$write("[%10d", v__h3790, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d184 ||
	   TASK_testplusargs___d185 && TASK_testplusargs___d186))
	$write("core:%2d ", hartid, "STAGE1 : rg_action: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  TASK_testplusargs_84_OR_TASK_testplusargs_85_A_ETC___d190)
	$write("None");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  TASK_testplusargs_84_OR_TASK_testplusargs_85_A_ETC___d191)
	$write("CheckPrev");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d184 ||
	   TASK_testplusargs___d185 && TASK_testplusargs___d186))
	$write(" misa[c]:%b discard:%b rg_receiving_upper:%b",
	       csr_misa_c_c,
	       rx_from_stage0_first_x[15],
	       rg_receiving_upper);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  (TASK_testplusargs___d184 ||
	   TASK_testplusargs___d185 && TASK_testplusargs___d186))
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d84 &&
	  NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO_15__ETC___d196)
	begin
	  TASK_testplusargs___d241 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d84 &&
	  NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO_15__ETC___d196)
	begin
	  TASK_testplusargs___d242 = $test$plusargs("mstage1");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d84 &&
	  NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO_15__ETC___d196)
	begin
	  TASK_testplusargs___d243 = $test$plusargs("l0");
	  #0;
	end
    TASK_testplusargs_41_OR_TASK_testplusargs_42_A_ETC___d250 =
	(TASK_testplusargs___d241 ||
	 TASK_testplusargs___d242 && TASK_testplusargs___d243) &&
	IF_NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO__ETC___d249;
    TASK_testplusargs_41_OR_TASK_testplusargs_42_A_ETC___d252 =
	(TASK_testplusargs___d241 ||
	 TASK_testplusargs___d242 && TASK_testplusargs___d243) &&
	IF_NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO__ETC___d216;
    TASK_testplusargs_41_OR_TASK_testplusargs_42_A_ETC___d256 =
	(TASK_testplusargs___d241 ||
	 TASK_testplusargs___d242 && TASK_testplusargs___d243) &&
	(!rg_receiving_upper ||
	 IF_ff_memory_response_ff_i_notEmpty_THEN_NOT_f_ETC___d175);
    TASK_testplusargs_41_OR_TASK_testplusargs_42_A_ETC___d258 =
	(TASK_testplusargs___d241 ||
	 TASK_testplusargs___d242 && TASK_testplusargs___d243) &&
	rg_receiving_upper &&
	IF_ff_memory_response_ff_i_notEmpty_THEN_ff_me_ETC___d178;
    TASK_testplusargs_41_OR_TASK_testplusargs_42_A_ETC___d263 =
	(TASK_testplusargs___d241 ||
	 TASK_testplusargs___d242 && TASK_testplusargs___d243) &&
	IF_NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO__ETC___d262;
    TASK_testplusargs_41_OR_TASK_testplusargs_42_A_ETC___d265 =
	(TASK_testplusargs___d241 ||
	 TASK_testplusargs___d242 && TASK_testplusargs___d243) &&
	IF_NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO__ETC___d210;
    TASK_testplusargs_41_OR_TASK_testplusargs_42_A_ETC___d277 =
	(TASK_testplusargs___d241 ||
	 TASK_testplusargs___d242 && TASK_testplusargs___d243) &&
	IF_NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO__ETC___d276;
    TASK_testplusargs_41_OR_TASK_testplusargs_42_A_ETC___d280 =
	(TASK_testplusargs___d241 ||
	 TASK_testplusargs___d242 && TASK_testplusargs___d243) &&
	IF_NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO__ETC___d279;
    TASK_testplusargs_41_OR_TASK_testplusargs_42_A_ETC___d283 =
	(TASK_testplusargs___d241 ||
	 TASK_testplusargs___d242 && TASK_testplusargs___d243) &&
	IF_NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO__ETC___d282;
    rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d246 =
	rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d84 &&
	NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO_15__ETC___d196 &&
	(TASK_testplusargs___d241 ||
	 TASK_testplusargs___d242 && TASK_testplusargs___d243);
    TASK_testplusargs_41_OR_TASK_testplusargs_42_A_ETC___d286 =
	(TASK_testplusargs___d241 ||
	 TASK_testplusargs___d242 && TASK_testplusargs___d243) &&
	IF_NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO__ETC___d285;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d84 &&
	  NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO_15__ETC___d196)
	begin
	  v__h4260 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d246)
	$write("[%10d", v__h4260, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d246)
	$write("core:%2d ", hartid, "STAGE1 : Enquing: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d246)
	$write("PIPE1 { ", "program_counter: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d246)
	$write("'h%h",
	       IF_rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_m_ETC___d169);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d246)
	$write(", ", "instruction: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d246)
	$write("'h%h", pipedata_instruction__h4092);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d246)
	$write(", ", "epochs: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d246)
	$write("'h%h", curr_epoch__h1421);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d246)
	$write(", ", "trap: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d84 &&
	  NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO_15__ETC___d196 &&
	  TASK_testplusargs_41_OR_TASK_testplusargs_42_A_ETC___d250)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d84 &&
	  NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO_15__ETC___d196 &&
	  TASK_testplusargs_41_OR_TASK_testplusargs_42_A_ETC___d252)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d246)
	$write(", ", "cause: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d246)
	$write("'h%h", cause__h3429);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d246)
	$write(", ", "upper_err: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d84 &&
	  NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO_15__ETC___d196 &&
	  TASK_testplusargs_41_OR_TASK_testplusargs_42_A_ETC___d256)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d84 &&
	  NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO_15__ETC___d196 &&
	  TASK_testplusargs_41_OR_TASK_testplusargs_42_A_ETC___d258)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d246)
	$write(", ", "compressed: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d84 &&
	  NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO_15__ETC___d196 &&
	  TASK_testplusargs_41_OR_TASK_testplusargs_42_A_ETC___d263)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d84 &&
	  NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO_15__ETC___d196 &&
	  TASK_testplusargs_41_OR_TASK_testplusargs_42_A_ETC___d265)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d246)
	$write(", ", "btbresponse: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d246)
	$write("BTBResponse { ", "prediction: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d246)
	$write("'h%h", x1_avValue_snd_snd_fst_prediction__h4152);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d246)
	$write(", ", "btbhit: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d84 &&
	  NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO_15__ETC___d196 &&
	  TASK_testplusargs_41_OR_TASK_testplusargs_42_A_ETC___d277)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d84 &&
	  NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO_15__ETC___d196 &&
	  TASK_testplusargs_41_OR_TASK_testplusargs_42_A_ETC___d280)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d246)
	$write(", ", "hi: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d84 &&
	  NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO_15__ETC___d196 &&
	  TASK_testplusargs_41_OR_TASK_testplusargs_42_A_ETC___d283)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d84 &&
	  NOT_rg_action_4_5_AND_rg_prev_6_BITS_16_TO_15__ETC___d196 &&
	  TASK_testplusargs_41_OR_TASK_testplusargs_42_A_ETC___d286)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d246)
	$write(", ", "history: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d246)
	$write("'h%h", x1_avValue_snd_snd_fst_history__h4155, " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d246)
	$write(" }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_process_instruction &&
	  rg_eEpoch_8_CONCAT_rg_wEpoch_9_0_EQ_IF_ff_memo_ETC___d246)
	$write("\n");
  end
  // synopsys translate_on
endmodule  // mkstage1

