/*
 * Generated by Bluespec Compiler (build a026416)
 * 
 * On Sun Aug  9 21:42:45 IST 2020
 * 
 */
#ifndef __vpi_wrapper_init_rbb_jtag_h__
#define __vpi_wrapper_init_rbb_jtag_h__

#include <vpi_user.h>

/* registration function */
void init_rbb_jtag_vpi_register();

/* VPI wrapper function */
PLI_INT32 init_rbb_jtag_calltf(PLI_BYTE8 *user_data);

#endif /* ifndef __vpi_wrapper_init_rbb_jtag_h__ */
