/*
 * Generated by Bluespec Compiler (build a026416)
 * 
 * On Mon Aug 17 18:03:36 IST 2020
 * 
 */
#ifndef __vpi_wrapper_get_frame_h__
#define __vpi_wrapper_get_frame_h__

#include <vpi_user.h>

/* registration function */
void get_frame_vpi_register();

/* VPI wrapper function */
PLI_INT32 get_frame_calltf(PLI_BYTE8 *user_data);

#endif /* ifndef __vpi_wrapper_get_frame_h__ */
