//
// Generated by Bluespec Compiler (build a026416)
//
// On Tue Aug 11 13:42:10 IST 2020
//
//
// Ports:
// Name                         I/O  size props
// RDY_core_request_put           O     1
// core_response_get              O    39 reg
// RDY_core_response_get          O     1 reg
// request_to_ptw_get             O    66 reg
// RDY_request_to_ptw_get         O     1 reg
// RDY_response_frm_ptw_put       O     1
// RDY_ma_satp_from_csr           O     1 const
// RDY_ma_curr_priv               O     1 const
// mv_perf_counters               O     1
// RDY_mv_perf_counters           O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// core_request_put               I    65
// response_frm_ptw_put           I    63
// ma_satp_from_csr_s             I    64
// ma_curr_priv_c                 I     2
// EN_core_request_put            I     1
// EN_response_frm_ptw_put        I     1
// EN_ma_satp_from_csr            I     1
// EN_ma_curr_priv                I     1
// EN_core_response_get           I     1
// EN_request_to_ptw_get          I     1
//
// Combinational paths from inputs to outputs:
//   (core_request_put,
//    ma_satp_from_csr_s,
//    ma_curr_priv_c,
//    EN_core_request_put,
//    EN_ma_satp_from_csr,
//    EN_ma_curr_priv) -> mv_perf_counters
//   (EN_ma_satp_from_csr, EN_ma_curr_priv) -> RDY_core_request_put
//   EN_ma_satp_from_csr -> RDY_response_frm_ptw_put
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkfa_itlb(CLK,
		 RST_N,

		 core_request_put,
		 EN_core_request_put,
		 RDY_core_request_put,

		 EN_core_response_get,
		 core_response_get,
		 RDY_core_response_get,

		 EN_request_to_ptw_get,
		 request_to_ptw_get,
		 RDY_request_to_ptw_get,

		 response_frm_ptw_put,
		 EN_response_frm_ptw_put,
		 RDY_response_frm_ptw_put,

		 ma_satp_from_csr_s,
		 EN_ma_satp_from_csr,
		 RDY_ma_satp_from_csr,

		 ma_curr_priv_c,
		 EN_ma_curr_priv,
		 RDY_ma_curr_priv,

		 mv_perf_counters,
		 RDY_mv_perf_counters);
  parameter [63 : 0] hartid = 64'b0;
  input  CLK;
  input  RST_N;

  // action method core_request_put
  input  [64 : 0] core_request_put;
  input  EN_core_request_put;
  output RDY_core_request_put;

  // actionvalue method core_response_get
  input  EN_core_response_get;
  output [38 : 0] core_response_get;
  output RDY_core_response_get;

  // actionvalue method request_to_ptw_get
  input  EN_request_to_ptw_get;
  output [65 : 0] request_to_ptw_get;
  output RDY_request_to_ptw_get;

  // action method response_frm_ptw_put
  input  [62 : 0] response_frm_ptw_put;
  input  EN_response_frm_ptw_put;
  output RDY_response_frm_ptw_put;

  // action method ma_satp_from_csr
  input  [63 : 0] ma_satp_from_csr_s;
  input  EN_ma_satp_from_csr;
  output RDY_ma_satp_from_csr;

  // action method ma_curr_priv
  input  [1 : 0] ma_curr_priv_c;
  input  EN_ma_curr_priv;
  output RDY_ma_curr_priv;

  // value method mv_perf_counters
  output mv_perf_counters;
  output RDY_mv_perf_counters;

  // signals for module outputs
  wire [65 : 0] request_to_ptw_get;
  wire [38 : 0] core_response_get;
  wire RDY_core_request_put,
       RDY_core_response_get,
       RDY_ma_curr_priv,
       RDY_ma_satp_from_csr,
       RDY_mv_perf_counters,
       RDY_request_to_ptw_get,
       RDY_response_frm_ptw_put,
       mv_perf_counters;

  // register rg_miss_queue
  reg [63 : 0] rg_miss_queue;
  wire [63 : 0] rg_miss_queue_D_IN;
  wire rg_miss_queue_EN;

  // register rg_replace
  reg [1 : 0] rg_replace;
  wire [1 : 0] rg_replace_D_IN;
  wire rg_replace_EN;

  // register rg_sfence
  reg rg_sfence;
  wire rg_sfence_D_IN, rg_sfence_EN;

  // register rg_tlb_miss
  reg rg_tlb_miss;
  wire rg_tlb_miss_D_IN, rg_tlb_miss_EN;

  // register v_vpn_tag_0
  reg [105 : 0] v_vpn_tag_0;
  wire [105 : 0] v_vpn_tag_0_D_IN;
  wire v_vpn_tag_0_EN;

  // register v_vpn_tag_1
  reg [105 : 0] v_vpn_tag_1;
  wire [105 : 0] v_vpn_tag_1_D_IN;
  wire v_vpn_tag_1_EN;

  // register v_vpn_tag_2
  reg [105 : 0] v_vpn_tag_2;
  wire [105 : 0] v_vpn_tag_2_D_IN;
  wire v_vpn_tag_2_EN;

  // register v_vpn_tag_3
  reg [105 : 0] v_vpn_tag_3;
  wire [105 : 0] v_vpn_tag_3_D_IN;
  wire v_vpn_tag_3_EN;

  // ports of submodule ff_core_respone
  wire [38 : 0] ff_core_respone_D_IN, ff_core_respone_D_OUT;
  wire ff_core_respone_CLR,
       ff_core_respone_DEQ,
       ff_core_respone_EMPTY_N,
       ff_core_respone_ENQ,
       ff_core_respone_FULL_N;

  // ports of submodule ff_request_to_ptw
  wire [65 : 0] ff_request_to_ptw_D_IN, ff_request_to_ptw_D_OUT;
  wire ff_request_to_ptw_CLR,
       ff_request_to_ptw_DEQ,
       ff_request_to_ptw_EMPTY_N,
       ff_request_to_ptw_ENQ,
       ff_request_to_ptw_FULL_N;

  // rule scheduling signals
  wire CAN_FIRE_RL_rl_fence,
       CAN_FIRE_core_request_put,
       CAN_FIRE_core_response_get,
       CAN_FIRE_ma_curr_priv,
       CAN_FIRE_ma_satp_from_csr,
       CAN_FIRE_request_to_ptw_get,
       CAN_FIRE_response_frm_ptw_put,
       WILL_FIRE_RL_rl_fence,
       WILL_FIRE_core_request_put,
       WILL_FIRE_core_response_get,
       WILL_FIRE_ma_curr_priv,
       WILL_FIRE_ma_satp_from_csr,
       WILL_FIRE_request_to_ptw_get,
       WILL_FIRE_response_frm_ptw_put;

  // inputs to muxes for submodule ports
  wire [105 : 0] MUX_v_vpn_tag_0_write_1__VAL_1;
  wire [38 : 0] MUX_ff_core_respone_enq_1__VAL_1,
		MUX_ff_core_respone_enq_1__VAL_2;
  wire [1 : 0] MUX_rg_replace_write_1__VAL_1;
  wire MUX_ff_core_respone_enq_1__SEL_1,
       MUX_rg_replace_write_1__SEL_1,
       MUX_rg_sfence_write_1__SEL_1,
       MUX_rg_tlb_miss_write_1__SEL_1,
       MUX_v_vpn_tag_0_write_1__SEL_1,
       MUX_v_vpn_tag_1_write_1__SEL_1,
       MUX_v_vpn_tag_2_write_1__SEL_1,
       MUX_v_vpn_tag_3_write_1__SEL_1;

  // declarations used by system tasks
  // synopsys translate_off
  reg TASK_testplusargs___d444;
  reg TASK_testplusargs___d445;
  reg TASK_testplusargs___d446;
  reg [63 : 0] v__h5943;
  reg TASK_testplusargs___d2;
  reg TASK_testplusargs___d3;
  reg TASK_testplusargs___d4;
  reg [63 : 0] v__h2324;
  reg TASK_testplusargs___d13;
  reg TASK_testplusargs___d14;
  reg TASK_testplusargs___d15;
  reg [63 : 0] v__h3114;
  reg TASK_testplusargs___d182;
  reg TASK_testplusargs___d183;
  reg TASK_testplusargs___d184;
  reg [63 : 0] v__h4322;
  reg TASK_testplusargs___d195;
  reg TASK_testplusargs___d196;
  reg TASK_testplusargs___d197;
  reg [63 : 0] v__h3305;
  reg TASK_testplusargs___d339;
  reg TASK_testplusargs___d340;
  reg TASK_testplusargs___d341;
  reg [63 : 0] v__h4429;
  reg TASK_testplusargs___d348;
  reg TASK_testplusargs___d349;
  reg TASK_testplusargs___d350;
  reg [63 : 0] v__h4589;
  reg TASK_testplusargs___d357;
  reg TASK_testplusargs___d358;
  reg TASK_testplusargs___d359;
  reg [63 : 0] v__h4749;
  reg TASK_testplusargs___d366;
  reg TASK_testplusargs___d367;
  reg TASK_testplusargs___d368;
  reg [63 : 0] v__h4906;
  reg TASK_testplusargs___d375;
  reg TASK_testplusargs___d376;
  reg TASK_testplusargs___d377;
  reg [63 : 0] v__h5075;
  reg TASK_testplusargs___d385;
  reg TASK_testplusargs___d386;
  reg TASK_testplusargs___d387;
  reg [63 : 0] v__h5236;
  reg TASK_testplusargs___d404;
  reg TASK_testplusargs___d405;
  reg TASK_testplusargs___d406;
  reg [63 : 0] v__h4167;
  reg wr_satp_wget__0_BITS_63_TO_60_1_EQ_0_2_OR_wr_p_ETC___d187;
  reg IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d200;
  reg TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d208;
  reg TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d218;
  reg TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d233;
  reg TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d240;
  reg TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d255;
  reg TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d262;
  reg TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d266;
  reg TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d273;
  reg TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d277;
  reg TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d281;
  reg TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d289;
  reg TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d296;
  reg TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d300;
  reg TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d307;
  reg TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d322;
  reg TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d329;
  reg IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d344;
  reg IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d353;
  reg IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d362;
  reg IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d371;
  reg IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d380;
  reg IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d390;
  reg NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d409;
  reg TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d453;
  reg TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d456;
  reg TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d459;
  reg TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d462;
  reg TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d465;
  reg TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d468;
  reg TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d471;
  reg TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d474;
  reg TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d477;
  reg TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d480;
  reg TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d483;
  reg TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d486;
  reg TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d489;
  reg TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d492;
  reg TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d495;
  reg TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d498;
  reg TASK_testplusargs_OR_TASK_testplusargs_AND_TAS_ETC___d10;
  reg TASK_testplusargs_OR_TASK_testplusargs_AND_TAS_ETC___d12;
  reg core_request_put_BIT_0_AND_TASK_testplusargs_3_ETC___d18;
  reg NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d202;
  reg NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d211;
  reg NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d221;
  reg NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d236;
  reg NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d243;
  reg NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d258;
  reg NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d265;
  reg NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d269;
  reg NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d276;
  reg NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d280;
  reg NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d284;
  reg NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d292;
  reg NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d299;
  reg NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d303;
  reg NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d310;
  reg NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d325;
  reg NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d332;
  reg NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d346;
  reg NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d355;
  reg NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d364;
  reg NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d373;
  reg NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d382;
  reg NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d392;
  reg NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d411;
  reg NOT_response_frm_ptw_put_BIT_6_42_43_AND_TASK__ETC___d449;
  // synopsys translate_on

  // remaining internal signals
  wire [63 : 0] physicaladdress__h4362;
  wire [55 : 0] x__h5289;
  wire [43 : 0] IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d114,
		x__h4642;
  wire [31 : 0] x_address__h5475, x_address__h5743;
  wire [26 : 0] IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d333,
		IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d335,
		tag_vpn__h5998;
  wire [17 : 0] IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d118,
		lower_pa__h4360,
		lower_pa__h5718,
		mask__h4357,
		mask__h5715,
		x__h4968,
		x__h4970,
		x__h5782,
		x__h5814,
		y__h4969,
		y__h5783;
  wire [9 : 0] _9_MUL_0_CONCAT_response_frm_ptw_put_BITS_8_TO__ETC___d428;
  wire [8 : 0] IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d336,
	       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d338;
  wire IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d100,
       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d101,
       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d102,
       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d138,
       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d140,
       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d149,
       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d151,
       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d160,
       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d162,
       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d165,
       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d167,
       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d177,
       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d207,
       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d217,
       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d230,
       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d232,
       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d237,
       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d239,
       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d252,
       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d254,
       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d259,
       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d261,
       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d270,
       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d272,
       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d286,
       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d288,
       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d293,
       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d295,
       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d304,
       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d306,
       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d319,
       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d321,
       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d326,
       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d328,
       NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d194,
       NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d403,
       NOT_core_request_put_BIT_0_1_AND_wr_satp_wget__ETC___d104,
       NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d205,
       NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d401,
       NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d62,
       NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d80,
       _511_CONCAT_v_vpn_tag_0_6_BITS_61_TO_44_9_0_AND_ETC___d34,
       _511_CONCAT_v_vpn_tag_1_5_BITS_61_TO_44_8_9_AND_ETC___d52,
       _511_CONCAT_v_vpn_tag_2_3_BITS_61_TO_44_6_7_AND_ETC___d70,
       _511_CONCAT_v_vpn_tag_3_1_BITS_61_TO_44_3_4_AND_ETC___d87,
       v_vpn_tag_0_6_BITS_70_TO_62_7_EQ_wr_satp_wget__ETC___d39,
       v_vpn_tag_0_6_BIT_98_7_AND_511_CONCAT_v_vpn_ta_ETC___d215,
       v_vpn_tag_1_5_BITS_70_TO_62_5_EQ_wr_satp_wget__ETC___d56,
       v_vpn_tag_2_3_BITS_70_TO_62_3_EQ_wr_satp_wget__ETC___d74,
       v_vpn_tag_3_1_BITS_70_TO_62_9_EQ_wr_satp_wget__ETC___d90;

  // action method core_request_put
  assign RDY_core_request_put =
	     !rg_sfence && !rg_tlb_miss && EN_ma_satp_from_csr &&
	     EN_ma_curr_priv &&
	     ff_core_respone_FULL_N &&
	     ff_request_to_ptw_FULL_N ;
  assign CAN_FIRE_core_request_put = RDY_core_request_put ;
  assign WILL_FIRE_core_request_put = EN_core_request_put ;

  // actionvalue method core_response_get
  assign core_response_get = ff_core_respone_D_OUT ;
  assign RDY_core_response_get = ff_core_respone_EMPTY_N ;
  assign CAN_FIRE_core_response_get = ff_core_respone_EMPTY_N ;
  assign WILL_FIRE_core_response_get = EN_core_response_get ;

  // actionvalue method request_to_ptw_get
  assign request_to_ptw_get = ff_request_to_ptw_D_OUT ;
  assign RDY_request_to_ptw_get = ff_request_to_ptw_EMPTY_N ;
  assign CAN_FIRE_request_to_ptw_get = ff_request_to_ptw_EMPTY_N ;
  assign WILL_FIRE_request_to_ptw_get = EN_request_to_ptw_get ;

  // action method response_frm_ptw_put
  assign RDY_response_frm_ptw_put =
	     rg_tlb_miss && !rg_sfence && ff_core_respone_FULL_N &&
	     EN_ma_satp_from_csr ;
  assign CAN_FIRE_response_frm_ptw_put =
	     rg_tlb_miss && !rg_sfence && ff_core_respone_FULL_N &&
	     EN_ma_satp_from_csr ;
  assign WILL_FIRE_response_frm_ptw_put = EN_response_frm_ptw_put ;

  // action method ma_satp_from_csr
  assign RDY_ma_satp_from_csr = 1'd1 ;
  assign CAN_FIRE_ma_satp_from_csr = 1'd1 ;
  assign WILL_FIRE_ma_satp_from_csr = EN_ma_satp_from_csr ;

  // action method ma_curr_priv
  assign RDY_ma_curr_priv = 1'd1 ;
  assign CAN_FIRE_ma_curr_priv = 1'd1 ;
  assign WILL_FIRE_ma_curr_priv = EN_ma_curr_priv ;

  // value method mv_perf_counters
  assign mv_perf_counters = MUX_rg_tlb_miss_write_1__SEL_1 ;
  assign RDY_mv_perf_counters = 1'd1 ;

  // submodule ff_core_respone
  FIFO2 #(.width(32'd39), .guarded(32'd1)) ff_core_respone(.RST(RST_N),
							   .CLK(CLK),
							   .D_IN(ff_core_respone_D_IN),
							   .ENQ(ff_core_respone_ENQ),
							   .DEQ(ff_core_respone_DEQ),
							   .CLR(ff_core_respone_CLR),
							   .D_OUT(ff_core_respone_D_OUT),
							   .FULL_N(ff_core_respone_FULL_N),
							   .EMPTY_N(ff_core_respone_EMPTY_N));

  // submodule ff_request_to_ptw
  FIFO2 #(.width(32'd66), .guarded(32'd1)) ff_request_to_ptw(.RST(RST_N),
							     .CLK(CLK),
							     .D_IN(ff_request_to_ptw_D_IN),
							     .ENQ(ff_request_to_ptw_ENQ),
							     .DEQ(ff_request_to_ptw_DEQ),
							     .CLR(ff_request_to_ptw_CLR),
							     .D_OUT(ff_request_to_ptw_D_OUT),
							     .FULL_N(ff_request_to_ptw_FULL_N),
							     .EMPTY_N(ff_request_to_ptw_EMPTY_N));

  // rule RL_rl_fence
  assign CAN_FIRE_RL_rl_fence = rg_sfence ;
  assign WILL_FIRE_RL_rl_fence = rg_sfence ;

  // inputs to muxes for submodule ports
  assign MUX_ff_core_respone_enq_1__SEL_1 =
	     EN_core_request_put &&
	     NOT_core_request_put_BIT_0_1_AND_wr_satp_wget__ETC___d104 ;
  assign MUX_rg_replace_write_1__SEL_1 =
	     EN_response_frm_ptw_put && !response_frm_ptw_put[6] ;
  assign MUX_rg_sfence_write_1__SEL_1 =
	     EN_core_request_put && core_request_put[0] ;
  assign MUX_rg_tlb_miss_write_1__SEL_1 =
	     EN_core_request_put &&
	     NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d403 ;
  assign MUX_v_vpn_tag_0_write_1__SEL_1 =
	     EN_response_frm_ptw_put && rg_replace == 2'd0 &&
	     !response_frm_ptw_put[6] ;
  assign MUX_v_vpn_tag_1_write_1__SEL_1 =
	     EN_response_frm_ptw_put && rg_replace == 2'd1 &&
	     !response_frm_ptw_put[6] ;
  assign MUX_v_vpn_tag_2_write_1__SEL_1 =
	     EN_response_frm_ptw_put && rg_replace == 2'd2 &&
	     !response_frm_ptw_put[6] ;
  assign MUX_v_vpn_tag_3_write_1__SEL_1 =
	     EN_response_frm_ptw_put && rg_replace == 2'd3 &&
	     !response_frm_ptw_put[6] ;
  assign MUX_ff_core_respone_enq_1__VAL_1 =
	     (ma_satp_from_csr_s[63:60] == 4'd0 || ma_curr_priv_c == 2'd3) ?
	       { core_request_put[32:1],
		 core_request_put[64:33] != 32'd0,
		 6'd1 } :
	       { x_address__h5475,
		 IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d140 ||
		 IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d177,
		 6'd12 } ;
  assign MUX_ff_core_respone_enq_1__VAL_2 =
	     { x_address__h5743, response_frm_ptw_put[6:0] } ;
  assign MUX_rg_replace_write_1__VAL_1 = rg_replace + 2'd1 ;
  assign MUX_v_vpn_tag_0_write_1__VAL_1 =
	     { response_frm_ptw_put[16:9],
	       tag_vpn__h5998,
	       ma_satp_from_csr_s[52:44],
	       mask__h5715,
	       response_frm_ptw_put[62:19] } ;

  // register rg_miss_queue
  assign rg_miss_queue_D_IN = core_request_put[64:1] ;
  assign rg_miss_queue_EN = MUX_rg_tlb_miss_write_1__SEL_1 ;

  // register rg_replace
  assign rg_replace_D_IN =
	     MUX_rg_replace_write_1__SEL_1 ?
	       MUX_rg_replace_write_1__VAL_1 :
	       2'd0 ;
  assign rg_replace_EN =
	     EN_response_frm_ptw_put && !response_frm_ptw_put[6] ||
	     rg_sfence ;

  // register rg_sfence
  assign rg_sfence_D_IN = MUX_rg_sfence_write_1__SEL_1 ;
  assign rg_sfence_EN =
	     EN_core_request_put && core_request_put[0] || rg_sfence ;

  // register rg_tlb_miss
  assign rg_tlb_miss_D_IN = MUX_rg_tlb_miss_write_1__SEL_1 ;
  assign rg_tlb_miss_EN =
	     EN_core_request_put &&
	     NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d403 ||
	     rg_sfence ||
	     EN_response_frm_ptw_put ;

  // register v_vpn_tag_0
  assign v_vpn_tag_0_D_IN =
	     MUX_v_vpn_tag_0_write_1__SEL_1 ?
	       MUX_v_vpn_tag_0_write_1__VAL_1 :
	       106'd0 ;
  assign v_vpn_tag_0_EN =
	     EN_response_frm_ptw_put && rg_replace == 2'd0 &&
	     !response_frm_ptw_put[6] ||
	     rg_sfence ;

  // register v_vpn_tag_1
  assign v_vpn_tag_1_D_IN =
	     MUX_v_vpn_tag_1_write_1__SEL_1 ?
	       MUX_v_vpn_tag_0_write_1__VAL_1 :
	       106'd0 ;
  assign v_vpn_tag_1_EN =
	     EN_response_frm_ptw_put && rg_replace == 2'd1 &&
	     !response_frm_ptw_put[6] ||
	     rg_sfence ;

  // register v_vpn_tag_2
  assign v_vpn_tag_2_D_IN =
	     MUX_v_vpn_tag_2_write_1__SEL_1 ?
	       MUX_v_vpn_tag_0_write_1__VAL_1 :
	       106'd0 ;
  assign v_vpn_tag_2_EN =
	     EN_response_frm_ptw_put && rg_replace == 2'd2 &&
	     !response_frm_ptw_put[6] ||
	     rg_sfence ;

  // register v_vpn_tag_3
  assign v_vpn_tag_3_D_IN =
	     MUX_v_vpn_tag_3_write_1__SEL_1 ?
	       MUX_v_vpn_tag_0_write_1__VAL_1 :
	       106'd0 ;
  assign v_vpn_tag_3_EN =
	     EN_response_frm_ptw_put && rg_replace == 2'd3 &&
	     !response_frm_ptw_put[6] ||
	     rg_sfence ;

  // submodule ff_core_respone
  assign ff_core_respone_D_IN =
	     MUX_ff_core_respone_enq_1__SEL_1 ?
	       MUX_ff_core_respone_enq_1__VAL_1 :
	       MUX_ff_core_respone_enq_1__VAL_2 ;
  assign ff_core_respone_ENQ =
	     EN_core_request_put &&
	     NOT_core_request_put_BIT_0_1_AND_wr_satp_wget__ETC___d104 ||
	     EN_response_frm_ptw_put ;
  assign ff_core_respone_DEQ = EN_core_response_get ;
  assign ff_core_respone_CLR = 1'b0 ;

  // submodule ff_request_to_ptw
  assign ff_request_to_ptw_D_IN = { core_request_put[64:1], 2'd3 } ;
  assign ff_request_to_ptw_ENQ = MUX_rg_tlb_miss_write_1__SEL_1 ;
  assign ff_request_to_ptw_DEQ = EN_request_to_ptw_get ;
  assign ff_request_to_ptw_CLR = 1'b0 ;

  // remaining internal signals
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d100 =
	     (!v_vpn_tag_0[98] ||
	      !_511_CONCAT_v_vpn_tag_0_6_BITS_61_TO_44_9_0_AND_ETC___d34 ||
	      !v_vpn_tag_0_6_BITS_70_TO_62_7_EQ_wr_satp_wget__ETC___d39 &&
	      !v_vpn_tag_0[103]) ?
	       v_vpn_tag_1[98] &&
	       _511_CONCAT_v_vpn_tag_1_5_BITS_61_TO_44_8_9_AND_ETC___d52 &&
	       (v_vpn_tag_1_5_BITS_70_TO_62_5_EQ_wr_satp_wget__ETC___d56 ||
		v_vpn_tag_1[103]) :
	       v_vpn_tag_0[98] ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d101 =
	     NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d62 ?
	       v_vpn_tag_2[98] &&
	       _511_CONCAT_v_vpn_tag_2_3_BITS_61_TO_44_6_7_AND_ETC___d70 &&
	       (v_vpn_tag_2_3_BITS_70_TO_62_3_EQ_wr_satp_wget__ETC___d74 ||
		v_vpn_tag_2[103]) :
	       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d100 ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d102 =
	     NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d80 ?
	       v_vpn_tag_3[98] &&
	       _511_CONCAT_v_vpn_tag_3_1_BITS_61_TO_44_3_4_AND_ETC___d87 &&
	       (v_vpn_tag_3_1_BITS_70_TO_62_9_EQ_wr_satp_wget__ETC___d90 ||
		v_vpn_tag_3[103]) :
	       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d101 ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d114 =
	     (!v_vpn_tag_0[98] ||
	      !_511_CONCAT_v_vpn_tag_0_6_BITS_61_TO_44_9_0_AND_ETC___d34 ||
	      !v_vpn_tag_0_6_BITS_70_TO_62_7_EQ_wr_satp_wget__ETC___d39 &&
	      !v_vpn_tag_0[103]) ?
	       v_vpn_tag_1[43:0] :
	       v_vpn_tag_0[43:0] ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d118 =
	     (!v_vpn_tag_0[98] ||
	      !_511_CONCAT_v_vpn_tag_0_6_BITS_61_TO_44_9_0_AND_ETC___d34 ||
	      !v_vpn_tag_0_6_BITS_70_TO_62_7_EQ_wr_satp_wget__ETC___d39 &&
	      !v_vpn_tag_0[103]) ?
	       v_vpn_tag_1[61:44] :
	       v_vpn_tag_0[61:44] ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d138 =
	     (!v_vpn_tag_0[98] ||
	      !_511_CONCAT_v_vpn_tag_0_6_BITS_61_TO_44_9_0_AND_ETC___d34 ||
	      !v_vpn_tag_0_6_BITS_70_TO_62_7_EQ_wr_satp_wget__ETC___d39 &&
	      !v_vpn_tag_0[103]) ?
	       !v_vpn_tag_1[101] :
	       !v_vpn_tag_0[101] ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d140 =
	     NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d80 ?
	       !v_vpn_tag_3[101] :
	       (NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d62 ?
		  !v_vpn_tag_2[101] :
		  IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d138) ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d149 =
	     (!v_vpn_tag_0[98] ||
	      !_511_CONCAT_v_vpn_tag_0_6_BITS_61_TO_44_9_0_AND_ETC___d34 ||
	      !v_vpn_tag_0_6_BITS_70_TO_62_7_EQ_wr_satp_wget__ETC___d39 &&
	      !v_vpn_tag_0[103]) ?
	       !v_vpn_tag_1[104] :
	       !v_vpn_tag_0[104] ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d151 =
	     NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d80 ?
	       !v_vpn_tag_3[104] :
	       (NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d62 ?
		  !v_vpn_tag_2[104] :
		  IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d149) ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d160 =
	     (!v_vpn_tag_0[98] ||
	      !_511_CONCAT_v_vpn_tag_0_6_BITS_61_TO_44_9_0_AND_ETC___d34 ||
	      !v_vpn_tag_0_6_BITS_70_TO_62_7_EQ_wr_satp_wget__ETC___d39 &&
	      !v_vpn_tag_0[103]) ?
	       !v_vpn_tag_1[102] :
	       !v_vpn_tag_0[102] ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d162 =
	     NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d80 ?
	       !v_vpn_tag_3[102] :
	       (NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d62 ?
		  !v_vpn_tag_2[102] :
		  IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d160) ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d165 =
	     (!v_vpn_tag_0[98] ||
	      !_511_CONCAT_v_vpn_tag_0_6_BITS_61_TO_44_9_0_AND_ETC___d34 ||
	      !v_vpn_tag_0_6_BITS_70_TO_62_7_EQ_wr_satp_wget__ETC___d39 &&
	      !v_vpn_tag_0[103]) ?
	       v_vpn_tag_1[102] :
	       v_vpn_tag_0[102] ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d167 =
	     NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d80 ?
	       v_vpn_tag_3[102] :
	       (NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d62 ?
		  v_vpn_tag_2[102] :
		  IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d165) ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d177 =
	     IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d151 ||
	     IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d162 &&
	     ma_curr_priv_c == 2'd0 ||
	     IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d167 &&
	     ma_curr_priv_c == 2'd1 ||
	     core_request_put[64:40] != {25{core_request_put[39]}} ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d207 =
	     NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d80 ?
	       !v_vpn_tag_3[98] :
	       (NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d62 ?
		  !v_vpn_tag_2[98] :
		  NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d205) ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d217 =
	     NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d80 ?
	       v_vpn_tag_3[98] :
	       (NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d62 ?
		  v_vpn_tag_2[98] :
		  v_vpn_tag_0_6_BIT_98_7_AND_511_CONCAT_v_vpn_ta_ETC___d215) ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d230 =
	     (!v_vpn_tag_0[98] ||
	      !_511_CONCAT_v_vpn_tag_0_6_BITS_61_TO_44_9_0_AND_ETC___d34 ||
	      !v_vpn_tag_0_6_BITS_70_TO_62_7_EQ_wr_satp_wget__ETC___d39 &&
	      !v_vpn_tag_0[103]) ?
	       !v_vpn_tag_1[99] :
	       !v_vpn_tag_0[99] ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d232 =
	     NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d80 ?
	       !v_vpn_tag_3[99] :
	       (NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d62 ?
		  !v_vpn_tag_2[99] :
		  IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d230) ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d237 =
	     (!v_vpn_tag_0[98] ||
	      !_511_CONCAT_v_vpn_tag_0_6_BITS_61_TO_44_9_0_AND_ETC___d34 ||
	      !v_vpn_tag_0_6_BITS_70_TO_62_7_EQ_wr_satp_wget__ETC___d39 &&
	      !v_vpn_tag_0[103]) ?
	       v_vpn_tag_1[99] :
	       v_vpn_tag_0[99] ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d239 =
	     NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d80 ?
	       v_vpn_tag_3[99] :
	       (NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d62 ?
		  v_vpn_tag_2[99] :
		  IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d237) ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d252 =
	     (!v_vpn_tag_0[98] ||
	      !_511_CONCAT_v_vpn_tag_0_6_BITS_61_TO_44_9_0_AND_ETC___d34 ||
	      !v_vpn_tag_0_6_BITS_70_TO_62_7_EQ_wr_satp_wget__ETC___d39 &&
	      !v_vpn_tag_0[103]) ?
	       !v_vpn_tag_1[100] :
	       !v_vpn_tag_0[100] ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d254 =
	     NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d80 ?
	       !v_vpn_tag_3[100] :
	       (NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d62 ?
		  !v_vpn_tag_2[100] :
		  IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d252) ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d259 =
	     (!v_vpn_tag_0[98] ||
	      !_511_CONCAT_v_vpn_tag_0_6_BITS_61_TO_44_9_0_AND_ETC___d34 ||
	      !v_vpn_tag_0_6_BITS_70_TO_62_7_EQ_wr_satp_wget__ETC___d39 &&
	      !v_vpn_tag_0[103]) ?
	       v_vpn_tag_1[100] :
	       v_vpn_tag_0[100] ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d261 =
	     NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d80 ?
	       v_vpn_tag_3[100] :
	       (NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d62 ?
		  v_vpn_tag_2[100] :
		  IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d259) ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d270 =
	     (!v_vpn_tag_0[98] ||
	      !_511_CONCAT_v_vpn_tag_0_6_BITS_61_TO_44_9_0_AND_ETC___d34 ||
	      !v_vpn_tag_0_6_BITS_70_TO_62_7_EQ_wr_satp_wget__ETC___d39 &&
	      !v_vpn_tag_0[103]) ?
	       v_vpn_tag_1[101] :
	       v_vpn_tag_0[101] ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d272 =
	     NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d80 ?
	       v_vpn_tag_3[101] :
	       (NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d62 ?
		  v_vpn_tag_2[101] :
		  IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d270) ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d286 =
	     (!v_vpn_tag_0[98] ||
	      !_511_CONCAT_v_vpn_tag_0_6_BITS_61_TO_44_9_0_AND_ETC___d34 ||
	      !v_vpn_tag_0_6_BITS_70_TO_62_7_EQ_wr_satp_wget__ETC___d39 &&
	      !v_vpn_tag_0[103]) ?
	       !v_vpn_tag_1[103] :
	       !v_vpn_tag_0[103] ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d288 =
	     NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d80 ?
	       !v_vpn_tag_3[103] :
	       (NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d62 ?
		  !v_vpn_tag_2[103] :
		  IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d286) ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d293 =
	     (!v_vpn_tag_0[98] ||
	      !_511_CONCAT_v_vpn_tag_0_6_BITS_61_TO_44_9_0_AND_ETC___d34 ||
	      !v_vpn_tag_0_6_BITS_70_TO_62_7_EQ_wr_satp_wget__ETC___d39 &&
	      !v_vpn_tag_0[103]) ?
	       v_vpn_tag_1[103] :
	       v_vpn_tag_0[103] ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d295 =
	     NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d80 ?
	       v_vpn_tag_3[103] :
	       (NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d62 ?
		  v_vpn_tag_2[103] :
		  IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d293) ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d304 =
	     (!v_vpn_tag_0[98] ||
	      !_511_CONCAT_v_vpn_tag_0_6_BITS_61_TO_44_9_0_AND_ETC___d34 ||
	      !v_vpn_tag_0_6_BITS_70_TO_62_7_EQ_wr_satp_wget__ETC___d39 &&
	      !v_vpn_tag_0[103]) ?
	       v_vpn_tag_1[104] :
	       v_vpn_tag_0[104] ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d306 =
	     NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d80 ?
	       v_vpn_tag_3[104] :
	       (NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d62 ?
		  v_vpn_tag_2[104] :
		  IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d304) ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d319 =
	     (!v_vpn_tag_0[98] ||
	      !_511_CONCAT_v_vpn_tag_0_6_BITS_61_TO_44_9_0_AND_ETC___d34 ||
	      !v_vpn_tag_0_6_BITS_70_TO_62_7_EQ_wr_satp_wget__ETC___d39 &&
	      !v_vpn_tag_0[103]) ?
	       !v_vpn_tag_1[105] :
	       !v_vpn_tag_0[105] ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d321 =
	     NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d80 ?
	       !v_vpn_tag_3[105] :
	       (NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d62 ?
		  !v_vpn_tag_2[105] :
		  IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d319) ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d326 =
	     (!v_vpn_tag_0[98] ||
	      !_511_CONCAT_v_vpn_tag_0_6_BITS_61_TO_44_9_0_AND_ETC___d34 ||
	      !v_vpn_tag_0_6_BITS_70_TO_62_7_EQ_wr_satp_wget__ETC___d39 &&
	      !v_vpn_tag_0[103]) ?
	       v_vpn_tag_1[105] :
	       v_vpn_tag_0[105] ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d328 =
	     NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d80 ?
	       v_vpn_tag_3[105] :
	       (NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d62 ?
		  v_vpn_tag_2[105] :
		  IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d326) ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d333 =
	     (!v_vpn_tag_0[98] ||
	      !_511_CONCAT_v_vpn_tag_0_6_BITS_61_TO_44_9_0_AND_ETC___d34 ||
	      !v_vpn_tag_0_6_BITS_70_TO_62_7_EQ_wr_satp_wget__ETC___d39 &&
	      !v_vpn_tag_0[103]) ?
	       v_vpn_tag_1[97:71] :
	       v_vpn_tag_0[97:71] ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d335 =
	     NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d80 ?
	       v_vpn_tag_3[97:71] :
	       (NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d62 ?
		  v_vpn_tag_2[97:71] :
		  IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d333) ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d336 =
	     (!v_vpn_tag_0[98] ||
	      !_511_CONCAT_v_vpn_tag_0_6_BITS_61_TO_44_9_0_AND_ETC___d34 ||
	      !v_vpn_tag_0_6_BITS_70_TO_62_7_EQ_wr_satp_wget__ETC___d39 &&
	      !v_vpn_tag_0[103]) ?
	       v_vpn_tag_1[70:62] :
	       v_vpn_tag_0[70:62] ;
  assign IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d338 =
	     NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d80 ?
	       v_vpn_tag_3[70:62] :
	       (NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d62 ?
		  v_vpn_tag_2[70:62] :
		  IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d336) ;
  assign NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d194 =
	     !core_request_put[0] && ma_satp_from_csr_s[63:60] != 4'd0 &&
	     ma_curr_priv_c != 2'd3 &&
	     IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d102 ;
  assign NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d403 =
	     !core_request_put[0] && ma_satp_from_csr_s[63:60] != 4'd0 &&
	     ma_curr_priv_c != 2'd3 &&
	     NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d401 ;
  assign NOT_core_request_put_BIT_0_1_AND_wr_satp_wget__ETC___d104 =
	     !core_request_put[0] &&
	     (ma_satp_from_csr_s[63:60] == 4'd0 || ma_curr_priv_c == 2'd3 ||
	      IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d102) ;
  assign NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d205 =
	     (!v_vpn_tag_0[98] ||
	      !_511_CONCAT_v_vpn_tag_0_6_BITS_61_TO_44_9_0_AND_ETC___d34 ||
	      !v_vpn_tag_0_6_BITS_70_TO_62_7_EQ_wr_satp_wget__ETC___d39 &&
	      !v_vpn_tag_0[103]) &&
	     !v_vpn_tag_1[98] ;
  assign NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d401 =
	     NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d80 &&
	     (!v_vpn_tag_3[98] ||
	      !_511_CONCAT_v_vpn_tag_3_1_BITS_61_TO_44_3_4_AND_ETC___d87 ||
	      !v_vpn_tag_3_1_BITS_70_TO_62_9_EQ_wr_satp_wget__ETC___d90 &&
	      !v_vpn_tag_3[103]) ;
  assign NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d62 =
	     (!v_vpn_tag_0[98] ||
	      !_511_CONCAT_v_vpn_tag_0_6_BITS_61_TO_44_9_0_AND_ETC___d34 ||
	      !v_vpn_tag_0_6_BITS_70_TO_62_7_EQ_wr_satp_wget__ETC___d39 &&
	      !v_vpn_tag_0[103]) &&
	     (!v_vpn_tag_1[98] ||
	      !_511_CONCAT_v_vpn_tag_1_5_BITS_61_TO_44_8_9_AND_ETC___d52 ||
	      !v_vpn_tag_1_5_BITS_70_TO_62_5_EQ_wr_satp_wget__ETC___d56 &&
	      !v_vpn_tag_1[103]) ;
  assign NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d80 =
	     NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d62 &&
	     (!v_vpn_tag_2[98] ||
	      !_511_CONCAT_v_vpn_tag_2_3_BITS_61_TO_44_6_7_AND_ETC___d70 ||
	      !v_vpn_tag_2_3_BITS_70_TO_62_3_EQ_wr_satp_wget__ETC___d74 &&
	      !v_vpn_tag_2[103]) ;
  assign _511_CONCAT_v_vpn_tag_0_6_BITS_61_TO_44_9_0_AND_ETC___d34 =
	     ({ 9'd511, v_vpn_tag_0[61:44] } & core_request_put[39:13]) ==
	     v_vpn_tag_0[97:71] ;
  assign _511_CONCAT_v_vpn_tag_1_5_BITS_61_TO_44_8_9_AND_ETC___d52 =
	     ({ 9'd511, v_vpn_tag_1[61:44] } & core_request_put[39:13]) ==
	     v_vpn_tag_1[97:71] ;
  assign _511_CONCAT_v_vpn_tag_2_3_BITS_61_TO_44_6_7_AND_ETC___d70 =
	     ({ 9'd511, v_vpn_tag_2[61:44] } & core_request_put[39:13]) ==
	     v_vpn_tag_2[97:71] ;
  assign _511_CONCAT_v_vpn_tag_3_1_BITS_61_TO_44_3_4_AND_ETC___d87 =
	     ({ 9'd511, v_vpn_tag_3[61:44] } & core_request_put[39:13]) ==
	     v_vpn_tag_3[97:71] ;
  assign _9_MUL_0_CONCAT_response_frm_ptw_put_BITS_8_TO__ETC___d428 =
	     5'd9 * { 3'd0, response_frm_ptw_put[8:7] } ;
  assign lower_pa__h4360 = x__h4968 | y__h4969 ;
  assign lower_pa__h5718 = x__h5782 | y__h5783 ;
  assign mask__h4357 =
	     NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d80 ?
	       v_vpn_tag_3[61:44] :
	       (NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d62 ?
		  v_vpn_tag_2[61:44] :
		  IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d118) ;
  assign mask__h5715 =
	     18'd262143 <<
	     _9_MUL_0_CONCAT_response_frm_ptw_put_BITS_8_TO__ETC___d428[4:0] ;
  assign physicaladdress__h4362 = { 8'd0, x__h5289 } ;
  assign tag_vpn__h5998 = { 9'd511, mask__h5715 } & rg_miss_queue[38:12] ;
  assign v_vpn_tag_0_6_BITS_70_TO_62_7_EQ_wr_satp_wget__ETC___d39 =
	     v_vpn_tag_0[70:62] == ma_satp_from_csr_s[52:44] ;
  assign v_vpn_tag_0_6_BIT_98_7_AND_511_CONCAT_v_vpn_ta_ETC___d215 =
	     v_vpn_tag_0[98] &&
	     _511_CONCAT_v_vpn_tag_0_6_BITS_61_TO_44_9_0_AND_ETC___d34 &&
	     (v_vpn_tag_0_6_BITS_70_TO_62_7_EQ_wr_satp_wget__ETC___d39 ||
	      v_vpn_tag_0[103]) ||
	     v_vpn_tag_1[98] ;
  assign v_vpn_tag_1_5_BITS_70_TO_62_5_EQ_wr_satp_wget__ETC___d56 =
	     v_vpn_tag_1[70:62] == ma_satp_from_csr_s[52:44] ;
  assign v_vpn_tag_2_3_BITS_70_TO_62_3_EQ_wr_satp_wget__ETC___d74 =
	     v_vpn_tag_2[70:62] == ma_satp_from_csr_s[52:44] ;
  assign v_vpn_tag_3_1_BITS_70_TO_62_9_EQ_wr_satp_wget__ETC___d90 =
	     v_vpn_tag_3[70:62] == ma_satp_from_csr_s[52:44] ;
  assign x__h4642 =
	     NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d80 ?
	       v_vpn_tag_3[43:0] :
	       (NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d62 ?
		  v_vpn_tag_2[43:0] :
		  IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d114) ;
  assign x__h4968 = mask__h4357 & x__h4642[17:0] ;
  assign x__h4970 = ~mask__h4357 ;
  assign x__h5289 =
	     { x__h4642[43:18], lower_pa__h4360, core_request_put[12:1] } ;
  assign x__h5782 = mask__h5715 & response_frm_ptw_put[36:19] ;
  assign x__h5814 = ~mask__h5715 ;
  assign x_address__h5475 =
	     { x__h4642[19:18], lower_pa__h4360, core_request_put[12:1] } ;
  assign x_address__h5743 =
	     { response_frm_ptw_put[38:37],
	       lower_pa__h5718,
	       rg_miss_queue[11:0] } ;
  assign y__h4969 = x__h4970 & core_request_put[30:13] ;
  assign y__h5783 = x__h5814 & rg_miss_queue[29:12] ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        rg_miss_queue <= `BSV_ASSIGNMENT_DELAY 64'd0;
	rg_replace <= `BSV_ASSIGNMENT_DELAY 2'd0;
	rg_sfence <= `BSV_ASSIGNMENT_DELAY 1'd0;
	rg_tlb_miss <= `BSV_ASSIGNMENT_DELAY 1'd0;
	v_vpn_tag_0 <= `BSV_ASSIGNMENT_DELAY 106'd0;
	v_vpn_tag_1 <= `BSV_ASSIGNMENT_DELAY 106'd0;
	v_vpn_tag_2 <= `BSV_ASSIGNMENT_DELAY 106'd0;
	v_vpn_tag_3 <= `BSV_ASSIGNMENT_DELAY 106'd0;
      end
    else
      begin
        if (rg_miss_queue_EN)
	  rg_miss_queue <= `BSV_ASSIGNMENT_DELAY rg_miss_queue_D_IN;
	if (rg_replace_EN)
	  rg_replace <= `BSV_ASSIGNMENT_DELAY rg_replace_D_IN;
	if (rg_sfence_EN) rg_sfence <= `BSV_ASSIGNMENT_DELAY rg_sfence_D_IN;
	if (rg_tlb_miss_EN)
	  rg_tlb_miss <= `BSV_ASSIGNMENT_DELAY rg_tlb_miss_D_IN;
	if (v_vpn_tag_0_EN)
	  v_vpn_tag_0 <= `BSV_ASSIGNMENT_DELAY v_vpn_tag_0_D_IN;
	if (v_vpn_tag_1_EN)
	  v_vpn_tag_1 <= `BSV_ASSIGNMENT_DELAY v_vpn_tag_1_D_IN;
	if (v_vpn_tag_2_EN)
	  v_vpn_tag_2 <= `BSV_ASSIGNMENT_DELAY v_vpn_tag_2_D_IN;
	if (v_vpn_tag_3_EN)
	  v_vpn_tag_3 <= `BSV_ASSIGNMENT_DELAY v_vpn_tag_3_D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    rg_miss_queue = 64'hAAAAAAAAAAAAAAAA;
    rg_replace = 2'h2;
    rg_sfence = 1'h0;
    rg_tlb_miss = 1'h0;
    v_vpn_tag_0 = 106'h2AAAAAAAAAAAAAAAAAAAAAAAAAA;
    v_vpn_tag_1 = 106'h2AAAAAAAAAAAAAAAAAAAAAAAAAA;
    v_vpn_tag_2 = 106'h2AAAAAAAAAAAAAAAAAAAAAAAAAA;
    v_vpn_tag_3 = 106'h2AAAAAAAAAAAAAAAAAAAAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put && !response_frm_ptw_put[6])
	begin
	  TASK_testplusargs___d444 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put && !response_frm_ptw_put[6])
	begin
	  TASK_testplusargs___d445 = $test$plusargs("mitlb");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put && !response_frm_ptw_put[6])
	begin
	  TASK_testplusargs___d446 = $test$plusargs("l0");
	  #0;
	end
    TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d453 =
	(TASK_testplusargs___d444 ||
	 TASK_testplusargs___d445 && TASK_testplusargs___d446) &&
	response_frm_ptw_put[9];
    TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d456 =
	(TASK_testplusargs___d444 ||
	 TASK_testplusargs___d445 && TASK_testplusargs___d446) &&
	!response_frm_ptw_put[9];
    TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d459 =
	(TASK_testplusargs___d444 ||
	 TASK_testplusargs___d445 && TASK_testplusargs___d446) &&
	response_frm_ptw_put[10];
    TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d462 =
	(TASK_testplusargs___d444 ||
	 TASK_testplusargs___d445 && TASK_testplusargs___d446) &&
	!response_frm_ptw_put[10];
    TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d465 =
	(TASK_testplusargs___d444 ||
	 TASK_testplusargs___d445 && TASK_testplusargs___d446) &&
	response_frm_ptw_put[11];
    TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d468 =
	(TASK_testplusargs___d444 ||
	 TASK_testplusargs___d445 && TASK_testplusargs___d446) &&
	!response_frm_ptw_put[11];
    TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d471 =
	(TASK_testplusargs___d444 ||
	 TASK_testplusargs___d445 && TASK_testplusargs___d446) &&
	response_frm_ptw_put[12];
    TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d474 =
	(TASK_testplusargs___d444 ||
	 TASK_testplusargs___d445 && TASK_testplusargs___d446) &&
	!response_frm_ptw_put[12];
    TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d477 =
	(TASK_testplusargs___d444 ||
	 TASK_testplusargs___d445 && TASK_testplusargs___d446) &&
	response_frm_ptw_put[13];
    TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d483 =
	(TASK_testplusargs___d444 ||
	 TASK_testplusargs___d445 && TASK_testplusargs___d446) &&
	response_frm_ptw_put[14];
    TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d480 =
	(TASK_testplusargs___d444 ||
	 TASK_testplusargs___d445 && TASK_testplusargs___d446) &&
	!response_frm_ptw_put[13];
    TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d486 =
	(TASK_testplusargs___d444 ||
	 TASK_testplusargs___d445 && TASK_testplusargs___d446) &&
	!response_frm_ptw_put[14];
    TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d489 =
	(TASK_testplusargs___d444 ||
	 TASK_testplusargs___d445 && TASK_testplusargs___d446) &&
	response_frm_ptw_put[15];
    TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d492 =
	(TASK_testplusargs___d444 ||
	 TASK_testplusargs___d445 && TASK_testplusargs___d446) &&
	!response_frm_ptw_put[15];
    TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d495 =
	(TASK_testplusargs___d444 ||
	 TASK_testplusargs___d445 && TASK_testplusargs___d446) &&
	response_frm_ptw_put[16];
    TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d498 =
	(TASK_testplusargs___d444 ||
	 TASK_testplusargs___d445 && TASK_testplusargs___d446) &&
	!response_frm_ptw_put[16];
    NOT_response_frm_ptw_put_BIT_6_42_43_AND_TASK__ETC___d449 =
	!response_frm_ptw_put[6] &&
	(TASK_testplusargs___d444 ||
	 TASK_testplusargs___d445 && TASK_testplusargs___d446);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put && !response_frm_ptw_put[6])
	begin
	  v__h5943 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put &&
	  NOT_response_frm_ptw_put_BIT_6_42_43_AND_TASK__ETC___d449)
	$write("[%10d", v__h5943, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put &&
	  NOT_response_frm_ptw_put_BIT_6_42_43_AND_TASK__ETC___d449)
	$write("ITLB: Allocating index:%d for Tag:", rg_replace);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put &&
	  NOT_response_frm_ptw_put_BIT_6_42_43_AND_TASK__ETC___d449)
	$write("VPNTag { ", "permissions: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put &&
	  NOT_response_frm_ptw_put_BIT_6_42_43_AND_TASK__ETC___d449)
	$write("TLB_permissions { ", "v: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put && !response_frm_ptw_put[6] &&
	  TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d453)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put && !response_frm_ptw_put[6] &&
	  TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d456)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put &&
	  NOT_response_frm_ptw_put_BIT_6_42_43_AND_TASK__ETC___d449)
	$write(", ", "r: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put && !response_frm_ptw_put[6] &&
	  TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d459)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put && !response_frm_ptw_put[6] &&
	  TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d462)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put &&
	  NOT_response_frm_ptw_put_BIT_6_42_43_AND_TASK__ETC___d449)
	$write(", ", "w: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put && !response_frm_ptw_put[6] &&
	  TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d465)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put && !response_frm_ptw_put[6] &&
	  TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d468)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put &&
	  NOT_response_frm_ptw_put_BIT_6_42_43_AND_TASK__ETC___d449)
	$write(", ", "x: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put && !response_frm_ptw_put[6] &&
	  TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d471)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put && !response_frm_ptw_put[6] &&
	  TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d474)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put &&
	  NOT_response_frm_ptw_put_BIT_6_42_43_AND_TASK__ETC___d449)
	$write(", ", "u: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put && !response_frm_ptw_put[6] &&
	  TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d477)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put && !response_frm_ptw_put[6] &&
	  TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d480)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put &&
	  NOT_response_frm_ptw_put_BIT_6_42_43_AND_TASK__ETC___d449)
	$write(", ", "g: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put && !response_frm_ptw_put[6] &&
	  TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d483)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put && !response_frm_ptw_put[6] &&
	  TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d486)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put &&
	  NOT_response_frm_ptw_put_BIT_6_42_43_AND_TASK__ETC___d449)
	$write(", ", "a: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put && !response_frm_ptw_put[6] &&
	  TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d489)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put && !response_frm_ptw_put[6] &&
	  TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d492)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put &&
	  NOT_response_frm_ptw_put_BIT_6_42_43_AND_TASK__ETC___d449)
	$write(", ", "d: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put && !response_frm_ptw_put[6] &&
	  TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d495)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put && !response_frm_ptw_put[6] &&
	  TASK_testplusargs_44_OR_TASK_testplusargs_45_A_ETC___d498)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put &&
	  NOT_response_frm_ptw_put_BIT_6_42_43_AND_TASK__ETC___d449)
	$write(" }");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put &&
	  NOT_response_frm_ptw_put_BIT_6_42_43_AND_TASK__ETC___d449)
	$write(", ", "vpn: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put &&
	  NOT_response_frm_ptw_put_BIT_6_42_43_AND_TASK__ETC___d449)
	$write("'h%h", tag_vpn__h5998);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put &&
	  NOT_response_frm_ptw_put_BIT_6_42_43_AND_TASK__ETC___d449)
	$write(", ", "asid: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put &&
	  NOT_response_frm_ptw_put_BIT_6_42_43_AND_TASK__ETC___d449)
	$write("'h%h", ma_satp_from_csr_s[52:44]);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put &&
	  NOT_response_frm_ptw_put_BIT_6_42_43_AND_TASK__ETC___d449)
	$write(", ", "pagemask: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put &&
	  NOT_response_frm_ptw_put_BIT_6_42_43_AND_TASK__ETC___d449)
	$write("'h%h", mask__h5715);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put &&
	  NOT_response_frm_ptw_put_BIT_6_42_43_AND_TASK__ETC___d449)
	$write(", ", "ppn: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put &&
	  NOT_response_frm_ptw_put_BIT_6_42_43_AND_TASK__ETC___d449)
	$write("'h%h", response_frm_ptw_put[62:19], " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_response_frm_ptw_put &&
	  NOT_response_frm_ptw_put_BIT_6_42_43_AND_TASK__ETC___d449)
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put)
	begin
	  TASK_testplusargs___d2 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put)
	begin
	  TASK_testplusargs___d3 = $test$plusargs("mtlb");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put)
	begin
	  TASK_testplusargs___d4 = $test$plusargs("l0");
	  #0;
	end
    TASK_testplusargs_OR_TASK_testplusargs_AND_TAS_ETC___d10 =
	(TASK_testplusargs___d2 ||
	 TASK_testplusargs___d3 && TASK_testplusargs___d4) &&
	core_request_put[0];
    TASK_testplusargs_OR_TASK_testplusargs_AND_TAS_ETC___d12 =
	(TASK_testplusargs___d2 ||
	 TASK_testplusargs___d3 && TASK_testplusargs___d4) &&
	!core_request_put[0];
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put)
	begin
	  v__h2324 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  (TASK_testplusargs___d2 ||
	   TASK_testplusargs___d3 && TASK_testplusargs___d4))
	$write("[%10d", v__h2324, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  (TASK_testplusargs___d2 ||
	   TASK_testplusargs___d3 && TASK_testplusargs___d4))
	$write("core id:%2d ", hartid, "ITLB: received req: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  (TASK_testplusargs___d2 ||
	   TASK_testplusargs___d3 && TASK_testplusargs___d4))
	$write("ITLB_core_request { ", "address: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  (TASK_testplusargs___d2 ||
	   TASK_testplusargs___d3 && TASK_testplusargs___d4))
	$write("'h%h", core_request_put[64:1]);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  (TASK_testplusargs___d2 ||
	   TASK_testplusargs___d3 && TASK_testplusargs___d4))
	$write(", ", "sfence: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  TASK_testplusargs_OR_TASK_testplusargs_AND_TAS_ETC___d10)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  TASK_testplusargs_OR_TASK_testplusargs_AND_TAS_ETC___d12)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  (TASK_testplusargs___d2 ||
	   TASK_testplusargs___d3 && TASK_testplusargs___d4))
	$write(" }");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  (TASK_testplusargs___d2 ||
	   TASK_testplusargs___d3 && TASK_testplusargs___d4))
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put && core_request_put[0])
	begin
	  TASK_testplusargs___d13 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put && core_request_put[0])
	begin
	  TASK_testplusargs___d14 = $test$plusargs("mitlb");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put && core_request_put[0])
	begin
	  TASK_testplusargs___d15 = $test$plusargs("l0");
	  #0;
	end
    core_request_put_BIT_0_AND_TASK_testplusargs_3_ETC___d18 =
	core_request_put[0] &&
	(TASK_testplusargs___d13 ||
	 TASK_testplusargs___d14 && TASK_testplusargs___d15);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put && core_request_put[0])
	begin
	  v__h3114 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  core_request_put_BIT_0_AND_TASK_testplusargs_3_ETC___d18)
	$write("[%10d", v__h3114, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  core_request_put_BIT_0_AND_TASK_testplusargs_3_ETC___d18)
	$write("ITLB: SFence received");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  core_request_put_BIT_0_AND_TASK_testplusargs_3_ETC___d18)
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put && !core_request_put[0] &&
	  (ma_satp_from_csr_s[63:60] == 4'd0 || ma_curr_priv_c == 2'd3))
	begin
	  TASK_testplusargs___d182 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put && !core_request_put[0] &&
	  (ma_satp_from_csr_s[63:60] == 4'd0 || ma_curr_priv_c == 2'd3))
	begin
	  TASK_testplusargs___d183 = $test$plusargs("mitlb");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put && !core_request_put[0] &&
	  (ma_satp_from_csr_s[63:60] == 4'd0 || ma_curr_priv_c == 2'd3))
	begin
	  TASK_testplusargs___d184 = $test$plusargs("l0");
	  #0;
	end
    wr_satp_wget__0_BITS_63_TO_60_1_EQ_0_2_OR_wr_p_ETC___d187 =
	(ma_satp_from_csr_s[63:60] == 4'd0 || ma_curr_priv_c == 2'd3) &&
	(TASK_testplusargs___d182 ||
	 TASK_testplusargs___d183 && TASK_testplusargs___d184);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put && !core_request_put[0] &&
	  (ma_satp_from_csr_s[63:60] == 4'd0 || ma_curr_priv_c == 2'd3))
	begin
	  v__h4322 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put && !core_request_put[0] &&
	  wr_satp_wget__0_BITS_63_TO_60_1_EQ_0_2_OR_wr_p_ETC___d187)
	$write("[%10d", v__h4322, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put && !core_request_put[0] &&
	  wr_satp_wget__0_BITS_63_TO_60_1_EQ_0_2_OR_wr_p_ETC___d187)
	$write("ITLB : Transparent Translation. PhyAddr: %h",
	       core_request_put[32:1]);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put && !core_request_put[0] &&
	  wr_satp_wget__0_BITS_63_TO_60_1_EQ_0_2_OR_wr_p_ETC___d187)
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d194)
	begin
	  TASK_testplusargs___d195 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d194)
	begin
	  TASK_testplusargs___d196 = $test$plusargs("mitlb");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d194)
	begin
	  TASK_testplusargs___d197 = $test$plusargs("l0");
	  #0;
	end
    IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d200 =
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d102 &&
	(TASK_testplusargs___d195 ||
	 TASK_testplusargs___d196 && TASK_testplusargs___d197);
    TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d208 =
	(TASK_testplusargs___d195 ||
	 TASK_testplusargs___d196 && TASK_testplusargs___d197) &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d207;
    TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d218 =
	(TASK_testplusargs___d195 ||
	 TASK_testplusargs___d196 && TASK_testplusargs___d197) &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d217;
    TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d233 =
	(TASK_testplusargs___d195 ||
	 TASK_testplusargs___d196 && TASK_testplusargs___d197) &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d232;
    TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d240 =
	(TASK_testplusargs___d195 ||
	 TASK_testplusargs___d196 && TASK_testplusargs___d197) &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d239;
    TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d255 =
	(TASK_testplusargs___d195 ||
	 TASK_testplusargs___d196 && TASK_testplusargs___d197) &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d254;
    TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d262 =
	(TASK_testplusargs___d195 ||
	 TASK_testplusargs___d196 && TASK_testplusargs___d197) &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d261;
    TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d266 =
	(TASK_testplusargs___d195 ||
	 TASK_testplusargs___d196 && TASK_testplusargs___d197) &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d140;
    TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d273 =
	(TASK_testplusargs___d195 ||
	 TASK_testplusargs___d196 && TASK_testplusargs___d197) &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d272;
    TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d277 =
	(TASK_testplusargs___d195 ||
	 TASK_testplusargs___d196 && TASK_testplusargs___d197) &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d162;
    TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d281 =
	(TASK_testplusargs___d195 ||
	 TASK_testplusargs___d196 && TASK_testplusargs___d197) &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d167;
    TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d289 =
	(TASK_testplusargs___d195 ||
	 TASK_testplusargs___d196 && TASK_testplusargs___d197) &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d288;
    TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d300 =
	(TASK_testplusargs___d195 ||
	 TASK_testplusargs___d196 && TASK_testplusargs___d197) &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d151;
    TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d296 =
	(TASK_testplusargs___d195 ||
	 TASK_testplusargs___d196 && TASK_testplusargs___d197) &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d295;
    TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d307 =
	(TASK_testplusargs___d195 ||
	 TASK_testplusargs___d196 && TASK_testplusargs___d197) &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d306;
    TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d322 =
	(TASK_testplusargs___d195 ||
	 TASK_testplusargs___d196 && TASK_testplusargs___d197) &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d321;
    TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d329 =
	(TASK_testplusargs___d195 ||
	 TASK_testplusargs___d196 && TASK_testplusargs___d197) &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d328;
    NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d202 =
	!core_request_put[0] && ma_satp_from_csr_s[63:60] != 4'd0 &&
	ma_curr_priv_c != 2'd3 &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d200;
    NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d211 =
	!core_request_put[0] && ma_satp_from_csr_s[63:60] != 4'd0 &&
	ma_curr_priv_c != 2'd3 &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d102 &&
	TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d208;
    NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d221 =
	!core_request_put[0] && ma_satp_from_csr_s[63:60] != 4'd0 &&
	ma_curr_priv_c != 2'd3 &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d102 &&
	TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d218;
    NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d236 =
	!core_request_put[0] && ma_satp_from_csr_s[63:60] != 4'd0 &&
	ma_curr_priv_c != 2'd3 &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d102 &&
	TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d233;
    NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d258 =
	!core_request_put[0] && ma_satp_from_csr_s[63:60] != 4'd0 &&
	ma_curr_priv_c != 2'd3 &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d102 &&
	TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d255;
    NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d243 =
	!core_request_put[0] && ma_satp_from_csr_s[63:60] != 4'd0 &&
	ma_curr_priv_c != 2'd3 &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d102 &&
	TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d240;
    NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d265 =
	!core_request_put[0] && ma_satp_from_csr_s[63:60] != 4'd0 &&
	ma_curr_priv_c != 2'd3 &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d102 &&
	TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d262;
    NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d269 =
	!core_request_put[0] && ma_satp_from_csr_s[63:60] != 4'd0 &&
	ma_curr_priv_c != 2'd3 &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d102 &&
	TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d266;
    NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d276 =
	!core_request_put[0] && ma_satp_from_csr_s[63:60] != 4'd0 &&
	ma_curr_priv_c != 2'd3 &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d102 &&
	TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d273;
    NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d280 =
	!core_request_put[0] && ma_satp_from_csr_s[63:60] != 4'd0 &&
	ma_curr_priv_c != 2'd3 &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d102 &&
	TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d277;
    NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d284 =
	!core_request_put[0] && ma_satp_from_csr_s[63:60] != 4'd0 &&
	ma_curr_priv_c != 2'd3 &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d102 &&
	TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d281;
    NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d299 =
	!core_request_put[0] && ma_satp_from_csr_s[63:60] != 4'd0 &&
	ma_curr_priv_c != 2'd3 &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d102 &&
	TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d296;
    NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d292 =
	!core_request_put[0] && ma_satp_from_csr_s[63:60] != 4'd0 &&
	ma_curr_priv_c != 2'd3 &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d102 &&
	TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d289;
    NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d303 =
	!core_request_put[0] && ma_satp_from_csr_s[63:60] != 4'd0 &&
	ma_curr_priv_c != 2'd3 &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d102 &&
	TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d300;
    NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d310 =
	!core_request_put[0] && ma_satp_from_csr_s[63:60] != 4'd0 &&
	ma_curr_priv_c != 2'd3 &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d102 &&
	TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d307;
    NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d325 =
	!core_request_put[0] && ma_satp_from_csr_s[63:60] != 4'd0 &&
	ma_curr_priv_c != 2'd3 &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d102 &&
	TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d322;
    NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d332 =
	!core_request_put[0] && ma_satp_from_csr_s[63:60] != 4'd0 &&
	ma_curr_priv_c != 2'd3 &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d102 &&
	TASK_testplusargs_95_OR_TASK_testplusargs_96_A_ETC___d329;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d194)
	begin
	  v__h3305 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d202)
	$write("[%10d", v__h3305, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d202)
	$write("ITLB: Hit in TLB:");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d202)
	$write("VPNTag { ", "permissions: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d202)
	$write("TLB_permissions { ", "v: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d211)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d221)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d202)
	$write(", ", "r: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d236)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d243)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d202)
	$write(", ", "w: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d258)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d265)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d202)
	$write(", ", "x: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d269)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d276)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d202)
	$write(", ", "u: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d280)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d284)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d202)
	$write(", ", "g: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d292)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d299)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d202)
	$write(", ", "a: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d303)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d310)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d202)
	$write(", ", "d: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d325)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d332)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d202)
	$write(" }");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d202)
	$write(", ", "vpn: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d202)
	$write("'h%h",
	       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d335);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d202)
	$write(", ", "asid: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d202)
	$write("'h%h",
	       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d338);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d202)
	$write(", ", "pagemask: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d202)
	$write("'h%h", mask__h4357);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d202)
	$write(", ", "ppn: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d202)
	$write("'h%h", x__h4642, " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d202)
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d194)
	begin
	  TASK_testplusargs___d339 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d194)
	begin
	  TASK_testplusargs___d340 = $test$plusargs("mitlb");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d194)
	begin
	  TASK_testplusargs___d341 = $test$plusargs("l0");
	  #0;
	end
    IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d344 =
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d102 &&
	(TASK_testplusargs___d339 ||
	 TASK_testplusargs___d340 && TASK_testplusargs___d341);
    NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d346 =
	!core_request_put[0] && ma_satp_from_csr_s[63:60] != 4'd0 &&
	ma_curr_priv_c != 2'd3 &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d344;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d194)
	begin
	  v__h4429 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d346)
	$write("[%10d", v__h4429, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d346)
	$write("mask:%h", mask__h4357);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d346)
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d194)
	begin
	  TASK_testplusargs___d348 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d194)
	begin
	  TASK_testplusargs___d349 = $test$plusargs("mitlb");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d194)
	begin
	  TASK_testplusargs___d350 = $test$plusargs("l0");
	  #0;
	end
    IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d353 =
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d102 &&
	(TASK_testplusargs___d348 ||
	 TASK_testplusargs___d349 && TASK_testplusargs___d350);
    NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d355 =
	!core_request_put[0] && ma_satp_from_csr_s[63:60] != 4'd0 &&
	ma_curr_priv_c != 2'd3 &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d353;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d194)
	begin
	  v__h4589 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d355)
	$write("[%10d", v__h4589, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d355)
	$write("lower_ppn:%h", x__h4642[17:0]);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d355)
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d194)
	begin
	  TASK_testplusargs___d357 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d194)
	begin
	  TASK_testplusargs___d358 = $test$plusargs("mitlb");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d194)
	begin
	  TASK_testplusargs___d359 = $test$plusargs("l0");
	  #0;
	end
    IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d362 =
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d102 &&
	(TASK_testplusargs___d357 ||
	 TASK_testplusargs___d358 && TASK_testplusargs___d359);
    NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d364 =
	!core_request_put[0] && ma_satp_from_csr_s[63:60] != 4'd0 &&
	ma_curr_priv_c != 2'd3 &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d362;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d194)
	begin
	  v__h4749 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d364)
	$write("[%10d", v__h4749, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d364)
	$write("lower_vpn:%h", core_request_put[30:13]);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d364)
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d194)
	begin
	  TASK_testplusargs___d366 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d194)
	begin
	  TASK_testplusargs___d367 = $test$plusargs("mitlb");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d194)
	begin
	  TASK_testplusargs___d368 = $test$plusargs("l0");
	  #0;
	end
    IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d371 =
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d102 &&
	(TASK_testplusargs___d366 ||
	 TASK_testplusargs___d367 && TASK_testplusargs___d368);
    NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d373 =
	!core_request_put[0] && ma_satp_from_csr_s[63:60] != 4'd0 &&
	ma_curr_priv_c != 2'd3 &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d371;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d194)
	begin
	  v__h4906 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d373)
	$write("[%10d", v__h4906, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d373)
	$write("lower_pa:%h", lower_pa__h4360);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d373)
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d194)
	begin
	  TASK_testplusargs___d375 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d194)
	begin
	  TASK_testplusargs___d376 = $test$plusargs("mitlb");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d194)
	begin
	  TASK_testplusargs___d377 = $test$plusargs("l0");
	  #0;
	end
    IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d380 =
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d102 &&
	(TASK_testplusargs___d375 ||
	 TASK_testplusargs___d376 && TASK_testplusargs___d377);
    NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d382 =
	!core_request_put[0] && ma_satp_from_csr_s[63:60] != 4'd0 &&
	ma_curr_priv_c != 2'd3 &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d380;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d194)
	begin
	  v__h5075 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d382)
	$write("[%10d", v__h5075, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d382)
	$write("highest_ppn:%h", x__h4642[43:18]);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d382)
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d194)
	begin
	  TASK_testplusargs___d385 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d194)
	begin
	  TASK_testplusargs___d386 = $test$plusargs("mitlb");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d194)
	begin
	  TASK_testplusargs___d387 = $test$plusargs("l0");
	  #0;
	end
    IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d390 =
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d102 &&
	(TASK_testplusargs___d385 ||
	 TASK_testplusargs___d386 && TASK_testplusargs___d387);
    NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d392 =
	!core_request_put[0] && ma_satp_from_csr_s[63:60] != 4'd0 &&
	ma_curr_priv_c != 2'd3 &&
	IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d390;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d194)
	begin
	  v__h5236 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d392)
	$write("[%10d", v__h5236, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d392)
	$write("ITLB: Sending PA:%h Trap:%b",
	       physicaladdress__h4362,
	       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d140 ||
	       IF_NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CON_ETC___d177);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d392)
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d403)
	begin
	  TASK_testplusargs___d404 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d403)
	begin
	  TASK_testplusargs___d405 = $test$plusargs("mitlb");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d403)
	begin
	  TASK_testplusargs___d406 = $test$plusargs("l0");
	  #0;
	end
    NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d409 =
	NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d401 &&
	(TASK_testplusargs___d404 ||
	 TASK_testplusargs___d405 && TASK_testplusargs___d406);
    NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d411 =
	!core_request_put[0] && ma_satp_from_csr_s[63:60] != 4'd0 &&
	ma_curr_priv_c != 2'd3 &&
	NOT_v_vpn_tag_0_6_BIT_98_7_8_OR_NOT_511_CONCAT_ETC___d409;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d403)
	begin
	  v__h4167 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d411)
	$write("[%10d", v__h4167, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d411)
	$write("ITLB : TLBMiss. Sending Address to PTW:%h",
	       core_request_put[64:1]);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_core_request_put &&
	  NOT_core_request_put_BIT_0_1_AND_NOT_wr_satp_w_ETC___d411)
	$write("\n");
  end
  // synopsys translate_on
endmodule  // mkfa_itlb

