//
// Generated by Bluespec Compiler (build a026416)
//
// On Tue Aug 11 13:42:09 IST 2020
//
//
// Ports:
// Name                         I/O  size props
// rx_common_from_stage3_deq_ena  O     1
// rx_type_from_stage3_deq_ena    O     1
// tx_min_enq_ena                 O     1
// tx_min_enq_data_fst            O   136
// tx_min_enq_data_snd            O     1
// rx_inst_deq_ena                O     1
// tx_inst_enq_ena                O     1
// tx_inst_enq_data_fst           O    64
// tx_inst_enq_data_snd           O    32
// RDY_memory_response_put        O     1
// CLK                            I     1 clock
// RST_N                          I     1 reset
// rx_common_from_stage3_notEmpty_b  I     1 unused
// rx_common_from_stage3_first_deq_rdy_b  I     1
// rx_common_from_stage3_first_x  I    71
// rx_type_from_stage3_notEmpty_b  I     1 unused
// rx_type_from_stage3_first_deq_rdy_b  I     1
// rx_type_from_stage3_first_x    I    83
// tx_min_notFull_b               I     1 unused
// tx_min_enq_rdy_b               I     1
// rx_inst_notEmpty_b             I     1 unused
// rx_inst_first_deq_rdy_b        I     1
// rx_inst_first_x                I    96
// tx_inst_notFull_b              I     1 unused
// tx_inst_enq_rdy_b              I     1
// memory_response_put            I    72
// EN_memory_response_put         I     1
//
// Combinational paths from inputs to outputs:
//   (rx_common_from_stage3_first_deq_rdy_b,
//    rx_common_from_stage3_first_x,
//    rx_type_from_stage3_first_deq_rdy_b,
//    rx_type_from_stage3_first_x,
//    tx_min_enq_rdy_b,
//    rx_inst_first_deq_rdy_b,
//    tx_inst_enq_rdy_b,
//    memory_response_put,
//    EN_memory_response_put) -> rx_common_from_stage3_deq_ena
//   (rx_common_from_stage3_first_deq_rdy_b,
//    rx_common_from_stage3_first_x,
//    rx_type_from_stage3_first_deq_rdy_b,
//    rx_type_from_stage3_first_x,
//    tx_min_enq_rdy_b,
//    rx_inst_first_deq_rdy_b,
//    tx_inst_enq_rdy_b,
//    memory_response_put,
//    EN_memory_response_put) -> rx_type_from_stage3_deq_ena
//   (rx_common_from_stage3_first_deq_rdy_b,
//    rx_common_from_stage3_first_x,
//    rx_type_from_stage3_first_deq_rdy_b,
//    rx_type_from_stage3_first_x,
//    tx_min_enq_rdy_b,
//    rx_inst_first_deq_rdy_b,
//    tx_inst_enq_rdy_b,
//    memory_response_put,
//    EN_memory_response_put) -> tx_min_enq_ena
//   (rx_common_from_stage3_first_deq_rdy_b,
//    rx_common_from_stage3_first_x,
//    rx_type_from_stage3_first_deq_rdy_b,
//    rx_type_from_stage3_first_x,
//    tx_min_enq_rdy_b,
//    rx_inst_first_deq_rdy_b,
//    tx_inst_enq_rdy_b,
//    memory_response_put,
//    EN_memory_response_put) -> tx_min_enq_data_fst
//   (rx_common_from_stage3_first_deq_rdy_b,
//    rx_common_from_stage3_first_x,
//    rx_type_from_stage3_first_deq_rdy_b,
//    rx_type_from_stage3_first_x,
//    tx_min_enq_rdy_b,
//    rx_inst_first_deq_rdy_b,
//    tx_inst_enq_rdy_b,
//    memory_response_put,
//    EN_memory_response_put) -> tx_min_enq_data_snd
//   (rx_common_from_stage3_first_deq_rdy_b,
//    rx_common_from_stage3_first_x,
//    rx_type_from_stage3_first_deq_rdy_b,
//    rx_type_from_stage3_first_x,
//    tx_min_enq_rdy_b,
//    rx_inst_first_deq_rdy_b,
//    tx_inst_enq_rdy_b,
//    memory_response_put,
//    EN_memory_response_put) -> rx_inst_deq_ena
//   (rx_common_from_stage3_first_deq_rdy_b,
//    rx_common_from_stage3_first_x,
//    rx_type_from_stage3_first_deq_rdy_b,
//    rx_type_from_stage3_first_x,
//    tx_min_enq_rdy_b,
//    rx_inst_first_deq_rdy_b,
//    tx_inst_enq_rdy_b,
//    memory_response_put,
//    EN_memory_response_put) -> tx_inst_enq_ena
//   (rx_common_from_stage3_first_deq_rdy_b,
//    rx_common_from_stage3_first_x,
//    rx_type_from_stage3_first_deq_rdy_b,
//    rx_type_from_stage3_first_x,
//    tx_min_enq_rdy_b,
//    rx_inst_first_deq_rdy_b,
//    rx_inst_first_x,
//    tx_inst_enq_rdy_b,
//    memory_response_put,
//    EN_memory_response_put) -> tx_inst_enq_data_fst
//   (rx_common_from_stage3_first_deq_rdy_b,
//    rx_common_from_stage3_first_x,
//    rx_type_from_stage3_first_deq_rdy_b,
//    rx_type_from_stage3_first_x,
//    tx_min_enq_rdy_b,
//    rx_inst_first_deq_rdy_b,
//    rx_inst_first_x,
//    tx_inst_enq_rdy_b,
//    memory_response_put,
//    EN_memory_response_put) -> tx_inst_enq_data_snd
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkstage4(CLK,
		RST_N,

		rx_common_from_stage3_notEmpty_b,

		rx_common_from_stage3_first_deq_rdy_b,

		rx_common_from_stage3_first_x,

		rx_common_from_stage3_deq_ena,

		rx_type_from_stage3_notEmpty_b,

		rx_type_from_stage3_first_deq_rdy_b,

		rx_type_from_stage3_first_x,

		rx_type_from_stage3_deq_ena,

		tx_min_notFull_b,

		tx_min_enq_rdy_b,

		tx_min_enq_ena,

		tx_min_enq_data_fst,

		tx_min_enq_data_snd,

		rx_inst_notEmpty_b,

		rx_inst_first_deq_rdy_b,

		rx_inst_first_x,

		rx_inst_deq_ena,

		tx_inst_notFull_b,

		tx_inst_enq_rdy_b,

		tx_inst_enq_ena,

		tx_inst_enq_data_fst,

		tx_inst_enq_data_snd,

		memory_response_put,
		EN_memory_response_put,
		RDY_memory_response_put);
  parameter [63 : 0] hartid = 64'b0;
  input  CLK;
  input  RST_N;

  // action method rx_common_from_stage3_notEmpty
  input  rx_common_from_stage3_notEmpty_b;

  // action method rx_common_from_stage3_first_deq_rdy
  input  rx_common_from_stage3_first_deq_rdy_b;

  // action method rx_common_from_stage3_first
  input  [70 : 0] rx_common_from_stage3_first_x;

  // value method rx_common_from_stage3_deq_ena
  output rx_common_from_stage3_deq_ena;

  // action method rx_type_from_stage3_notEmpty
  input  rx_type_from_stage3_notEmpty_b;

  // action method rx_type_from_stage3_first_deq_rdy
  input  rx_type_from_stage3_first_deq_rdy_b;

  // action method rx_type_from_stage3_first
  input  [82 : 0] rx_type_from_stage3_first_x;

  // value method rx_type_from_stage3_deq_ena
  output rx_type_from_stage3_deq_ena;

  // action method tx_min_notFull
  input  tx_min_notFull_b;

  // action method tx_min_enq_rdy
  input  tx_min_enq_rdy_b;

  // value method tx_min_enq_ena
  output tx_min_enq_ena;

  // value method tx_min_enq_data_fst
  output [135 : 0] tx_min_enq_data_fst;

  // value method tx_min_enq_data_snd
  output tx_min_enq_data_snd;

  // action method rx_inst_notEmpty
  input  rx_inst_notEmpty_b;

  // action method rx_inst_first_deq_rdy
  input  rx_inst_first_deq_rdy_b;

  // action method rx_inst_first
  input  [95 : 0] rx_inst_first_x;

  // value method rx_inst_deq_ena
  output rx_inst_deq_ena;

  // action method tx_inst_notFull
  input  tx_inst_notFull_b;

  // action method tx_inst_enq_rdy
  input  tx_inst_enq_rdy_b;

  // value method tx_inst_enq_ena
  output tx_inst_enq_ena;

  // value method tx_inst_enq_data_fst
  output [63 : 0] tx_inst_enq_data_fst;

  // value method tx_inst_enq_data_snd
  output [31 : 0] tx_inst_enq_data_snd;

  // action method memory_response_put
  input  [71 : 0] memory_response_put;
  input  EN_memory_response_put;
  output RDY_memory_response_put;

  // signals for module outputs
  wire [135 : 0] tx_min_enq_data_fst;
  wire [63 : 0] tx_inst_enq_data_fst;
  wire [31 : 0] tx_inst_enq_data_snd;
  wire RDY_memory_response_put,
       rx_common_from_stage3_deq_ena,
       rx_inst_deq_ena,
       rx_type_from_stage3_deq_ena,
       tx_inst_enq_ena,
       tx_min_enq_data_snd,
       tx_min_enq_ena;

  // inlined wires
  wire [136 : 0] txmin_w_data_wget;
  wire [82 : 0] rx_type_w_data_wget;
  wire [72 : 0] ff_memory_response_rv_port0__write_1,
		ff_memory_response_rv_port1__read,
		ff_memory_response_rv_port1__write_1,
		ff_memory_response_rv_port2__read;
  wire ff_memory_response_rv_EN_port1__write, rx_common_w_ena_whas;

  // register ff_memory_response_rv
  reg [72 : 0] ff_memory_response_rv;
  wire [72 : 0] ff_memory_response_rv_D_IN;
  wire ff_memory_response_rv_EN;

  // rule scheduling signals
  wire CAN_FIRE_RL_check_instruction,
       CAN_FIRE_memory_response_put,
       CAN_FIRE_rx_common_from_stage3_first,
       CAN_FIRE_rx_common_from_stage3_first_deq_rdy,
       CAN_FIRE_rx_common_from_stage3_notEmpty,
       CAN_FIRE_rx_inst_first,
       CAN_FIRE_rx_inst_first_deq_rdy,
       CAN_FIRE_rx_inst_notEmpty,
       CAN_FIRE_rx_type_from_stage3_first,
       CAN_FIRE_rx_type_from_stage3_first_deq_rdy,
       CAN_FIRE_rx_type_from_stage3_notEmpty,
       CAN_FIRE_tx_inst_enq_rdy,
       CAN_FIRE_tx_inst_notFull,
       CAN_FIRE_tx_min_enq_rdy,
       CAN_FIRE_tx_min_notFull,
       WILL_FIRE_RL_check_instruction,
       WILL_FIRE_memory_response_put,
       WILL_FIRE_rx_common_from_stage3_first,
       WILL_FIRE_rx_common_from_stage3_first_deq_rdy,
       WILL_FIRE_rx_common_from_stage3_notEmpty,
       WILL_FIRE_rx_inst_first,
       WILL_FIRE_rx_inst_first_deq_rdy,
       WILL_FIRE_rx_inst_notEmpty,
       WILL_FIRE_rx_type_from_stage3_first,
       WILL_FIRE_rx_type_from_stage3_first_deq_rdy,
       WILL_FIRE_rx_type_from_stage3_notEmpty,
       WILL_FIRE_tx_inst_enq_rdy,
       WILL_FIRE_tx_inst_notFull,
       WILL_FIRE_tx_min_enq_rdy,
       WILL_FIRE_tx_min_notFull;

  // declarations used by system tasks
  // synopsys translate_off
  reg TASK_testplusargs___d10;
  reg TASK_testplusargs___d11;
  reg TASK_testplusargs___d12;
  reg [63 : 0] v__h1603;
  reg TASK_testplusargs___d30;
  reg TASK_testplusargs___d31;
  reg TASK_testplusargs___d32;
  reg [63 : 0] v__h1850;
  reg TASK_testplusargs___d121;
  reg TASK_testplusargs___d122;
  reg TASK_testplusargs___d123;
  reg [63 : 0] v__h2413;
  reg TASK_testplusargs___d147;
  reg TASK_testplusargs___d148;
  reg TASK_testplusargs___d149;
  reg [63 : 0] v__h2669;
  reg TASK_testplusargs___d158;
  reg TASK_testplusargs___d159;
  reg TASK_testplusargs___d160;
  reg [63 : 0] v__h2853;
  reg TASK_testplusargs___d168;
  reg TASK_testplusargs___d169;
  reg TASK_testplusargs___d170;
  reg [63 : 0] v__h3099;
  reg ff_memory_response_rv_port1__read__17_BIT_72_1_ETC___d126;
  reg TASK_testplusargs_21_OR_TASK_testplusargs_22_A_ETC___d132;
  reg TASK_testplusargs_21_OR_TASK_testplusargs_22_A_ETC___d136;
  reg NOT_IF_rx_common_w_data_whas__6_THEN_rx_common_ETC___d152;
  reg NOT_ff_memory_response_rv_port1__read__17_BIT__ETC___d163;
  reg TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d179;
  reg TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d203;
  reg TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d212;
  reg TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d245;
  reg TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d254;
  reg TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d257;
  reg TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d266;
  reg TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d26;
  reg TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d29;
  reg TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d41;
  reg TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d44;
  reg TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d47;
  reg TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d57;
  reg TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d71;
  reg TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d76;
  reg TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d91;
  reg TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d94;
  reg TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d97;
  reg TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d100;
  reg TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d103;
  reg TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d114;
  reg NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d173;
  reg NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d180;
  reg TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d186;
  reg NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d204;
  reg NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d213;
  reg NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d246;
  reg NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d255;
  reg NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d258;
  reg NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d267;
  // synopsys translate_on

  // remaining internal signals
  reg [2 : 0] CASE_rx_type_from_stage3_first_x_BITS_3_TO_1_0_ETC__q2,
	      IF_rx_type_w_data_whas__6_THEN_IF_rx_type_w_da_ETC___d88;
  reg [1 : 0] CASE_rx_type_from_stage3_first_x_BITS_82_TO_81_ETC__q1;
  wire [135 : 0] IF_rx_type_w_data_whas__6_AND_rx_type_w_data_w_ETC___d299,
		 IF_rx_type_w_data_whas__6_AND_rx_type_w_data_w_ETC___d300,
		 IF_rx_type_w_data_whas__6_AND_rx_type_w_data_w_ETC___d301;
  wire [133 : 0] IF_rx_type_w_data_whas__6_AND_rx_type_w_data_w_ETC___d283;
  wire [63 : 0] _theResult___word__h3371,
		commitvalue__h3332,
		value__h3303,
		value__h3359,
		x_first_word__h2498;
  wire [5 : 0] x_first_cause__h2500;
  wire [4 : 0] value__h3496;
  wire IF_rx_common_w_data_whas__6_THEN_rx_common_w_d_ETC___d143,
       NOT_ff_memory_response_rv_port1__read__17_BIT__ETC___d194,
       NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d189,
       NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d202,
       NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d210,
       NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d243,
       NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d252,
       ff_memory_response_rv_port1__read__17_BIT_72_1_ETC___d184,
       ff_memory_response_rv_port1__read__17_BIT_72_1_ETC___d198,
       rx_type_w_data_whas__6_AND_rx_type_w_data_wget_ETC___d177,
       x_first_epochs__h2501;

  // action method rx_common_from_stage3_notEmpty
  assign CAN_FIRE_rx_common_from_stage3_notEmpty = 1'd1 ;
  assign WILL_FIRE_rx_common_from_stage3_notEmpty = 1'd1 ;

  // action method rx_common_from_stage3_first_deq_rdy
  assign CAN_FIRE_rx_common_from_stage3_first_deq_rdy = 1'd1 ;
  assign WILL_FIRE_rx_common_from_stage3_first_deq_rdy = 1'd1 ;

  // action method rx_common_from_stage3_first
  assign CAN_FIRE_rx_common_from_stage3_first = 1'd1 ;
  assign WILL_FIRE_rx_common_from_stage3_first = 1'd1 ;

  // value method rx_common_from_stage3_deq_ena
  assign rx_common_from_stage3_deq_ena = rx_common_w_ena_whas ;

  // action method rx_type_from_stage3_notEmpty
  assign CAN_FIRE_rx_type_from_stage3_notEmpty = 1'd1 ;
  assign WILL_FIRE_rx_type_from_stage3_notEmpty = 1'd1 ;

  // action method rx_type_from_stage3_first_deq_rdy
  assign CAN_FIRE_rx_type_from_stage3_first_deq_rdy = 1'd1 ;
  assign WILL_FIRE_rx_type_from_stage3_first_deq_rdy = 1'd1 ;

  // action method rx_type_from_stage3_first
  assign CAN_FIRE_rx_type_from_stage3_first = 1'd1 ;
  assign WILL_FIRE_rx_type_from_stage3_first = 1'd1 ;

  // value method rx_type_from_stage3_deq_ena
  assign rx_type_from_stage3_deq_ena = rx_common_w_ena_whas ;

  // action method tx_min_notFull
  assign CAN_FIRE_tx_min_notFull = 1'd1 ;
  assign WILL_FIRE_tx_min_notFull = 1'd1 ;

  // action method tx_min_enq_rdy
  assign CAN_FIRE_tx_min_enq_rdy = 1'd1 ;
  assign WILL_FIRE_tx_min_enq_rdy = 1'd1 ;

  // value method tx_min_enq_ena
  assign tx_min_enq_ena = rx_common_w_ena_whas ;

  // value method tx_min_enq_data_fst
  assign tx_min_enq_data_fst =
	     (rx_common_w_ena_whas && txmin_w_data_wget[136:135] == 2'd0) ?
	       { 2'd0, txmin_w_data_wget[134:1] } :
	       ((rx_common_w_ena_whas && txmin_w_data_wget[136:135] == 2'd1) ?
		  { 2'd1, txmin_w_data_wget[134:1] } :
		  ((rx_common_w_ena_whas &&
		    txmin_w_data_wget[136:135] == 2'd2) ?
		     { 2'd2, txmin_w_data_wget[134:1] } :
		     { 2'd3,
		       48'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */ ,
		       txmin_w_data_wget[86:1] })) ;

  // value method tx_min_enq_data_snd
  assign tx_min_enq_data_snd = txmin_w_data_wget[0] ;

  // action method rx_inst_notEmpty
  assign CAN_FIRE_rx_inst_notEmpty = 1'd1 ;
  assign WILL_FIRE_rx_inst_notEmpty = 1'd1 ;

  // action method rx_inst_first_deq_rdy
  assign CAN_FIRE_rx_inst_first_deq_rdy = 1'd1 ;
  assign WILL_FIRE_rx_inst_first_deq_rdy = 1'd1 ;

  // action method rx_inst_first
  assign CAN_FIRE_rx_inst_first = 1'd1 ;
  assign WILL_FIRE_rx_inst_first = 1'd1 ;

  // value method rx_inst_deq_ena
  assign rx_inst_deq_ena = rx_common_w_ena_whas ;

  // action method tx_inst_notFull
  assign CAN_FIRE_tx_inst_notFull = 1'd1 ;
  assign WILL_FIRE_tx_inst_notFull = 1'd1 ;

  // action method tx_inst_enq_rdy
  assign CAN_FIRE_tx_inst_enq_rdy = 1'd1 ;
  assign WILL_FIRE_tx_inst_enq_rdy = 1'd1 ;

  // value method tx_inst_enq_ena
  assign tx_inst_enq_ena = rx_common_w_ena_whas ;

  // value method tx_inst_enq_data_fst
  assign tx_inst_enq_data_fst = rx_inst_first_x[95:32] ;

  // value method tx_inst_enq_data_snd
  assign tx_inst_enq_data_snd = rx_inst_first_x[31:0] ;

  // action method memory_response_put
  assign RDY_memory_response_put = !ff_memory_response_rv[72] ;
  assign CAN_FIRE_memory_response_put = !ff_memory_response_rv[72] ;
  assign WILL_FIRE_memory_response_put = EN_memory_response_put ;

  // rule RL_check_instruction
  assign CAN_FIRE_RL_check_instruction =
	     rx_type_from_stage3_first_deq_rdy_b &&
	     rx_common_from_stage3_first_deq_rdy_b &&
	     tx_min_enq_rdy_b &&
	     tx_inst_enq_rdy_b &&
	     rx_inst_first_deq_rdy_b ;
  assign WILL_FIRE_RL_check_instruction = CAN_FIRE_RL_check_instruction ;

  // inlined wires
  assign rx_common_w_ena_whas =
	     WILL_FIRE_RL_check_instruction &&
	     (rx_type_w_data_wget[82:81] != 2'd0 ||
	      ff_memory_response_rv_port1__read[72] &&
	      IF_rx_common_w_data_whas__6_THEN_rx_common_w_d_ETC___d143) ;
  assign rx_type_w_data_wget =
	     { CASE_rx_type_from_stage3_first_x_BITS_82_TO_81_ETC__q1,
	       (rx_type_from_stage3_first_x[82:81] == 2'd0) ?
		 { 77'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */ ,
		   CASE_rx_type_from_stage3_first_x_BITS_3_TO_1_0_ETC__q2,
		   rx_type_from_stage3_first_x[0] } :
		 rx_type_from_stage3_first_x[80:0] } ;
  assign txmin_w_data_wget =
	     { IF_rx_type_w_data_whas__6_AND_rx_type_w_data_w_ETC___d301,
	       rx_common_from_stage3_first_x[1] } ;
  assign ff_memory_response_rv_port0__write_1 =
	     { 1'd1, memory_response_put } ;
  assign ff_memory_response_rv_port1__read =
	     EN_memory_response_put ?
	       ff_memory_response_rv_port0__write_1 :
	       ff_memory_response_rv ;
  assign ff_memory_response_rv_EN_port1__write =
	     WILL_FIRE_RL_check_instruction &&
	     rx_type_w_data_wget[82:81] == 2'd0 &&
	     ff_memory_response_rv_port1__read[72] ;
  assign ff_memory_response_rv_port1__write_1 =
	     { 1'd0,
	       72'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */  } ;
  assign ff_memory_response_rv_port2__read =
	     ff_memory_response_rv_EN_port1__write ?
	       ff_memory_response_rv_port1__write_1 :
	       ff_memory_response_rv_port1__read ;

  // register ff_memory_response_rv
  assign ff_memory_response_rv_D_IN = ff_memory_response_rv_port2__read ;
  assign ff_memory_response_rv_EN = 1'b1 ;

  // remaining internal signals
  assign IF_rx_common_w_data_whas__6_THEN_rx_common_w_d_ETC___d143 =
	     rx_common_from_stage3_first_x[1] ==
	     ff_memory_response_rv_port1__read[0] ;
  assign IF_rx_type_w_data_whas__6_AND_rx_type_w_data_w_ETC___d283 =
	     (rx_type_w_data_wget[82:81] == 2'd1) ?
	       { rx_type_w_data_wget[69:0],
		 rx_common_from_stage3_first_x[70:7] } :
	       { x_first_cause__h2500,
		 x_first_word__h2498,
		 rx_common_from_stage3_first_x[70:7] } ;
  assign IF_rx_type_w_data_whas__6_AND_rx_type_w_data_w_ETC___d299 =
	     (rx_type_w_data_wget[82:81] == 2'd2 ||
	      rx_type_w_data_wget[82:81] == 2'd0 &&
	      ff_memory_response_rv_port1__read__17_BIT_72_1_ETC___d198) ?
	       { 2'd2,
		 59'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */ ,
		 (rx_type_w_data_wget[82:81] == 2'd2) ?
		   { rx_type_w_data_wget[68:5],
		     rx_common_from_stage3_first_x[6:2],
		     rx_type_w_data_wget[4:0],
		     rx_common_from_stage3_first_x[0] } :
		   { _theResult___word__h3371,
		     rx_common_from_stage3_first_x[6:2],
		     5'd0,
		     rx_common_from_stage3_first_x[0] } } :
	       { 2'd3,
		 48'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */ ,
		 rx_type_w_data_wget[80:0],
		 rx_common_from_stage3_first_x[6:2] } ;
  assign IF_rx_type_w_data_whas__6_AND_rx_type_w_data_w_ETC___d300 =
	     (rx_type_w_data_wget[82:81] == 2'd0 &&
	      ff_memory_response_rv_port1__read__17_BIT_72_1_ETC___d184) ?
	       { 2'd1,
		 1'bx /* unspecified value */ ,
		 rx_common_from_stage3_first_x[70:7],
		 commitvalue__h3332,
		 rx_common_from_stage3_first_x[6:2] } :
	       IF_rx_type_w_data_whas__6_AND_rx_type_w_data_w_ETC___d299 ;
  assign IF_rx_type_w_data_whas__6_AND_rx_type_w_data_w_ETC___d301 =
	     (rx_type_w_data_wget[82:81] == 2'd1 ||
	      rx_type_w_data_whas__6_AND_rx_type_w_data_wget_ETC___d177) ?
	       { 2'd0,
		 IF_rx_type_w_data_whas__6_AND_rx_type_w_data_w_ETC___d283 } :
	       IF_rx_type_w_data_whas__6_AND_rx_type_w_data_w_ETC___d300 ;
  assign NOT_ff_memory_response_rv_port1__read__17_BIT__ETC___d194 =
	     !ff_memory_response_rv_port1__read[72] ||
	     !IF_rx_common_w_data_whas__6_THEN_rx_common_w_d_ETC___d143 ||
	     ff_memory_response_rv_port1__read[7] ||
	     IF_rx_type_w_data_whas__6_THEN_IF_rx_type_w_da_ETC___d88 !=
	     3'd1 &&
	     IF_rx_type_w_data_whas__6_THEN_IF_rx_type_w_da_ETC___d88 !=
	     3'd4 ;
  assign NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d189 =
	     rx_type_w_data_wget[82:81] != 2'd0 ||
	     !ff_memory_response_rv_port1__read[72] ||
	     !IF_rx_common_w_data_whas__6_THEN_rx_common_w_d_ETC___d143 ||
	     !ff_memory_response_rv_port1__read[7] ;
  assign NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d202 =
	     NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d189 &&
	     (rx_type_w_data_wget[82:81] != 2'd0 ||
	      NOT_ff_memory_response_rv_port1__read__17_BIT__ETC___d194) &&
	     (rx_type_w_data_wget[82:81] == 2'd2 ||
	      rx_type_w_data_wget[82:81] == 2'd0 &&
	      ff_memory_response_rv_port1__read__17_BIT_72_1_ETC___d198) ;
  assign NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d210 =
	     (rx_type_w_data_wget[82:81] != 2'd0 ||
	      NOT_ff_memory_response_rv_port1__read__17_BIT__ETC___d194) &&
	     rx_type_w_data_wget[82:81] != 2'd2 &&
	     (rx_type_w_data_wget[82:81] != 2'd0 ||
	      !ff_memory_response_rv_port1__read[72] ||
	      !IF_rx_common_w_data_whas__6_THEN_rx_common_w_d_ETC___d143 ||
	      ff_memory_response_rv_port1__read[7] ||
	      IF_rx_type_w_data_whas__6_THEN_IF_rx_type_w_da_ETC___d88 ==
	      3'd1 ||
	      IF_rx_type_w_data_whas__6_THEN_IF_rx_type_w_da_ETC___d88 ==
	      3'd4) ;
  assign NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d243 =
	     (rx_type_w_data_wget[82:81] != 2'd0 ||
	      NOT_ff_memory_response_rv_port1__read__17_BIT__ETC___d194) &&
	     (rx_type_w_data_wget[82:81] == 2'd2 ||
	      rx_type_w_data_wget[82:81] == 2'd0 &&
	      ff_memory_response_rv_port1__read__17_BIT_72_1_ETC___d198) &&
	     rx_common_from_stage3_first_x[0] ;
  assign NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d252 =
	     (rx_type_w_data_wget[82:81] != 2'd0 ||
	      NOT_ff_memory_response_rv_port1__read__17_BIT__ETC___d194) &&
	     (rx_type_w_data_wget[82:81] == 2'd2 ||
	      rx_type_w_data_wget[82:81] == 2'd0 &&
	      ff_memory_response_rv_port1__read__17_BIT_72_1_ETC___d198) &&
	     !rx_common_from_stage3_first_x[0] ;
  assign _theResult___word__h3371 =
	     rx_type_w_data_wget[0] ?
	       { 32'hFFFFFFFF, x_first_word__h2498[31:0] } :
	       x_first_word__h2498 ;
  assign commitvalue__h3332 = value__h3359 ;
  assign ff_memory_response_rv_port1__read__17_BIT_72_1_ETC___d184 =
	     ff_memory_response_rv_port1__read[72] &&
	     IF_rx_common_w_data_whas__6_THEN_rx_common_w_d_ETC___d143 &&
	     !ff_memory_response_rv_port1__read[7] &&
	     (IF_rx_type_w_data_whas__6_THEN_IF_rx_type_w_da_ETC___d88 ==
	      3'd1 ||
	      IF_rx_type_w_data_whas__6_THEN_IF_rx_type_w_da_ETC___d88 ==
	      3'd4) ;
  assign ff_memory_response_rv_port1__read__17_BIT_72_1_ETC___d198 =
	     ff_memory_response_rv_port1__read[72] &&
	     IF_rx_common_w_data_whas__6_THEN_rx_common_w_d_ETC___d143 &&
	     !ff_memory_response_rv_port1__read[7] &&
	     IF_rx_type_w_data_whas__6_THEN_IF_rx_type_w_da_ETC___d88 !=
	     3'd1 &&
	     IF_rx_type_w_data_whas__6_THEN_IF_rx_type_w_da_ETC___d88 !=
	     3'd4 ;
  assign rx_type_w_data_whas__6_AND_rx_type_w_data_wget_ETC___d177 =
	     rx_type_w_data_wget[82:81] == 2'd0 &&
	     ff_memory_response_rv_port1__read[72] &&
	     IF_rx_common_w_data_whas__6_THEN_rx_common_w_d_ETC___d143 &&
	     ff_memory_response_rv_port1__read[7] ;
  assign value__h3303 =
	     (rx_type_w_data_wget[82:81] == 2'd1) ?
	       rx_type_w_data_wget[63:0] :
	       x_first_word__h2498 ;
  assign value__h3359 =
	     (IF_rx_type_w_data_whas__6_THEN_IF_rx_type_w_da_ETC___d88 ==
	      3'd4) ?
	       _theResult___word__h3371 :
	       64'd0 ;
  assign value__h3496 =
	     (rx_type_w_data_wget[82:81] == 2'd2) ?
	       rx_type_w_data_wget[4:0] :
	       5'd0 ;
  assign x_first_cause__h2500 =
	     ff_memory_response_rv_port1__read[72] ?
	       ff_memory_response_rv_port1__read[6:1] :
	       6'd0 ;
  assign x_first_epochs__h2501 =
	     ff_memory_response_rv_port1__read[72] &&
	     ff_memory_response_rv_port1__read[0] ;
  assign x_first_word__h2498 =
	     ff_memory_response_rv_port1__read[72] ?
	       ff_memory_response_rv_port1__read[71:8] :
	       64'd0 ;
  always@(rx_type_from_stage3_first_x)
  begin
    case (rx_type_from_stage3_first_x[82:81])
      2'd0, 2'd1, 2'd2:
	  CASE_rx_type_from_stage3_first_x_BITS_82_TO_81_ETC__q1 =
	      rx_type_from_stage3_first_x[82:81];
      2'd3: CASE_rx_type_from_stage3_first_x_BITS_82_TO_81_ETC__q1 = 2'd3;
    endcase
  end
  always@(rx_type_from_stage3_first_x)
  begin
    case (rx_type_from_stage3_first_x[3:1])
      3'd0, 3'd1, 3'd2, 3'd3, 3'd4:
	  CASE_rx_type_from_stage3_first_x_BITS_3_TO_1_0_ETC__q2 =
	      rx_type_from_stage3_first_x[3:1];
      default: CASE_rx_type_from_stage3_first_x_BITS_3_TO_1_0_ETC__q2 = 3'd5;
    endcase
  end
  always@(rx_type_w_data_wget)
  begin
    case (rx_type_w_data_wget[3:1])
      3'd0, 3'd1:
	  IF_rx_type_w_data_whas__6_THEN_IF_rx_type_w_da_ETC___d88 =
	      rx_type_w_data_wget[3:1];
      3'd2: IF_rx_type_w_data_whas__6_THEN_IF_rx_type_w_da_ETC___d88 = 3'd4;
      3'd3: IF_rx_type_w_data_whas__6_THEN_IF_rx_type_w_da_ETC___d88 = 3'd2;
      3'd4: IF_rx_type_w_data_whas__6_THEN_IF_rx_type_w_da_ETC___d88 = 3'd3;
      default: IF_rx_type_w_data_whas__6_THEN_IF_rx_type_w_da_ETC___d88 =
		   3'd5;
    endcase
  end

  // handling of inlined registers

  always@(posedge CLK or `BSV_RESET_EDGE RST_N)
  if (RST_N == `BSV_RESET_VALUE)
    begin
      ff_memory_response_rv <= `BSV_ASSIGNMENT_DELAY
	  { 1'd0,
	    72'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */  };
    end
  else
    begin
      if (ff_memory_response_rv_EN)
	ff_memory_response_rv <= `BSV_ASSIGNMENT_DELAY
	    ff_memory_response_rv_D_IN;
    end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    ff_memory_response_rv = 73'h0AAAAAAAAAAAAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction)
	begin
	  TASK_testplusargs___d10 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction)
	begin
	  TASK_testplusargs___d11 = $test$plusargs("mstage4");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction)
	begin
	  TASK_testplusargs___d12 = $test$plusargs("l0");
	  #0;
	end
    TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d26 =
	(TASK_testplusargs___d10 ||
	 TASK_testplusargs___d11 && TASK_testplusargs___d12) &&
	rx_common_from_stage3_first_x[0];
    TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d29 =
	(TASK_testplusargs___d10 ||
	 TASK_testplusargs___d11 && TASK_testplusargs___d12) &&
	!rx_common_from_stage3_first_x[0];
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction)
	begin
	  v__h1603 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  (TASK_testplusargs___d10 ||
	   TASK_testplusargs___d11 && TASK_testplusargs___d12))
	$write("[%10d", v__h1603, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  (TASK_testplusargs___d10 ||
	   TASK_testplusargs___d11 && TASK_testplusargs___d12))
	$write("core:%2d ", hartid, "STAGE4: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  (TASK_testplusargs___d10 ||
	   TASK_testplusargs___d11 && TASK_testplusargs___d12))
	$write("Stage4Common { ", "pc: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  (TASK_testplusargs___d10 ||
	   TASK_testplusargs___d11 && TASK_testplusargs___d12))
	$write("'h%h", rx_common_from_stage3_first_x[70:7]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  (TASK_testplusargs___d10 ||
	   TASK_testplusargs___d11 && TASK_testplusargs___d12))
	$write(", ", "rd: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  (TASK_testplusargs___d10 ||
	   TASK_testplusargs___d11 && TASK_testplusargs___d12))
	$write("'h%h", rx_common_from_stage3_first_x[6:2]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  (TASK_testplusargs___d10 ||
	   TASK_testplusargs___d11 && TASK_testplusargs___d12))
	$write(", ", "epochs: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  (TASK_testplusargs___d10 ||
	   TASK_testplusargs___d11 && TASK_testplusargs___d12))
	$write("'h%h", rx_common_from_stage3_first_x[1]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  (TASK_testplusargs___d10 ||
	   TASK_testplusargs___d11 && TASK_testplusargs___d12))
	$write(", ", "rdtype: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d26)
	$write("FRF");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d29)
	$write("IRF");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  (TASK_testplusargs___d10 ||
	   TASK_testplusargs___d11 && TASK_testplusargs___d12))
	$write(" }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  (TASK_testplusargs___d10 ||
	   TASK_testplusargs___d11 && TASK_testplusargs___d12))
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction)
	begin
	  TASK_testplusargs___d30 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction)
	begin
	  TASK_testplusargs___d31 = $test$plusargs("mstage4");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction)
	begin
	  TASK_testplusargs___d32 = $test$plusargs("l0");
	  #0;
	end
    TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d41 =
	(TASK_testplusargs___d30 ||
	 TASK_testplusargs___d31 && TASK_testplusargs___d32) &&
	rx_type_w_data_wget[82:81] == 2'd0;
    TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d44 =
	(TASK_testplusargs___d30 ||
	 TASK_testplusargs___d31 && TASK_testplusargs___d32) &&
	rx_type_w_data_wget[82:81] == 2'd1;
    TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d47 =
	(TASK_testplusargs___d30 ||
	 TASK_testplusargs___d31 && TASK_testplusargs___d32) &&
	rx_type_w_data_wget[82:81] == 2'd2;
    TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d57 =
	(TASK_testplusargs___d30 ||
	 TASK_testplusargs___d31 && TASK_testplusargs___d32) &&
	rx_type_w_data_wget[82:81] != 2'd0 &&
	rx_type_w_data_wget[82:81] != 2'd1 &&
	rx_type_w_data_wget[82:81] != 2'd2;
    TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d71 =
	(TASK_testplusargs___d30 ||
	 TASK_testplusargs___d31 && TASK_testplusargs___d32) &&
	rx_type_w_data_wget[82:81] != 2'd0 &&
	rx_type_w_data_wget[82:81] != 2'd1;
    TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d76 =
	(TASK_testplusargs___d30 ||
	 TASK_testplusargs___d31 && TASK_testplusargs___d32) &&
	rx_type_w_data_wget[82:81] != 2'd0;
    TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d91 =
	(TASK_testplusargs___d30 ||
	 TASK_testplusargs___d31 && TASK_testplusargs___d32) &&
	rx_type_w_data_wget[82:81] == 2'd0 &&
	IF_rx_type_w_data_whas__6_THEN_IF_rx_type_w_da_ETC___d88 == 3'd0;
    TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d94 =
	(TASK_testplusargs___d30 ||
	 TASK_testplusargs___d31 && TASK_testplusargs___d32) &&
	rx_type_w_data_wget[82:81] == 2'd0 &&
	IF_rx_type_w_data_whas__6_THEN_IF_rx_type_w_da_ETC___d88 == 3'd1;
    TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d97 =
	(TASK_testplusargs___d30 ||
	 TASK_testplusargs___d31 && TASK_testplusargs___d32) &&
	rx_type_w_data_wget[82:81] == 2'd0 &&
	IF_rx_type_w_data_whas__6_THEN_IF_rx_type_w_da_ETC___d88 == 3'd2;
    TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d100 =
	(TASK_testplusargs___d30 ||
	 TASK_testplusargs___d31 && TASK_testplusargs___d32) &&
	rx_type_w_data_wget[82:81] == 2'd0 &&
	IF_rx_type_w_data_whas__6_THEN_IF_rx_type_w_da_ETC___d88 == 3'd3;
    TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d103 =
	(TASK_testplusargs___d30 ||
	 TASK_testplusargs___d31 && TASK_testplusargs___d32) &&
	rx_type_w_data_wget[82:81] == 2'd0 &&
	IF_rx_type_w_data_whas__6_THEN_IF_rx_type_w_da_ETC___d88 == 3'd4;
    TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d114 =
	(TASK_testplusargs___d30 ||
	 TASK_testplusargs___d31 && TASK_testplusargs___d32) &&
	rx_type_w_data_wget[82:81] == 2'd0 &&
	IF_rx_type_w_data_whas__6_THEN_IF_rx_type_w_da_ETC___d88 != 3'd0 &&
	IF_rx_type_w_data_whas__6_THEN_IF_rx_type_w_da_ETC___d88 != 3'd1 &&
	IF_rx_type_w_data_whas__6_THEN_IF_rx_type_w_da_ETC___d88 != 3'd2 &&
	IF_rx_type_w_data_whas__6_THEN_IF_rx_type_w_da_ETC___d88 != 3'd3 &&
	IF_rx_type_w_data_whas__6_THEN_IF_rx_type_w_da_ETC___d88 != 3'd4;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction)
	begin
	  v__h1850 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  (TASK_testplusargs___d30 ||
	   TASK_testplusargs___d31 && TASK_testplusargs___d32))
	$write("[%10d", v__h1850, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  (TASK_testplusargs___d30 ||
	   TASK_testplusargs___d31 && TASK_testplusargs___d32))
	$write("core:%2d ", hartid, "STAGE4: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d41)
	$write("tagged Memory ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d44)
	$write("tagged Trap ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d47)
	$write("tagged Regular ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d57)
	$write("tagged System ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d41)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d44)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d47)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d57)
	$write("Stage4System { ", "rs1_imm: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d41)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d44)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d47)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d57)
	$write("'h%h", rx_type_w_data_wget[80:17]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d41)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d44)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d47)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d57)
	$write(", ", "lpc: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d41)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d44)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d47)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d57)
	$write("'h%h", rx_type_w_data_wget[16:15]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d41)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d44)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d47)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d57)
	$write(", ", "csr_address: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d41)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d44)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d47)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d57)
	$write("'h%h", rx_type_w_data_wget[14:3]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d41)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d44)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d47)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d57)
	$write(", ", "funct3: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d41)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d44)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d47)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d57)
	$write("'h%h", rx_type_w_data_wget[2:0], " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d41)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d44)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d47)
	$write("Stage4Regular { ", "rdvalue: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d57)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d41)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d44)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d47)
	$write("'h%h", rx_type_w_data_wget[68:5]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d57)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d41)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d44)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d47)
	$write(", ", "fflags: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d57)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d41)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d44)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d47)
	$write("'h%h", rx_type_w_data_wget[4:0], " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d57)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d41)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d44)
	$write("Stage4Trap { ", "cause: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d71)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d41)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d44)
	$write("'h%h", rx_type_w_data_wget[69:64]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d71)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d41)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d44)
	$write(", ", "badaddr: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d71)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d41)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d44)
	$write("'h%h", rx_type_w_data_wget[63:0], " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d71)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d41)
	$write("Stage4Memory { ", "memaccess: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d76)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d91)
	$write("Load");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d94)
	$write("Store");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d97)
	$write("Fence");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d100)
	$write("FenceI");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d103)
	$write("Atomic");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d114)
	$write("SFence");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d76)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d41)
	$write(", ", "nanboxing: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d76)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d41)
	$write("'h%h", rx_type_w_data_wget[0], " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d76)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  (TASK_testplusargs___d30 ||
	   TASK_testplusargs___d31 && TASK_testplusargs___d32))
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  rx_type_w_data_wget[82:81] == 2'd0 &&
	  ff_memory_response_rv_port1__read[72])
	begin
	  TASK_testplusargs___d121 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  rx_type_w_data_wget[82:81] == 2'd0 &&
	  ff_memory_response_rv_port1__read[72])
	begin
	  TASK_testplusargs___d122 = $test$plusargs("mstage4");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  rx_type_w_data_wget[82:81] == 2'd0 &&
	  ff_memory_response_rv_port1__read[72])
	begin
	  TASK_testplusargs___d123 = $test$plusargs("l0");
	  #0;
	end
    ff_memory_response_rv_port1__read__17_BIT_72_1_ETC___d126 =
	ff_memory_response_rv_port1__read[72] &&
	(TASK_testplusargs___d121 ||
	 TASK_testplusargs___d122 && TASK_testplusargs___d123);
    TASK_testplusargs_21_OR_TASK_testplusargs_22_A_ETC___d132 =
	(TASK_testplusargs___d121 ||
	 TASK_testplusargs___d122 && TASK_testplusargs___d123) &&
	ff_memory_response_rv_port1__read[7];
    TASK_testplusargs_21_OR_TASK_testplusargs_22_A_ETC___d136 =
	(TASK_testplusargs___d121 ||
	 TASK_testplusargs___d122 && TASK_testplusargs___d123) &&
	!ff_memory_response_rv_port1__read[7];
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  rx_type_w_data_wget[82:81] == 2'd0 &&
	  ff_memory_response_rv_port1__read[72])
	begin
	  v__h2413 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  rx_type_w_data_wget[82:81] == 2'd0 &&
	  ff_memory_response_rv_port1__read__17_BIT_72_1_ETC___d126)
	$write("[%10d", v__h2413, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  rx_type_w_data_wget[82:81] == 2'd0 &&
	  ff_memory_response_rv_port1__read__17_BIT_72_1_ETC___d126)
	$write("core:%2d ", hartid, "STAGE4: Received: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  rx_type_w_data_wget[82:81] == 2'd0 &&
	  ff_memory_response_rv_port1__read__17_BIT_72_1_ETC___d126)
	$write("DMem_core_response { ", "word: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  rx_type_w_data_wget[82:81] == 2'd0 &&
	  ff_memory_response_rv_port1__read__17_BIT_72_1_ETC___d126)
	$write("'h%h", x_first_word__h2498);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  rx_type_w_data_wget[82:81] == 2'd0 &&
	  ff_memory_response_rv_port1__read__17_BIT_72_1_ETC___d126)
	$write(", ", "trap: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  rx_type_w_data_wget[82:81] == 2'd0 &&
	  ff_memory_response_rv_port1__read[72] &&
	  TASK_testplusargs_21_OR_TASK_testplusargs_22_A_ETC___d132)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  rx_type_w_data_wget[82:81] == 2'd0 &&
	  ff_memory_response_rv_port1__read[72] &&
	  TASK_testplusargs_21_OR_TASK_testplusargs_22_A_ETC___d136)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  rx_type_w_data_wget[82:81] == 2'd0 &&
	  ff_memory_response_rv_port1__read__17_BIT_72_1_ETC___d126)
	$write(", ", "cause: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  rx_type_w_data_wget[82:81] == 2'd0 &&
	  ff_memory_response_rv_port1__read__17_BIT_72_1_ETC___d126)
	$write("'h%h", x_first_cause__h2500);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  rx_type_w_data_wget[82:81] == 2'd0 &&
	  ff_memory_response_rv_port1__read__17_BIT_72_1_ETC___d126)
	$write(", ", "epochs: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  rx_type_w_data_wget[82:81] == 2'd0 &&
	  ff_memory_response_rv_port1__read__17_BIT_72_1_ETC___d126)
	$write("'h%h", x_first_epochs__h2501, " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  rx_type_w_data_wget[82:81] == 2'd0 &&
	  ff_memory_response_rv_port1__read__17_BIT_72_1_ETC___d126)
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  rx_type_w_data_wget[82:81] == 2'd0 &&
	  ff_memory_response_rv_port1__read[72] &&
	  !IF_rx_common_w_data_whas__6_THEN_rx_common_w_d_ETC___d143)
	begin
	  TASK_testplusargs___d147 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  rx_type_w_data_wget[82:81] == 2'd0 &&
	  ff_memory_response_rv_port1__read[72] &&
	  !IF_rx_common_w_data_whas__6_THEN_rx_common_w_d_ETC___d143)
	begin
	  TASK_testplusargs___d148 = $test$plusargs("mstage4");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  rx_type_w_data_wget[82:81] == 2'd0 &&
	  ff_memory_response_rv_port1__read[72] &&
	  !IF_rx_common_w_data_whas__6_THEN_rx_common_w_d_ETC___d143)
	begin
	  TASK_testplusargs___d149 = $test$plusargs("l0");
	  #0;
	end
    NOT_IF_rx_common_w_data_whas__6_THEN_rx_common_ETC___d152 =
	!IF_rx_common_w_data_whas__6_THEN_rx_common_w_d_ETC___d143 &&
	(TASK_testplusargs___d147 ||
	 TASK_testplusargs___d148 && TASK_testplusargs___d149);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  rx_type_w_data_wget[82:81] == 2'd0 &&
	  ff_memory_response_rv_port1__read[72] &&
	  !IF_rx_common_w_data_whas__6_THEN_rx_common_w_d_ETC___d143)
	begin
	  v__h2669 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  rx_type_w_data_wget[82:81] == 2'd0 &&
	  ff_memory_response_rv_port1__read[72] &&
	  NOT_IF_rx_common_w_data_whas__6_THEN_rx_common_ETC___d152)
	$write("[%10d", v__h2669, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  rx_type_w_data_wget[82:81] == 2'd0 &&
	  ff_memory_response_rv_port1__read[72] &&
	  NOT_IF_rx_common_w_data_whas__6_THEN_rx_common_ETC___d152)
	$write("core:%2d ",
	       hartid,
	       "STAGE4: Instruction and Response Epochs do not match");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  rx_type_w_data_wget[82:81] == 2'd0 &&
	  ff_memory_response_rv_port1__read[72] &&
	  NOT_IF_rx_common_w_data_whas__6_THEN_rx_common_ETC___d152)
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  rx_type_w_data_wget[82:81] == 2'd0 &&
	  !ff_memory_response_rv_port1__read[72])
	begin
	  TASK_testplusargs___d158 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  rx_type_w_data_wget[82:81] == 2'd0 &&
	  !ff_memory_response_rv_port1__read[72])
	begin
	  TASK_testplusargs___d159 = $test$plusargs("mstage4");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  rx_type_w_data_wget[82:81] == 2'd0 &&
	  !ff_memory_response_rv_port1__read[72])
	begin
	  TASK_testplusargs___d160 = $test$plusargs("l0");
	  #0;
	end
    NOT_ff_memory_response_rv_port1__read__17_BIT__ETC___d163 =
	!ff_memory_response_rv_port1__read[72] &&
	(TASK_testplusargs___d158 ||
	 TASK_testplusargs___d159 && TASK_testplusargs___d160);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  rx_type_w_data_wget[82:81] == 2'd0 &&
	  !ff_memory_response_rv_port1__read[72])
	begin
	  v__h2853 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  rx_type_w_data_wget[82:81] == 2'd0 &&
	  NOT_ff_memory_response_rv_port1__read__17_BIT__ETC___d163)
	$write("[%10d", v__h2853, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  rx_type_w_data_wget[82:81] == 2'd0 &&
	  NOT_ff_memory_response_rv_port1__read__17_BIT__ETC___d163)
	$write("core:%2d ", hartid, "STAGE4: Waiting for Memory Response");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  rx_type_w_data_wget[82:81] == 2'd0 &&
	  NOT_ff_memory_response_rv_port1__read__17_BIT__ETC___d163)
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  (rx_type_w_data_wget[82:81] != 2'd0 ||
	   ff_memory_response_rv_port1__read[72] &&
	   IF_rx_common_w_data_whas__6_THEN_rx_common_w_d_ETC___d143))
	begin
	  TASK_testplusargs___d168 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  (rx_type_w_data_wget[82:81] != 2'd0 ||
	   ff_memory_response_rv_port1__read[72] &&
	   IF_rx_common_w_data_whas__6_THEN_rx_common_w_d_ETC___d143))
	begin
	  TASK_testplusargs___d169 = $test$plusargs("mstage4");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  (rx_type_w_data_wget[82:81] != 2'd0 ||
	   ff_memory_response_rv_port1__read[72] &&
	   IF_rx_common_w_data_whas__6_THEN_rx_common_w_d_ETC___d143))
	begin
	  TASK_testplusargs___d170 = $test$plusargs("l0");
	  #0;
	end
    TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d179 =
	(TASK_testplusargs___d168 ||
	 TASK_testplusargs___d169 && TASK_testplusargs___d170) &&
	(rx_type_w_data_wget[82:81] == 2'd1 ||
	 rx_type_w_data_whas__6_AND_rx_type_w_data_wget_ETC___d177);
    TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d203 =
	(TASK_testplusargs___d168 ||
	 TASK_testplusargs___d169 && TASK_testplusargs___d170) &&
	NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d202;
    TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d212 =
	(TASK_testplusargs___d168 ||
	 TASK_testplusargs___d169 && TASK_testplusargs___d170) &&
	rx_type_w_data_wget[82:81] != 2'd1 &&
	NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d189 &&
	NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d210;
    TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d245 =
	(TASK_testplusargs___d168 ||
	 TASK_testplusargs___d169 && TASK_testplusargs___d170) &&
	rx_type_w_data_wget[82:81] != 2'd1 &&
	NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d189 &&
	NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d243;
    TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d254 =
	(TASK_testplusargs___d168 ||
	 TASK_testplusargs___d169 && TASK_testplusargs___d170) &&
	rx_type_w_data_wget[82:81] != 2'd1 &&
	NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d189 &&
	NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d252;
    TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d257 =
	(TASK_testplusargs___d168 ||
	 TASK_testplusargs___d169 && TASK_testplusargs___d170) &&
	rx_type_w_data_wget[82:81] != 2'd1 &&
	NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d189 &&
	(rx_type_w_data_wget[82:81] != 2'd0 ||
	 NOT_ff_memory_response_rv_port1__read__17_BIT__ETC___d194);
    TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d266 =
	(TASK_testplusargs___d168 ||
	 TASK_testplusargs___d169 && TASK_testplusargs___d170) &&
	rx_type_w_data_wget[82:81] != 2'd1 &&
	NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d189;
    NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d173 =
	(rx_type_w_data_wget[82:81] != 2'd0 ||
	 ff_memory_response_rv_port1__read[72] &&
	 IF_rx_common_w_data_whas__6_THEN_rx_common_w_d_ETC___d143) &&
	(TASK_testplusargs___d168 ||
	 TASK_testplusargs___d169 && TASK_testplusargs___d170);
    NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d180 =
	(rx_type_w_data_wget[82:81] != 2'd0 ||
	 ff_memory_response_rv_port1__read[72] &&
	 IF_rx_common_w_data_whas__6_THEN_rx_common_w_d_ETC___d143) &&
	TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d179;
    NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d204 =
	(rx_type_w_data_wget[82:81] != 2'd0 ||
	 ff_memory_response_rv_port1__read[72] &&
	 IF_rx_common_w_data_whas__6_THEN_rx_common_w_d_ETC___d143) &&
	TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d203;
    TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d186 =
	(TASK_testplusargs___d168 ||
	 TASK_testplusargs___d169 && TASK_testplusargs___d170) &&
	rx_type_w_data_wget[82:81] == 2'd0 &&
	ff_memory_response_rv_port1__read__17_BIT_72_1_ETC___d184;
    NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d213 =
	(rx_type_w_data_wget[82:81] != 2'd0 ||
	 ff_memory_response_rv_port1__read[72] &&
	 IF_rx_common_w_data_whas__6_THEN_rx_common_w_d_ETC___d143) &&
	TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d212;
    NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d246 =
	(rx_type_w_data_wget[82:81] != 2'd0 ||
	 ff_memory_response_rv_port1__read[72] &&
	 IF_rx_common_w_data_whas__6_THEN_rx_common_w_d_ETC___d143) &&
	TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d245;
    NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d255 =
	(rx_type_w_data_wget[82:81] != 2'd0 ||
	 ff_memory_response_rv_port1__read[72] &&
	 IF_rx_common_w_data_whas__6_THEN_rx_common_w_d_ETC___d143) &&
	TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d254;
    NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d267 =
	(rx_type_w_data_wget[82:81] != 2'd0 ||
	 ff_memory_response_rv_port1__read[72] &&
	 IF_rx_common_w_data_whas__6_THEN_rx_common_w_d_ETC___d143) &&
	TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d266;
    NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d258 =
	(rx_type_w_data_wget[82:81] != 2'd0 ||
	 ff_memory_response_rv_port1__read[72] &&
	 IF_rx_common_w_data_whas__6_THEN_rx_common_w_d_ETC___d143) &&
	TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d257;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  (rx_type_w_data_wget[82:81] != 2'd0 ||
	   ff_memory_response_rv_port1__read[72] &&
	   IF_rx_common_w_data_whas__6_THEN_rx_common_w_d_ETC___d143))
	begin
	  v__h3099 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d173)
	$write("[%10d", v__h3099, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d173)
	$write("core:%2d ", hartid, "STAGE4: Enquing: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d180)
	$write("tagged TRAP ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d186)
	$write("tagged STORE ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d204)
	$write("tagged REG ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d213)
	$write("tagged SYSTEM ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d180)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d186)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d204)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d213)
	$write("CommitSystem { ", "rs1: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d180)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d186)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d204)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d213)
	$write("'h%h", rx_type_w_data_wget[80:17]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d180)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d186)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d204)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d213)
	$write(", ", "lpc: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d180)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d186)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d204)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d213)
	$write("'h%h", rx_type_w_data_wget[16:15]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d180)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d186)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d204)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d213)
	$write(", ", "csraddr: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d180)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d186)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d204)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d213)
	$write("'h%h", rx_type_w_data_wget[14:3]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d180)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d186)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d204)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d213)
	$write(", ", "func3: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d180)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d186)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d204)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d213)
	$write("'h%h", rx_type_w_data_wget[2:0]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d180)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d186)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d204)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d213)
	$write(", ", "rd: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d180)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d186)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d204)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d213)
	$write("'h%h", rx_common_from_stage3_first_x[6:2], " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d180)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d186)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d204)
	$write("CommitRegular { ", "commitvalue: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d213)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d180)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d186)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d204)
	$write("'h%h",
	       (rx_type_w_data_wget[82:81] == 2'd2) ?
		 rx_type_w_data_wget[68:5] :
		 _theResult___word__h3371);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d213)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d180)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d186)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d204)
	$write(", ", "rd: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d213)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d180)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d186)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d204)
	$write("'h%h", rx_common_from_stage3_first_x[6:2]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d213)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d180)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d186)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d204)
	$write(", ", "fflags: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d213)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d180)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d186)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d204)
	$write("'h%h", value__h3496);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d213)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d180)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d186)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d204)
	$write(", ", "rdtype: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d213)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d180)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d186)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d246)
	$write("FRF");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d255)
	$write("IRF");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d213)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d180)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d186)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d204)
	$write(" }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d213)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d180)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d186)
	$write("CommitStore { ", "pc: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d258)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d180)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d186)
	$write("'h%h", rx_common_from_stage3_first_x[70:7]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d258)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d180)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d186)
	$write(", ", "commitvalue: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d258)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d180)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d186)
	$write("'h%h", value__h3359);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d258)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d180)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d186)
	$write(", ", "rd: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d258)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d180)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  TASK_testplusargs_68_OR_TASK_testplusargs_69_A_ETC___d186)
	$write("'h%h", rx_common_from_stage3_first_x[6:2], " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d258)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d180)
	$write("CommitTrap { ", "cause: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d267)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d180)
	$write("'h%h",
	       (rx_type_w_data_wget[82:81] == 2'd1) ?
		 rx_type_w_data_wget[69:64] :
		 x_first_cause__h2500);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d267)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d180)
	$write(", ", "badaddr: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d267)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d180)
	$write("'h%h", value__h3303);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d267)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d180)
	$write(", ", "pc: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d267)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d180)
	$write("'h%h", rx_common_from_stage3_first_x[70:7], " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d267)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_check_instruction &&
	  NOT_rx_type_w_data_whas__6_8_OR_NOT_rx_type_w__ETC___d173)
	$write("\n");
  end
  // synopsys translate_on
endmodule  // mkstage4

