//
// Generated by Bluespec Compiler (build a026416)
//
// On Sat Aug  8 15:33:47 IST 2020
//
//
// Ports:
// Name                         I/O  size props
// hasCSRPermission               O     1
// hasCSRPermission_address       I    12
// hasCSRPermission_write         I     1
// hasCSRPermission_prv           I     2
//
// Combinational paths from inputs to outputs:
//   (hasCSRPermission_address,
//    hasCSRPermission_write,
//    hasCSRPermission_prv) -> hasCSRPermission
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_hasCSRPermission(hasCSRPermission_address,
			       hasCSRPermission_write,
			       hasCSRPermission_prv,
			       hasCSRPermission);
  // value method hasCSRPermission
  input  [11 : 0] hasCSRPermission_address;
  input  hasCSRPermission_write;
  input  [1 : 0] hasCSRPermission_prv;
  output hasCSRPermission;

  // signals for module outputs
  wire hasCSRPermission;

  // remaining internal signals
  reg [1 : 0] CASE_hasCSRPermission_prv_1_hasCSRPermission_p_ETC__q1;

  // value method hasCSRPermission
  assign hasCSRPermission =
	     CASE_hasCSRPermission_prv_1_hasCSRPermission_p_ETC__q1 >=
	     hasCSRPermission_address[9:8] &&
	     (!hasCSRPermission_write ||
	      hasCSRPermission_address[11:10] != 2'b11) ;

  // remaining internal signals
  always@(hasCSRPermission_prv)
  begin
    case (hasCSRPermission_prv)
      2'd1, 2'd3:
	  CASE_hasCSRPermission_prv_1_hasCSRPermission_p_ETC__q1 =
	      hasCSRPermission_prv;
      default: CASE_hasCSRPermission_prv_1_hasCSRPermission_p_ETC__q1 = 2'd0;
    endcase
  end
endmodule  // module_hasCSRPermission

