//
// Generated by Bluespec Compiler (build a026416)
//
// On Sat Aug  8 15:33:47 IST 2020
//
//
// Ports:
// Name                         I/O  size props
// decoder_func_32                O    75
// decoder_func_32_inst           I    32
// decoder_func_32_csrs           I   199
// decoder_func_32_compressed     I     1
//
// Combinational paths from inputs to outputs:
//   (decoder_func_32_inst,
//    decoder_func_32_csrs,
//    decoder_func_32_compressed) -> decoder_func_32
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_decoder_func_32(decoder_func_32_inst,
			      decoder_func_32_csrs,
			      decoder_func_32_compressed,
			      decoder_func_32);
  // value method decoder_func_32
  input  [31 : 0] decoder_func_32_inst;
  input  [198 : 0] decoder_func_32_csrs;
  input  decoder_func_32_compressed;
  output [74 : 0] decoder_func_32;

  // signals for module outputs
  wire [74 : 0] decoder_func_32;

  // remaining internal signals
  reg [10 : 0] CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_de_ETC__q9;
  reg [7 : 0] CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_de_ETC__q10;
  reg [5 : 0] CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_0__ETC__q7,
	      _theResult_____9_snd__h3604,
	      _theResult_____9_snd__h3659;
  reg [3 : 0] CASE_decoder_func_32_inst_BITS_14_TO_12_0_1_1_1_6__q11,
	      CASE_decoder_func_32_inst_BITS_31_TO_7_0_6_0x2_ETC__q2,
	      CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q12,
	      CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q13,
	      CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_0__ETC__q8,
	      IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d360,
	      IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d373,
	      IF_decoder_func_32_inst_BITS_6_TO_2_EQ_0b11000_ETC___d696,
	      IF_decoder_func_32_inst_BITS_6_TO_5_20_EQ_0b0__ETC___d396,
	      fn___1__h7544,
	      fn___1__h7606;
  reg [1 : 0] CASE_decoder_func_32_csrs_BITS_198_TO_197_1_de_ETC__q1;
  reg CASE_decoder_func_32_inst_BITS_14_TO_12_0_NOT__ETC__q4,
      CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_NOT__ETC__q3,
      CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q5,
      CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q6,
      IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d200,
      IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d262,
      IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d530,
      IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b1_ETC___d273,
      IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b1_ETC___d537,
      IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d161,
      IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d214,
      IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d277,
      IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d503,
      IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d541,
      IF_decoder_func_32_inst_BITS_6_TO_5_20_EQ_0b0__ETC___d348,
      IF_decoder_func_32_inst_BITS_6_TO_5_20_EQ_0b0__ETC___d588;
  wire [47 : 0] IF_NOT_decoder_func_32_inst_BITS_1_TO_0_17_EQ__ETC___d710;
  wire [42 : 0] IF_NOT_decoder_func_32_inst_BITS_6_TO_2_EQ_0b1_ETC___d709;
  wire [31 : 0] immediate_value___1__h4538,
		immediate_value__h51,
		instr_meta_immediate__h1053;
  wire [11 : 0] NOT_decoder_func_32_inst_BITS_6_TO_2_EQ_0b1011_ETC___d618;
  wire [10 : 0] bit20_30__h49;
  wire [7 : 0] bit12_19__h48;
  wire [6 : 0] instr_meta_funct__h1054, temp1___1__h7267, temp1__h80;
  wire [5 : 0] _theResult_____9_snd__h3632, trapcause___1__h3654, x__h7270;
  wire [4 : 0] x__h21, x__h213, x__h482, x__h540;
  wire [3 : 0] IF_NOT_decoder_func_32_inst_BIT_26_20_21_AND_N_ETC___d374,
	       IF_NOT_decoder_func_32_inst_BIT_26_20_21_AND_N_ETC___d375,
	       IF_decoder_func_32_csrs_BIT_111_96_AND_decoder_ETC___d365,
	       IF_decoder_func_32_csrs_BIT_111_96_AND_decoder_ETC___d367,
	       IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d388,
	       IF_decoder_func_32_inst_BITS_6_TO_5_20_EQ_0b10_ETC___d693,
	       IF_decoder_func_32_inst_BIT_30_1_THEN_0b1011_E_ETC___d671,
	       fn___1__h7505,
	       fn___1__h7527;
  wire IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d340,
       IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d580,
       IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d591,
       IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_1_3_ETC___d147,
       IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_1_3_ETC___d207,
       IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_2_ETC___d238,
       IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_2_ETC___d511,
       NOT_decoder_func_32_csrs_BIT_111_96_87_OR_NOT__ETC___d497,
       NOT_decoder_func_32_inst_BITS_6_TO_5_20_EQ_0b1_ETC___d585,
       NOT_decoder_func_32_inst_BIT_26_20_21_AND_NOT__ETC___d228,
       address_valid___d338,
       bit31__h50,
       decoder_func_32_csrs_BIT_111_96_AND_decoder_fu_ETC___d208,
       decoder_func_32_csrs_BIT_99_69_AND_decoder_fun_ETC___d195,
       decoder_func_32_inst_BITS_14_TO_12_3_ULE_3___d202,
       decoder_func_32_inst_BITS_14_TO_12_3_ULT_2___d246,
       decoder_func_32_inst_BITS_14_TO_12_3_ULT_3___d244,
       decoder_func_32_inst_BITS_14_TO_12_3_ULT_4___d163,
       decoder_func_32_inst_BITS_1_TO_0_17_EQ_0b11_18_ETC___d594,
       decoder_func_32_inst_BITS_6_TO_5_20_EQ_0b11_78_ETC___d345,
       decoder_func_32_inst_BIT_25_22_EQ_INV_decoder__ETC___d269,
       decoder_func_32_inst_BIT_26_20_OR_decoder_func_ETC___d508,
       decoder_func_32_inst_BIT_27_84_OR_decoder_func_ETC___d686,
       valid_csr_access___d335;

  // value method decoder_func_32
  assign decoder_func_32 =
	     { x__h21,
	       x__h213,
	       x__h482,
	       x__h540,
	       (decoder_func_32_inst[6:4] == 3'b100 ||
		decoder_func_32_inst[6:4] == 3'b101 &&
		decoder_func_32_inst[31:28] != 4'b1101 &&
		decoder_func_32_inst[31:28] != 4'b1111) ?
		 2'd2 :
		 ((decoder_func_32_inst[6:2] != 5'b11011 &&
		   decoder_func_32_inst[6:2] != 5'b11001 &&
		   decoder_func_32_inst[6:2] != 5'b00101 &&
		   decoder_func_32_inst[6:4] != 3'b100 &&
		   (decoder_func_32_inst[6:4] != 3'b101 ||
		    decoder_func_32_inst[31:28] == 4'b1101 ||
		    decoder_func_32_inst[31:28] == 4'b1111)) ?
		    2'd0 :
		    2'd1),
	       (decoder_func_32_inst[6:4] == 3'b101 &&
		!decoder_func_32_inst[30] ||
		decoder_func_32_inst[6:2] == 5'b01001 ||
		decoder_func_32_inst[6:4] == 3'b100) ?
		 3'd4 :
		 ((decoder_func_32_inst[6:2] != 5'b11001 &&
		   decoder_func_32_inst[6:2] != 5'b11011 &&
		   decoder_func_32_inst[6:2] != 5'b00011 &&
		   decoder_func_32_inst[6:4] != 3'b001 &&
		   decoder_func_32_inst[6:2] != 5'b01101 &&
		   (decoder_func_32_inst[6:4] != 3'b101 ||
		    decoder_func_32_inst[30]) &&
		   decoder_func_32_inst[6:2] != 5'b01001 &&
		   decoder_func_32_inst[6:4] != 3'b100) ?
		    3'd0 :
		    ((decoder_func_32_inst[6:4] == 3'b001 ||
		      decoder_func_32_inst[6:2] == 5'b01101) ?
		       3'd1 :
		       (((decoder_func_32_inst[6:2] == 5'b11001 ||
			  decoder_func_32_inst[6:2] == 5'b11011 ||
			  decoder_func_32_inst[6:2] == 5'b00011) &&
			 !decoder_func_32_compressed) ?
			  3'd2 :
			  3'd3))),
	       decoder_func_32_inst[6:4] == 3'b100,
	       decoder_func_32_inst[6:2] == 5'b00001 ||
	       decoder_func_32_inst[6:4] == 3'b101 &&
	       decoder_func_32_inst[31:28] != 4'b1010 &&
	       decoder_func_32_inst[31:28] != 4'b1100 &&
	       decoder_func_32_inst[31:28] != 4'b1110 ||
	       decoder_func_32_inst[6:4] == 3'b100,
	       IF_NOT_decoder_func_32_inst_BITS_1_TO_0_17_EQ__ETC___d710 } ;

  // remaining internal signals
  module_valid_csr_access instance_valid_csr_access_1(.valid_csr_access_csr_addr(decoder_func_32_inst[31:20]),
						      .valid_csr_access_operand(decoder_func_32_inst[19:15]),
						      .valid_csr_access_operation(decoder_func_32_inst[13:12]),
						      .valid_csr_access_tvm(decoder_func_32_csrs[55]),
						      .valid_csr_access_prv(CASE_decoder_func_32_csrs_BITS_198_TO_197_1_de_ETC__q1),
						      .valid_csr_access(valid_csr_access___d335));
  module_address_valid instance_address_valid_0(.address_valid_addr(decoder_func_32_inst[31:20]),
						.address_valid_misa(decoder_func_32_csrs[124:99]),
						.address_valid(address_valid___d338));
  assign IF_NOT_decoder_func_32_inst_BITS_1_TO_0_17_EQ__ETC___d710 =
	     { (decoder_func_32_inst[1:0] != 2'b11 &&
		IF_decoder_func_32_inst_BITS_6_TO_5_20_EQ_0b0__ETC___d348) ?
		 4'd6 :
		 IF_decoder_func_32_inst_BITS_6_TO_5_20_EQ_0b0__ETC___d396,
	       IF_NOT_decoder_func_32_inst_BITS_6_TO_2_EQ_0b1_ETC___d709,
	       1'd0 } ;
  assign IF_NOT_decoder_func_32_inst_BITS_6_TO_2_EQ_0b1_ETC___d709 =
	     { ((decoder_func_32_inst[6:2] != 5'b11100 ||
		 decoder_func_32_inst[31:25] != 7'b0001001 ||
		 decoder_func_32_inst[14:12] != 3'd0) &&
		decoder_func_32_inst[6:2] != 5'b01011 &&
		(!decoder_func_32_inst[12] ||
		 decoder_func_32_inst[6:2] != 5'b00011) &&
		(decoder_func_32_inst[12] ||
		 decoder_func_32_inst[6:2] != 5'b00011) &&
		decoder_func_32_inst[6:2] != 5'b01000 &&
		(decoder_func_32_inst[6:2] != 5'b01001 ||
		 !decoder_func_32_csrs[104])) ?
		 3'd0 :
		 ((decoder_func_32_inst[6:2] == 5'b01000 ||
		   decoder_func_32_inst[6:2] == 5'b01001 &&
		   decoder_func_32_csrs[104]) ?
		    3'd1 :
		    ((!decoder_func_32_inst[12] &&
		      decoder_func_32_inst[6:2] == 5'b00011) ?
		       3'd3 :
		       ((decoder_func_32_inst[12] &&
			 decoder_func_32_inst[6:2] == 5'b00011) ?
			  3'd4 :
			  ((decoder_func_32_inst[6:2] == 5'b01011) ?
			     3'd2 :
			     3'd5)))),
	       instr_meta_immediate__h1053,
	       instr_meta_funct__h1054,
	       decoder_func_32_inst[6:2] == 5'b00011 ||
	       decoder_func_32_inst_BITS_1_TO_0_17_EQ_0b11_18_ETC___d594 ||
	       decoder_func_32_inst[6:2] == 5'b11100 &&
	       decoder_func_32_inst[31:25] == 7'b0001001 &&
	       decoder_func_32_inst[14:12] == 3'd0 } ;
  assign IF_NOT_decoder_func_32_inst_BIT_26_20_21_AND_N_ETC___d374 =
	     (NOT_decoder_func_32_inst_BIT_26_20_21_AND_NOT__ETC___d228 &&
	      IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_2_ETC___d238) ?
	       4'd8 :
	       4'd6 ;
  assign IF_NOT_decoder_func_32_inst_BIT_26_20_21_AND_N_ETC___d375 =
	     (NOT_decoder_func_32_inst_BIT_26_20_21_AND_NOT__ETC___d228 &&
	      (IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d262 ||
	       IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b1_ETC___d273)) ?
	       4'd8 :
	       4'd6 ;
  assign IF_decoder_func_32_csrs_BIT_111_96_AND_decoder_ETC___d365 =
	     (decoder_func_32_csrs[111] &&
	      decoder_func_32_inst[31:25] == 7'd1) ?
	       4'd9 :
	       (IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d200 ?
		  4'd0 :
		  4'd6) ;
  assign IF_decoder_func_32_csrs_BIT_111_96_AND_decoder_ETC___d367 =
	     (decoder_func_32_csrs[111] &&
	      decoder_func_32_inst[31:25] == 7'd1 &&
	      (decoder_func_32_inst[14:12] == 3'd0 ||
	       !decoder_func_32_inst_BITS_14_TO_12_3_ULE_3___d202)) ?
	       4'd9 :
	       (IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_1_3_ETC___d207 ?
		  4'd0 :
		  4'd6) ;
  assign IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d340 =
	     (decoder_func_32_inst[14:12] == 3'd0) ?
	       decoder_func_32_inst[31:20] == 12'h002 &&
	       decoder_func_32_inst[19:15] == 5'd0 &&
	       decoder_func_32_inst[11:7] == 5'd0 &&
	       decoder_func_32_csrs[112] ||
	       decoder_func_32_inst[31:20] == 12'h102 &&
	       decoder_func_32_inst[19:15] == 5'd0 &&
	       decoder_func_32_inst[11:7] == 5'd0 &&
	       decoder_func_32_csrs[117] &&
	       (decoder_func_32_csrs[198:197] == 2'd3 ||
		decoder_func_32_csrs[198:197] == 2'd1 &&
		!decoder_func_32_csrs[57]) ||
	       decoder_func_32_inst[31:20] == 12'h302 &&
	       decoder_func_32_inst[19:15] == 5'd0 &&
	       decoder_func_32_inst[11:7] == 5'd0 &&
	       decoder_func_32_csrs[198:197] == 2'd3 ||
	       ((decoder_func_32_inst[31:20] == 12'h105 &&
		 decoder_func_32_inst[19:15] == 5'd0 &&
		 decoder_func_32_inst[11:7] == 5'd0) ?
		  !decoder_func_32_csrs[56] ||
		  decoder_func_32_csrs[198:197] == 2'd3 :
		  decoder_func_32_inst[31:25] == 7'b0001001 &&
		  decoder_func_32_inst[11:7] == 5'd0 &&
		  (!decoder_func_32_csrs[55] ||
		   decoder_func_32_csrs[198:197] == 2'd3)) :
	       decoder_func_32_inst[14:12] != 3'd4 &&
	       valid_csr_access___d335 &&
	       address_valid___d338 ;
  assign IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d388 =
	     (decoder_func_32_inst[14:12] == 3'd0) ?
	       CASE_decoder_func_32_inst_BITS_31_TO_7_0_6_0x2_ETC__q2 :
	       ((decoder_func_32_inst[14:12] != 3'd4 &&
		 valid_csr_access___d335 &&
		 address_valid___d338) ?
		  4'd5 :
		  4'd6) ;
  assign IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d580 =
	     (decoder_func_32_inst[14:12] == 3'd0) ?
	       (decoder_func_32_inst[31:20] != 12'h002 ||
		decoder_func_32_inst[19:15] != 5'd0 ||
		decoder_func_32_inst[11:7] != 5'd0 ||
		!decoder_func_32_csrs[112]) &&
	       (decoder_func_32_inst[31:20] != 12'h102 ||
		decoder_func_32_inst[19:15] != 5'd0 ||
		decoder_func_32_inst[11:7] != 5'd0 ||
		!decoder_func_32_csrs[117] ||
		decoder_func_32_csrs[198:197] != 2'd3 &&
		(decoder_func_32_csrs[198:197] != 2'd1 ||
		 decoder_func_32_csrs[57])) &&
	       (decoder_func_32_inst[31:20] != 12'h302 ||
		decoder_func_32_inst[19:15] != 5'd0 ||
		decoder_func_32_inst[11:7] != 5'd0 ||
		decoder_func_32_csrs[198:197] != 2'd3) &&
	       ((decoder_func_32_inst[31:20] == 12'h105 &&
		 decoder_func_32_inst[19:15] == 5'd0 &&
		 decoder_func_32_inst[11:7] == 5'd0) ?
		  decoder_func_32_csrs[56] &&
		  decoder_func_32_csrs[198:197] != 2'd3 :
		  decoder_func_32_inst[31:25] != 7'b0001001 ||
		  decoder_func_32_inst[11:7] != 5'd0 ||
		  decoder_func_32_csrs[55] &&
		  decoder_func_32_csrs[198:197] != 2'd3) :
	       decoder_func_32_inst[14:12] == 3'd4 ||
	       !valid_csr_access___d335 ||
	       !address_valid___d338 ;
  assign IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d591 =
	     (decoder_func_32_inst[14:12] == 3'd0) ?
	       decoder_func_32_inst[31:20] == 12'h002 &&
	       decoder_func_32_inst[19:15] == 5'd0 &&
	       decoder_func_32_inst[11:7] == 5'd0 &&
	       decoder_func_32_csrs[112] ||
	       decoder_func_32_inst[31:20] == 12'h102 &&
	       decoder_func_32_inst[19:15] == 5'd0 &&
	       decoder_func_32_inst[11:7] == 5'd0 &&
	       decoder_func_32_csrs[117] &&
	       (decoder_func_32_csrs[198:197] == 2'd3 ||
		decoder_func_32_csrs[198:197] == 2'd1 &&
		!decoder_func_32_csrs[57]) ||
	       decoder_func_32_inst[31:20] == 12'h302 &&
	       decoder_func_32_inst[19:15] == 5'd0 &&
	       decoder_func_32_inst[11:7] == 5'd0 &&
	       decoder_func_32_csrs[198:197] == 2'd3 :
	       decoder_func_32_inst[14:12] != 3'd4 &&
	       valid_csr_access___d335 &&
	       address_valid___d338 ;
  assign IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_1_3_ETC___d147 =
	     (decoder_func_32_inst[14:12] == 3'd1) ?
	       decoder_func_32_inst[31:26] == 6'd0 :
	       decoder_func_32_inst[14:12] != 3'd5 ||
	       decoder_func_32_inst[31:26] == 6'd0 ||
	       decoder_func_32_inst[31:26] == 6'b010000 ;
  assign IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_1_3_ETC___d207 =
	     (decoder_func_32_inst[14:12] == 3'd1) ?
	       decoder_func_32_inst[31:25] == 7'b0 :
	       (decoder_func_32_inst[14:12] == 3'd0 ||
		decoder_func_32_inst[14:12] == 3'd5) &&
	       (decoder_func_32_inst[31:25] == 7'b0 ||
		decoder_func_32_inst[31:25] == 7'b0100000) ;
  assign IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_2_ETC___d238 =
	     (decoder_func_32_inst[14:12] == 3'd7) ?
	       decoder_func_32_csrs[34:32] != 3'b101 &&
	       decoder_func_32_csrs[34:32] != 3'b110 :
	       decoder_func_32_inst[14:12] != 3'd5 &&
	       decoder_func_32_inst[14:12] != 3'b110 ;
  assign IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_2_ETC___d511 =
	     (decoder_func_32_inst[14:12] == 3'd7) ?
	       decoder_func_32_csrs[34:32] == 3'b101 ||
	       decoder_func_32_csrs[34:32] == 3'b110 :
	       decoder_func_32_inst[14:12] == 3'd5 ||
	       decoder_func_32_inst[14:12] == 3'b110 ;
  assign IF_decoder_func_32_inst_BITS_6_TO_5_20_EQ_0b10_ETC___d693 =
	     (decoder_func_32_inst[6:5] == 2'b10 &&
	      decoder_func_32_csrs[104] | decoder_func_32_csrs[102]) ?
	       decoder_func_32_inst[5:2] :
	       ((decoder_func_32_inst[6:2] == 5'b01011) ?
		  { decoder_func_32_inst_BIT_27_84_OR_decoder_func_ETC___d686 ?
		      decoder_func_32_inst[29:27] :
		      decoder_func_32_inst[31:29],
		    decoder_func_32_inst_BIT_27_84_OR_decoder_func_ETC___d686 ||
		    decoder_func_32_inst[27] } :
		  4'd0) ;
  assign IF_decoder_func_32_inst_BIT_30_1_THEN_0b1011_E_ETC___d671 =
	     decoder_func_32_inst[30] ? 4'b1011 : 4'b0101 ;
  assign NOT_decoder_func_32_csrs_BIT_111_96_87_OR_NOT__ETC___d497 =
	     (!decoder_func_32_csrs[111] ||
	      decoder_func_32_inst[31:25] != 7'd1 ||
	      decoder_func_32_inst[14:12] != 3'd0 &&
	      decoder_func_32_inst_BITS_14_TO_12_3_ULE_3___d202) &&
	     ((decoder_func_32_inst[14:12] == 3'd1) ?
		decoder_func_32_inst[31:25] != 7'b0 :
		decoder_func_32_inst[14:12] != 3'd0 &&
		decoder_func_32_inst[14:12] != 3'd5 ||
		decoder_func_32_inst[31:25] != 7'b0 &&
		decoder_func_32_inst[31:25] != 7'b0100000) ;
  assign NOT_decoder_func_32_inst_BITS_6_TO_2_EQ_0b1011_ETC___d618 =
	     { decoder_func_32_inst[6:2] != 5'b01011 &&
	       ((decoder_func_32_inst[6:2] == 5'b11000) ?
		  decoder_func_32_inst[7] :
		  decoder_func_32_inst[6:2] != 5'b01101 &&
		  decoder_func_32_inst[6:2] != 5'b00101 &&
		  ((decoder_func_32_inst[6:2] == 5'b11011) ?
		     decoder_func_32_inst[20] :
		     decoder_func_32_inst[31])),
	       CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_0__ETC__q7,
	       (decoder_func_32_inst[6:2] == 5'b01011) ?
		 4'd0 :
		 ((decoder_func_32_inst[6:2] == 5'b01000 ||
		   decoder_func_32_inst[6:2] == 5'b01001 &&
		   decoder_func_32_csrs[104] ||
		   decoder_func_32_inst[6:2] == 5'b11000) ?
		    decoder_func_32_inst[11:8] :
		    CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_0__ETC__q8),
	       decoder_func_32_inst[6:2] != 5'b01011 &&
	       ((decoder_func_32_inst[6:2] == 5'b01000 ||
		 decoder_func_32_inst[6:2] == 5'b01001 &&
		 decoder_func_32_csrs[104]) ?
		  decoder_func_32_inst[7] :
		  decoder_func_32_inst[6:2] != 5'b11000 &&
		  decoder_func_32_inst[6:2] != 5'b01101 &&
		  decoder_func_32_inst[6:2] != 5'b00101 &&
		  decoder_func_32_inst[6:2] != 5'b11011 &&
		  decoder_func_32_inst[20]) } ;
  assign NOT_decoder_func_32_inst_BITS_6_TO_5_20_EQ_0b1_ETC___d585 =
	     decoder_func_32_inst[6:5] != 2'b11 ||
	     CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q5 ;
  assign NOT_decoder_func_32_inst_BIT_26_20_21_AND_NOT__ETC___d228 =
	     !decoder_func_32_inst[26] &&
	     decoder_func_32_csrs[49:48] != 2'd0 &&
	     (!decoder_func_32_inst[25] && decoder_func_32_csrs[104] ||
	      decoder_func_32_inst[25] && decoder_func_32_csrs[102]) ;
  assign _theResult_____9_snd__h3632 =
	     (decoder_func_32_inst[14:12] == 3'd0) ?
	       _theResult_____9_snd__h3659 :
	       6'd2 ;
  assign bit12_19__h48 = {8{decoder_func_32_inst[31]}} ;
  assign bit20_30__h49 =
	     { bit12_19__h48,
	       decoder_func_32_inst[31],
	       decoder_func_32_inst[31],
	       decoder_func_32_inst[31] } ;
  assign bit31__h50 =
	     decoder_func_32_inst[6:2] != 5'b01011 &&
	     decoder_func_32_inst[31] ;
  assign decoder_func_32_csrs_BIT_111_96_AND_decoder_fu_ETC___d208 =
	     decoder_func_32_csrs[111] &&
	     decoder_func_32_inst[31:25] == 7'd1 &&
	     (decoder_func_32_inst[14:12] == 3'd0 ||
	      !decoder_func_32_inst_BITS_14_TO_12_3_ULE_3___d202) ||
	     IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_1_3_ETC___d207 ;
  assign decoder_func_32_csrs_BIT_99_69_AND_decoder_fun_ETC___d195 =
	     decoder_func_32_csrs[99] &&
	     (decoder_func_32_inst[14:12] == 3'd2 ||
	      decoder_func_32_inst[14:12] == 3'd3) &&
	     (decoder_func_32_inst[31:27] == 5'b0 ||
	      decoder_func_32_inst[31:27] == 5'b00001 ||
	      decoder_func_32_inst[31:27] == 5'b00011 ||
	      decoder_func_32_inst[31:27] == 5'b00100 ||
	      decoder_func_32_inst[31:27] == 5'b01000 ||
	      decoder_func_32_inst[31:27] == 5'd12 ||
	      decoder_func_32_inst[31:27] == 5'd16 ||
	      decoder_func_32_inst[31:27] == 5'b10100 ||
	      decoder_func_32_inst[31:27] == 5'b11000 ||
	      decoder_func_32_inst[31:27] == 5'b11100 ||
	      decoder_func_32_inst[31:27] == 5'b00010 &&
	      decoder_func_32_inst[24:20] == 5'd0) ;
  assign decoder_func_32_inst_BITS_14_TO_12_3_ULE_3___d202 =
	     decoder_func_32_inst[14:12] <= 3'd3 ;
  assign decoder_func_32_inst_BITS_14_TO_12_3_ULT_2___d246 =
	     decoder_func_32_inst[14:12] < 3'd2 ;
  assign decoder_func_32_inst_BITS_14_TO_12_3_ULT_3___d244 =
	     decoder_func_32_inst[14:12] < 3'd3 ;
  assign decoder_func_32_inst_BITS_14_TO_12_3_ULT_4___d163 =
	     decoder_func_32_inst[14:12] < 3'd4 ;
  assign decoder_func_32_inst_BITS_1_TO_0_17_EQ_0b11_18_ETC___d594 =
	     (decoder_func_32_inst[1:0] == 2'b11 ||
	      IF_decoder_func_32_inst_BITS_6_TO_5_20_EQ_0b0__ETC___d588) &&
	     decoder_func_32_inst[6:5] == 2'b11 &&
	     decoder_func_32_inst[4:2] == 3'b100 &&
	     IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d591 ;
  assign decoder_func_32_inst_BITS_6_TO_5_20_EQ_0b11_78_ETC___d345 =
	     decoder_func_32_inst[6:5] == 2'b11 &&
	     CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_NOT__ETC__q3 ;
  assign decoder_func_32_inst_BIT_25_22_EQ_INV_decoder__ETC___d269 =
	     decoder_func_32_inst[25] == ~decoder_func_32_inst[20] ;
  assign decoder_func_32_inst_BIT_26_20_OR_decoder_func_ETC___d508 =
	     decoder_func_32_inst[26] ||
	     decoder_func_32_csrs[49:48] == 2'd0 ||
	     (decoder_func_32_inst[25] || !decoder_func_32_csrs[104]) &&
	     (!decoder_func_32_inst[25] || !decoder_func_32_csrs[102]) ;
  assign decoder_func_32_inst_BIT_27_84_OR_decoder_func_ETC___d686 =
	     decoder_func_32_inst[27] | decoder_func_32_inst[28] ;
  assign fn___1__h7505 = { 3'd1, decoder_func_32_inst[12] } ;
  assign fn___1__h7527 = { 1'b1, decoder_func_32_inst[14:12] } ;
  assign immediate_value___1__h4538 =
	     { 15'd0,
	       decoder_func_32_inst[19:15],
	       NOT_decoder_func_32_inst_BITS_6_TO_2_EQ_0b1011_ETC___d618 } ;
  assign immediate_value__h51 =
	     { bit31__h50,
	       CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_de_ETC__q9,
	       CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_de_ETC__q10,
	       NOT_decoder_func_32_inst_BITS_6_TO_2_EQ_0b1011_ETC___d618 } ;
  assign instr_meta_funct__h1054 =
	     (decoder_func_32_inst[1:0] != 2'b11 &&
	      IF_decoder_func_32_inst_BITS_6_TO_5_20_EQ_0b0__ETC___d348 ||
	      IF_decoder_func_32_inst_BITS_6_TO_5_20_EQ_0b0__ETC___d588) ?
	       temp1___1__h7267 :
	       temp1__h80 ;
  assign instr_meta_immediate__h1053 =
	     decoder_func_32_inst_BITS_1_TO_0_17_EQ_0b11_18_ETC___d594 ?
	       immediate_value___1__h4538 :
	       immediate_value__h51 ;
  assign temp1___1__h7267 = { 1'd0, x__h7270 } ;
  assign temp1__h80 =
	     { IF_decoder_func_32_inst_BITS_6_TO_2_EQ_0b11000_ETC___d696,
	       ((decoder_func_32_inst[1:0] == 2'b11 ||
		 IF_decoder_func_32_inst_BITS_6_TO_5_20_EQ_0b0__ETC___d588) &&
		decoder_func_32_inst[6:5] == 2'b10 &&
		IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d277 &&
		decoder_func_32_inst[14:12] == 3'd7) ?
		 decoder_func_32_csrs[34:32] :
		 decoder_func_32_inst[14:12] } ;
  assign trapcause___1__h3654 =
	     (decoder_func_32_csrs[119] &&
	      decoder_func_32_csrs[198:197] != 2'd3 &&
	      decoder_func_32_csrs[198:197] != 2'd1) ?
	       6'd8 :
	       ((decoder_func_32_csrs[117] &&
		 decoder_func_32_csrs[198:197] == 2'd1) ?
		  6'd9 :
		  6'd11) ;
  assign x__h21 =
	     (decoder_func_32_inst[6:2] == 5'b11011 ||
	      decoder_func_32_inst[6:2] == 5'b01101 ||
	      decoder_func_32_inst[6:2] == 5'b00101 ||
	      decoder_func_32_inst[6:2] == 5'b11100 &&
	      decoder_func_32_inst[14]) ?
	       5'd0 :
	       decoder_func_32_inst[19:15] ;
  assign x__h213 =
	     (decoder_func_32_inst[6:2] == 5'b11100 &&
	      decoder_func_32_inst[14:12] != 3'd0 &&
	      decoder_func_32_inst[31:25] != 7'b0001001 ||
	      decoder_func_32_inst[6:4] == 3'b0 ||
	      decoder_func_32_inst[6:2] == 5'b01101 ||
	      decoder_func_32_inst[6:4] == 3'b001 ||
	      decoder_func_32_inst[6:2] == 5'b11011 ||
	      decoder_func_32_inst[6:2] == 5'b11001 ||
	      decoder_func_32_inst[6:4] == 3'b101 &&
	      decoder_func_32_inst[30] &&
	      decoder_func_32_csrs[102] | decoder_func_32_csrs[104]) ?
	       5'd0 :
	       decoder_func_32_inst[24:20] ;
  assign x__h482 =
	     (decoder_func_32_inst[6:2] == 5'b11000 ||
	      decoder_func_32_inst[6:3] == 4'b0100 ||
	      decoder_func_32_inst[6:2] == 5'b00011) ?
	       5'd0 :
	       decoder_func_32_inst[11:7] ;
  assign x__h540 =
	     (decoder_func_32_inst[6:4] == 3'b100) ?
	       decoder_func_32_inst[31:27] :
	       5'd0 ;
  assign x__h7270 =
	     (decoder_func_32_inst[1:0] != 2'b11 &&
	      IF_decoder_func_32_inst_BITS_6_TO_5_20_EQ_0b0__ETC___d348 ||
	      decoder_func_32_inst[6:5] == 2'b0 ||
	      decoder_func_32_inst[6:5] == 2'b01 ||
	      decoder_func_32_inst[6:5] == 2'b10) ?
	       6'd2 :
	       ((decoder_func_32_inst[6:5] == 2'b11) ?
		  _theResult_____9_snd__h3604 :
		  6'd2) ;
  always@(decoder_func_32_inst or
	  trapcause___1__h3654 or decoder_func_32_csrs)
  begin
    case (decoder_func_32_inst[31:7])
      25'd0: _theResult_____9_snd__h3659 = trapcause___1__h3654;
      25'h0002000:
	  _theResult_____9_snd__h3659 =
	      (decoder_func_32_csrs[15] &&
	       decoder_func_32_csrs[198:197] == 2'd3 ||
	       decoder_func_32_csrs[14] &&
	       decoder_func_32_csrs[198:197] == 2'd1 ||
	       decoder_func_32_csrs[13] &&
	       decoder_func_32_csrs[198:197] != 2'd3 &&
	       decoder_func_32_csrs[198:197] != 2'd1) ?
		6'd49 :
		6'd3;
      default: _theResult_____9_snd__h3659 = 6'd2;
    endcase
  end
  always@(decoder_func_32_inst or _theResult_____9_snd__h3632)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0, 3'b001, 3'b011: _theResult_____9_snd__h3604 = 6'd2;
      3'b100: _theResult_____9_snd__h3604 = _theResult_____9_snd__h3632;
      default: _theResult_____9_snd__h3604 = 6'd2;
    endcase
  end
  always@(decoder_func_32_inst)
  begin
    case (decoder_func_32_inst[14:12])
      3'd0, 3'd5:
	  IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d200 =
	      decoder_func_32_inst[31:25] == 7'b0 ||
	      decoder_func_32_inst[31:25] == 7'b0100000;
      default: IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d200 =
		   decoder_func_32_inst[31:25] == 7'b0;
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_2_ETC___d238 or
	  decoder_func_32_inst_BITS_14_TO_12_3_ULT_3___d244 or
	  decoder_func_32_inst_BITS_14_TO_12_3_ULT_2___d246)
  begin
    case (decoder_func_32_inst[31:27])
      5'b0, 5'b00001, 5'b00010, 5'b00011:
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d262 =
	      IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_2_ETC___d238;
      5'b00100, 5'b10100:
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d262 =
	      decoder_func_32_inst_BITS_14_TO_12_3_ULT_3___d244;
      5'b00101:
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d262 =
	      decoder_func_32_inst_BITS_14_TO_12_3_ULT_2___d246;
      5'b01011:
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d262 =
	      decoder_func_32_inst[24:20] == 5'd0 &&
	      IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_2_ETC___d238;
      5'b11000, 5'b11010:
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d262 =
	      decoder_func_32_inst[24:21] == 4'b0 &&
	      IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_2_ETC___d238;
      5'b11100:
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d262 =
	      decoder_func_32_inst[24:20] == 5'd0 &&
	      (decoder_func_32_inst[14:12] == 3'd0 ||
	       decoder_func_32_inst[14:12] == 3'd1);
      default: IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d262 =
		   decoder_func_32_inst[31:27] == 5'b11110 &&
		   decoder_func_32_inst[24:20] == 5'd0 &&
		   decoder_func_32_inst[14:12] == 3'd0;
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_2_ETC___d238 or
	  decoder_func_32_inst_BIT_25_22_EQ_INV_decoder__ETC___d269)
  begin
    case (decoder_func_32_inst[31:27])
      5'b11000, 5'b11010:
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b1_ETC___d273 =
	      decoder_func_32_inst[24:21] == 4'b0001 &&
	      IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_2_ETC___d238;
      5'b11100, 5'b11110:
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b1_ETC___d273 =
	      decoder_func_32_inst[24:20] == 5'd0 &&
	      decoder_func_32_inst[14:12] == 3'd0;
      default: IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b1_ETC___d273 =
		   decoder_func_32_inst[31:27] == 5'b01000 &&
		   decoder_func_32_inst[24:21] == 4'b0 &&
		   IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_2_ETC___d238 &&
		   decoder_func_32_inst_BIT_25_22_EQ_INV_decoder__ETC___d269;
    endcase
  end
  always@(decoder_func_32_csrs)
  begin
    case (decoder_func_32_csrs[198:197])
      2'd1, 2'd3:
	  CASE_decoder_func_32_csrs_BITS_198_TO_197_1_de_ETC__q1 =
	      decoder_func_32_csrs[198:197];
      default: CASE_decoder_func_32_csrs_BITS_198_TO_197_1_de_ETC__q1 = 2'd0;
    endcase
  end
  always@(decoder_func_32_inst or decoder_func_32_csrs)
  begin
    case (decoder_func_32_inst[31:7])
      25'd0, 25'h0002000:
	  CASE_decoder_func_32_inst_BITS_31_TO_7_0_6_0x2_ETC__q2 = 4'd6;
      default: CASE_decoder_func_32_inst_BITS_31_TO_7_0_6_0x2_ETC__q2 =
		   (decoder_func_32_inst[31:20] == 12'h002 &&
		    decoder_func_32_inst[19:15] == 5'd0 &&
		    decoder_func_32_inst[11:7] == 5'd0 &&
		    decoder_func_32_csrs[112] ||
		    decoder_func_32_inst[31:20] == 12'h102 &&
		    decoder_func_32_inst[19:15] == 5'd0 &&
		    decoder_func_32_inst[11:7] == 5'd0 &&
		    decoder_func_32_csrs[117] &&
		    (decoder_func_32_csrs[198:197] == 2'd3 ||
		     decoder_func_32_csrs[198:197] == 2'd1 &&
		     !decoder_func_32_csrs[57]) ||
		    decoder_func_32_inst[31:20] == 12'h302 &&
		    decoder_func_32_inst[19:15] == 5'd0 &&
		    decoder_func_32_inst[11:7] == 5'd0 &&
		    decoder_func_32_csrs[198:197] == 2'd3) ?
		     4'd5 :
		     ((decoder_func_32_inst[31:20] == 12'h105 &&
		       decoder_func_32_inst[19:15] == 5'd0 &&
		       decoder_func_32_inst[11:7] == 5'd0) ?
			((!decoder_func_32_csrs[56] ||
			  decoder_func_32_csrs[198:197] == 2'd3) ?
			   4'd7 :
			   4'd6) :
			((decoder_func_32_inst[31:25] == 7'b0001001 &&
			  decoder_func_32_inst[11:7] == 5'd0) ?
			   ((!decoder_func_32_csrs[55] ||
			     decoder_func_32_csrs[198:197] == 2'd3) ?
			      4'd1 :
			      4'd6) :
			   4'd6));
    endcase
  end
  always@(decoder_func_32_inst or
	  decoder_func_32_csrs or
	  IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_1_3_ETC___d147)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0:
	  IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d161 =
	      decoder_func_32_inst[14:12] != 3'd7;
      3'b001:
	  IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d161 =
	      decoder_func_32_csrs[49:48] != 2'd0 &&
	      (decoder_func_32_csrs[104] &&
	       decoder_func_32_inst[14:12] == 3'd2 ||
	       decoder_func_32_csrs[102] &&
	       decoder_func_32_inst[14:12] == 3'd3);
      3'b011:
	  IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d161 =
	      decoder_func_32_inst[14:12] == 3'd0 ||
	      decoder_func_32_inst[14:12] == 3'd1;
      3'b100:
	  IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d161 =
	      IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_1_3_ETC___d147;
      default: IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d161 =
		   decoder_func_32_inst[4:2] == 3'b101 ||
		   decoder_func_32_inst[4:2] == 3'b110 &&
		   (decoder_func_32_inst[14:12] == 3'd0 ||
		    ((decoder_func_32_inst[14:12] == 3'd1) ?
		       decoder_func_32_inst[31:25] == 7'b0 :
		       decoder_func_32_inst[14:12] == 3'd5 &&
		       (decoder_func_32_inst[31:25] == 7'b0 ||
			decoder_func_32_inst[31:25] == 7'b0100000)));
    endcase
  end
  always@(decoder_func_32_inst or
	  decoder_func_32_csrs_BIT_111_96_AND_decoder_fu_ETC___d208 or
	  decoder_func_32_inst_BITS_14_TO_12_3_ULT_4___d163 or
	  decoder_func_32_csrs or
	  decoder_func_32_csrs_BIT_99_69_AND_decoder_fun_ETC___d195 or
	  IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d200)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0:
	  IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d214 =
	      decoder_func_32_inst_BITS_14_TO_12_3_ULT_4___d163;
      3'b001:
	  IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d214 =
	      decoder_func_32_csrs[104] &&
	      decoder_func_32_csrs[49:48] != 2'd0 &&
	      decoder_func_32_inst[14:12] == 3'd2 ||
	      decoder_func_32_csrs[102] &&
	      decoder_func_32_csrs[49:48] != 2'd0 &&
	      decoder_func_32_inst[14:12] == 3'd3;
      3'b011:
	  IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d214 =
	      decoder_func_32_csrs_BIT_99_69_AND_decoder_fun_ETC___d195;
      3'b100:
	  IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d214 =
	      decoder_func_32_csrs[111] &&
	      decoder_func_32_inst[31:25] == 7'd1 ||
	      IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d200;
      default: IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d214 =
		   decoder_func_32_inst[4:2] == 3'b101 ||
		   decoder_func_32_inst[4:2] == 3'b110 &&
		   decoder_func_32_csrs_BIT_111_96_AND_decoder_fu_ETC___d208;
    endcase
  end
  always@(decoder_func_32_inst or
	  NOT_decoder_func_32_inst_BIT_26_20_21_AND_NOT__ETC___d228 or
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d262 or
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b1_ETC___d273 or
	  IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_2_ETC___d238)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0, 3'b001, 3'b010, 3'b011:
	  IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d277 =
	      NOT_decoder_func_32_inst_BIT_26_20_21_AND_NOT__ETC___d228 &&
	      IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_2_ETC___d238;
      default: IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d277 =
		   decoder_func_32_inst[4:2] == 3'b100 &&
		   NOT_decoder_func_32_inst_BIT_26_20_21_AND_NOT__ETC___d228 &&
		   (IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d262 ||
		    IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b1_ETC___d273);
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d340)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_NOT__ETC__q3 =
	      decoder_func_32_inst[14:12] != 3'd2 &&
	      decoder_func_32_inst[14:12] != 3'd3;
      3'b001:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_NOT__ETC__q3 =
	      decoder_func_32_inst[14:12] == 3'd0;
      default: CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_NOT__ETC__q3 =
		   decoder_func_32_inst[4:2] == 3'b011 ||
		   decoder_func_32_inst[4:2] == 3'b100 &&
		   IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d340;
    endcase
  end
  always@(decoder_func_32_inst or
	  decoder_func_32_inst_BITS_6_TO_5_20_EQ_0b11_78_ETC___d345 or
	  IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d161 or
	  IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d214 or
	  IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d277)
  begin
    case (decoder_func_32_inst[6:5])
      2'b0:
	  IF_decoder_func_32_inst_BITS_6_TO_5_20_EQ_0b0__ETC___d348 =
	      IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d161;
      2'b01:
	  IF_decoder_func_32_inst_BITS_6_TO_5_20_EQ_0b0__ETC___d348 =
	      IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d214;
      2'b10:
	  IF_decoder_func_32_inst_BITS_6_TO_5_20_EQ_0b0__ETC___d348 =
	      IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d277;
      2'd3:
	  IF_decoder_func_32_inst_BITS_6_TO_5_20_EQ_0b0__ETC___d348 =
	      decoder_func_32_inst_BITS_6_TO_5_20_EQ_0b11_78_ETC___d345;
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_2_ETC___d511 or
	  decoder_func_32_inst_BITS_14_TO_12_3_ULT_3___d244 or
	  decoder_func_32_inst_BITS_14_TO_12_3_ULT_2___d246)
  begin
    case (decoder_func_32_inst[31:27])
      5'b0, 5'b00001, 5'b00010, 5'b00011:
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d530 =
	      IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_2_ETC___d511;
      5'b00100, 5'b10100:
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d530 =
	      !decoder_func_32_inst_BITS_14_TO_12_3_ULT_3___d244;
      5'b00101:
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d530 =
	      !decoder_func_32_inst_BITS_14_TO_12_3_ULT_2___d246;
      5'b01011:
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d530 =
	      decoder_func_32_inst[24:20] != 5'd0 ||
	      IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_2_ETC___d511;
      5'b11000, 5'b11010:
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d530 =
	      decoder_func_32_inst[24:21] != 4'b0 ||
	      IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_2_ETC___d511;
      5'b11100:
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d530 =
	      decoder_func_32_inst[24:20] != 5'd0 ||
	      decoder_func_32_inst[14:12] != 3'd0 &&
	      decoder_func_32_inst[14:12] != 3'd1;
      default: IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d530 =
		   decoder_func_32_inst[31:27] != 5'b11110 ||
		   decoder_func_32_inst[24:20] != 5'd0 ||
		   decoder_func_32_inst[14:12] != 3'd0;
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_2_ETC___d511 or
	  decoder_func_32_inst_BIT_25_22_EQ_INV_decoder__ETC___d269)
  begin
    case (decoder_func_32_inst[31:27])
      5'b11000, 5'b11010:
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b1_ETC___d537 =
	      decoder_func_32_inst[24:21] != 4'b0001 ||
	      IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_2_ETC___d511;
      5'b11100, 5'b11110:
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b1_ETC___d537 =
	      decoder_func_32_inst[24:20] != 5'd0 ||
	      decoder_func_32_inst[14:12] != 3'd0;
      default: IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b1_ETC___d537 =
		   decoder_func_32_inst[31:27] != 5'b01000 ||
		   decoder_func_32_inst[24:21] != 4'b0 ||
		   IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_2_ETC___d511 ||
		   !decoder_func_32_inst_BIT_25_22_EQ_INV_decoder__ETC___d269;
    endcase
  end
  always@(decoder_func_32_inst or
	  decoder_func_32_inst_BIT_26_20_OR_decoder_func_ETC___d508 or
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d530 or
	  IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b1_ETC___d537 or
	  IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_2_ETC___d511)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0, 3'b001, 3'b010, 3'b011:
	  IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d541 =
	      decoder_func_32_inst_BIT_26_20_OR_decoder_func_ETC___d508 ||
	      IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_7_2_ETC___d511;
      default: IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d541 =
		   decoder_func_32_inst[4:2] != 3'b100 ||
		   decoder_func_32_inst_BIT_26_20_OR_decoder_func_ETC___d508 ||
		   IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b0_ETC___d530 &&
		   IF_decoder_func_32_inst_BITS_31_TO_27_9_EQ_0b1_ETC___d537;
    endcase
  end
  always@(decoder_func_32_inst)
  begin
    case (decoder_func_32_inst[14:12])
      3'd0, 3'd5:
	  CASE_decoder_func_32_inst_BITS_14_TO_12_0_NOT__ETC__q4 =
	      decoder_func_32_inst[31:25] != 7'b0 &&
	      decoder_func_32_inst[31:25] != 7'b0100000;
      default: CASE_decoder_func_32_inst_BITS_14_TO_12_0_NOT__ETC__q4 =
		   decoder_func_32_inst[31:25] != 7'b0;
    endcase
  end
  always@(decoder_func_32_inst or
	  NOT_decoder_func_32_csrs_BIT_111_96_87_OR_NOT__ETC___d497 or
	  decoder_func_32_inst_BITS_14_TO_12_3_ULT_4___d163 or
	  decoder_func_32_csrs or
	  CASE_decoder_func_32_inst_BITS_14_TO_12_0_NOT__ETC__q4)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0:
	  IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d503 =
	      !decoder_func_32_inst_BITS_14_TO_12_3_ULT_4___d163;
      3'b001:
	  IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d503 =
	      (!decoder_func_32_csrs[104] ||
	       decoder_func_32_csrs[49:48] == 2'd0 ||
	       decoder_func_32_inst[14:12] != 3'd2) &&
	      (!decoder_func_32_csrs[102] ||
	       decoder_func_32_csrs[49:48] == 2'd0 ||
	       decoder_func_32_inst[14:12] != 3'd3);
      3'b011:
	  IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d503 =
	      !decoder_func_32_csrs[99] ||
	      decoder_func_32_inst[14:12] != 3'd2 &&
	      decoder_func_32_inst[14:12] != 3'd3 ||
	      decoder_func_32_inst[31:27] != 5'b0 &&
	      decoder_func_32_inst[31:27] != 5'b00001 &&
	      decoder_func_32_inst[31:27] != 5'b00011 &&
	      decoder_func_32_inst[31:27] != 5'b00100 &&
	      decoder_func_32_inst[31:27] != 5'b01000 &&
	      decoder_func_32_inst[31:27] != 5'd12 &&
	      decoder_func_32_inst[31:27] != 5'd16 &&
	      decoder_func_32_inst[31:27] != 5'b10100 &&
	      decoder_func_32_inst[31:27] != 5'b11000 &&
	      decoder_func_32_inst[31:27] != 5'b11100 &&
	      (decoder_func_32_inst[31:27] != 5'b00010 ||
	       decoder_func_32_inst[24:20] != 5'd0);
      3'b100:
	  IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d503 =
	      (!decoder_func_32_csrs[111] ||
	       decoder_func_32_inst[31:25] != 7'd1) &&
	      CASE_decoder_func_32_inst_BITS_14_TO_12_0_NOT__ETC__q4;
      default: IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d503 =
		   decoder_func_32_inst[4:2] != 3'b101 &&
		   (decoder_func_32_inst[4:2] != 3'b110 ||
		    NOT_decoder_func_32_csrs_BIT_111_96_87_OR_NOT__ETC___d497);
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d580)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q5 =
	      decoder_func_32_inst[14:12] == 3'd2 ||
	      decoder_func_32_inst[14:12] == 3'd3;
      3'b001:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q5 =
	      decoder_func_32_inst[14:12] != 3'd0;
      default: CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q5 =
		   decoder_func_32_inst[4:2] != 3'b011 &&
		   (decoder_func_32_inst[4:2] != 3'b100 ||
		    IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d580);
    endcase
  end
  always@(decoder_func_32_inst or decoder_func_32_csrs)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q6 =
	      decoder_func_32_inst[14:12] == 3'd7;
      3'b001:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q6 =
	      decoder_func_32_csrs[49:48] == 2'd0 ||
	      (!decoder_func_32_csrs[104] ||
	       decoder_func_32_inst[14:12] != 3'd2) &&
	      (!decoder_func_32_csrs[102] ||
	       decoder_func_32_inst[14:12] != 3'd3);
      3'b011:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q6 =
	      decoder_func_32_inst[14:12] != 3'd0 &&
	      decoder_func_32_inst[14:12] != 3'd1;
      3'b100:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q6 =
	      (decoder_func_32_inst[14:12] == 3'd1) ?
		decoder_func_32_inst[31:26] != 6'd0 :
		decoder_func_32_inst[14:12] == 3'd5 &&
		decoder_func_32_inst[31:26] != 6'd0 &&
		decoder_func_32_inst[31:26] != 6'b010000;
      default: CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q6 =
		   decoder_func_32_inst[4:2] != 3'b101 &&
		   (decoder_func_32_inst[4:2] != 3'b110 ||
		    decoder_func_32_inst[14:12] != 3'd0 &&
		    ((decoder_func_32_inst[14:12] == 3'd1) ?
		       decoder_func_32_inst[31:25] != 7'b0 :
		       decoder_func_32_inst[14:12] != 3'd5 ||
		       decoder_func_32_inst[31:25] != 7'b0 &&
		       decoder_func_32_inst[31:25] != 7'b0100000));
    endcase
  end
  always@(decoder_func_32_inst or
	  NOT_decoder_func_32_inst_BITS_6_TO_5_20_EQ_0b1_ETC___d585 or
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q6 or
	  IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d503 or
	  IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d541)
  begin
    case (decoder_func_32_inst[6:5])
      2'b0:
	  IF_decoder_func_32_inst_BITS_6_TO_5_20_EQ_0b0__ETC___d588 =
	      CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_deco_ETC__q6;
      2'b01:
	  IF_decoder_func_32_inst_BITS_6_TO_5_20_EQ_0b0__ETC___d588 =
	      IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d503;
      2'b10:
	  IF_decoder_func_32_inst_BITS_6_TO_5_20_EQ_0b0__ETC___d588 =
	      IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d541;
      2'd3:
	  IF_decoder_func_32_inst_BITS_6_TO_5_20_EQ_0b0__ETC___d588 =
	      NOT_decoder_func_32_inst_BITS_6_TO_5_20_EQ_0b1_ETC___d585;
    endcase
  end
  always@(decoder_func_32_inst)
  begin
    case (decoder_func_32_inst[6:2])
      5'b00101, 5'b01011, 5'b01101:
	  CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_0__ETC__q7 = 6'd0;
      default: CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_0__ETC__q7 =
		   decoder_func_32_inst[30:25];
    endcase
  end
  always@(decoder_func_32_inst)
  begin
    case (decoder_func_32_inst[6:2])
      5'b00101, 5'b01101:
	  CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_0__ETC__q8 = 4'd0;
      default: CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_0__ETC__q8 =
		   decoder_func_32_inst[24:21];
    endcase
  end
  always@(decoder_func_32_inst or bit20_30__h49)
  begin
    case (decoder_func_32_inst[6:2])
      5'b00101, 5'b01101:
	  CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_de_ETC__q9 =
	      decoder_func_32_inst[30:20];
      5'b01011:
	  CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_de_ETC__q9 = 11'd0;
      default: CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_de_ETC__q9 =
		   bit20_30__h49;
    endcase
  end
  always@(decoder_func_32_inst or bit12_19__h48)
  begin
    case (decoder_func_32_inst[6:2])
      5'b00101, 5'b01101, 5'b11011:
	  CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_de_ETC__q10 =
	      decoder_func_32_inst[19:12];
      5'b01011:
	  CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_de_ETC__q10 = 8'd0;
      default: CASE_decoder_func_32_inst_BITS_6_TO_2_0b101_de_ETC__q10 =
		   bit12_19__h48;
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_decoder_func_32_inst_BIT_30_1_THEN_0b1011_E_ETC___d671)
  begin
    case (decoder_func_32_inst[14:12])
      3'd2: fn___1__h7544 = 4'b1100;
      3'd3: fn___1__h7544 = 4'b1110;
      3'd5:
	  fn___1__h7544 =
	      IF_decoder_func_32_inst_BIT_30_1_THEN_0b1011_E_ETC___d671;
      default: fn___1__h7544 = { 1'b0, decoder_func_32_inst[14:12] };
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_decoder_func_32_inst_BIT_30_1_THEN_0b1011_E_ETC___d671)
  begin
    case (decoder_func_32_inst[14:12])
      3'd0: fn___1__h7606 = decoder_func_32_inst[30] ? 4'b1010 : 4'b0;
      3'd2: fn___1__h7606 = 4'b1100;
      3'd3: fn___1__h7606 = 4'b1110;
      3'd5:
	  fn___1__h7606 =
	      IF_decoder_func_32_inst_BIT_30_1_THEN_0b1011_E_ETC___d671;
      default: fn___1__h7606 = { 1'b0, decoder_func_32_inst[14:12] };
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_decoder_func_32_inst_BITS_6_TO_5_20_EQ_0b10_ETC___d693 or
	  fn___1__h7544 or fn___1__h7606 or fn___1__h7527 or fn___1__h7505)
  begin
    case (decoder_func_32_inst[6:2])
      5'b00100, 5'b00110:
	  IF_decoder_func_32_inst_BITS_6_TO_2_EQ_0b11000_ETC___d696 =
	      fn___1__h7544;
      5'b01100, 5'b01110:
	  IF_decoder_func_32_inst_BITS_6_TO_2_EQ_0b11000_ETC___d696 =
	      fn___1__h7606;
      5'b11000:
	  IF_decoder_func_32_inst_BITS_6_TO_2_EQ_0b11000_ETC___d696 =
	      decoder_func_32_inst[14] ? fn___1__h7527 : fn___1__h7505;
      default: IF_decoder_func_32_inst_BITS_6_TO_2_EQ_0b11000_ETC___d696 =
		   IF_decoder_func_32_inst_BITS_6_TO_5_20_EQ_0b10_ETC___d693;
    endcase
  end
  always@(decoder_func_32_inst)
  begin
    case (decoder_func_32_inst[14:12])
      3'd0, 3'd1:
	  CASE_decoder_func_32_inst_BITS_14_TO_12_0_1_1_1_6__q11 = 4'd1;
      default: CASE_decoder_func_32_inst_BITS_14_TO_12_0_1_1_1_6__q11 = 4'd6;
    endcase
  end
  always@(decoder_func_32_inst or
	  decoder_func_32_csrs or
	  CASE_decoder_func_32_inst_BITS_14_TO_12_0_1_1_1_6__q11 or
	  IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_1_3_ETC___d147)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0:
	  IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d360 =
	      (decoder_func_32_inst[14:12] == 3'd7) ? 4'd6 : 4'd1;
      3'b001:
	  IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d360 =
	      (decoder_func_32_csrs[49:48] != 2'd0 &&
	       (decoder_func_32_csrs[104] &&
		decoder_func_32_inst[14:12] == 3'd2 ||
		decoder_func_32_csrs[102] &&
		decoder_func_32_inst[14:12] == 3'd3)) ?
		4'd1 :
		4'd6;
      3'b011:
	  IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d360 =
	      CASE_decoder_func_32_inst_BITS_14_TO_12_0_1_1_1_6__q11;
      3'b100:
	  IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d360 =
	      IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_1_3_ETC___d147 ?
		4'd0 :
		4'd6;
      3'b101:
	  IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d360 = 4'd0;
      3'b110:
	  IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d360 =
	      (decoder_func_32_inst[14:12] == 3'd0 ||
	       ((decoder_func_32_inst[14:12] == 3'd1) ?
		  decoder_func_32_inst[31:25] == 7'b0 :
		  decoder_func_32_inst[14:12] == 3'd5 &&
		  (decoder_func_32_inst[31:25] == 7'b0 ||
		   decoder_func_32_inst[31:25] == 7'b0100000))) ?
		4'd0 :
		4'd6;
      default: IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d360 =
		   4'd6;
    endcase
  end
  always@(decoder_func_32_inst or
	  decoder_func_32_inst_BITS_14_TO_12_3_ULT_4___d163 or
	  decoder_func_32_csrs or
	  decoder_func_32_csrs_BIT_99_69_AND_decoder_fun_ETC___d195 or
	  IF_decoder_func_32_csrs_BIT_111_96_AND_decoder_ETC___d365 or
	  IF_decoder_func_32_csrs_BIT_111_96_AND_decoder_ETC___d367)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0:
	  IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d373 =
	      decoder_func_32_inst_BITS_14_TO_12_3_ULT_4___d163 ? 4'd1 : 4'd6;
      3'b001:
	  IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d373 =
	      (decoder_func_32_csrs[104] &&
	       decoder_func_32_csrs[49:48] != 2'd0 &&
	       decoder_func_32_inst[14:12] == 3'd2 ||
	       decoder_func_32_csrs[102] &&
	       decoder_func_32_csrs[49:48] != 2'd0 &&
	       decoder_func_32_inst[14:12] == 3'd3) ?
		4'd1 :
		4'd6;
      3'b011:
	  IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d373 =
	      decoder_func_32_csrs_BIT_99_69_AND_decoder_fun_ETC___d195 ?
		4'd1 :
		4'd6;
      3'b100:
	  IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d373 =
	      IF_decoder_func_32_csrs_BIT_111_96_AND_decoder_ETC___d365;
      3'b101:
	  IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d373 = 4'd0;
      3'b110:
	  IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d373 =
	      IF_decoder_func_32_csrs_BIT_111_96_AND_decoder_ETC___d367;
      default: IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d373 =
		   4'd6;
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_NOT_decoder_func_32_inst_BIT_26_20_21_AND_N_ETC___d374 or
	  IF_NOT_decoder_func_32_inst_BIT_26_20_21_AND_N_ETC___d375)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0, 3'b001, 3'b010, 3'b011:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q12 =
	      IF_NOT_decoder_func_32_inst_BIT_26_20_21_AND_N_ETC___d374;
      3'b100:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q12 =
	      IF_NOT_decoder_func_32_inst_BIT_26_20_21_AND_N_ETC___d375;
      default: CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q12 = 4'd6;
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d388)
  begin
    case (decoder_func_32_inst[4:2])
      3'b0:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q13 =
	      (decoder_func_32_inst[14:12] != 3'd2 &&
	       decoder_func_32_inst[14:12] != 3'd3) ?
		4'd2 :
		4'd6;
      3'b001:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q13 =
	      (decoder_func_32_inst[14:12] == 3'd0) ? 4'd4 : 4'd6;
      3'b011: CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q13 = 4'd3;
      3'b100:
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q13 =
	      IF_decoder_func_32_inst_BITS_14_TO_12_3_EQ_0_4_ETC___d388;
      default: CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q13 = 4'd6;
    endcase
  end
  always@(decoder_func_32_inst or
	  IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d360 or
	  IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d373 or
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q12 or
	  CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q13)
  begin
    case (decoder_func_32_inst[6:5])
      2'b0:
	  IF_decoder_func_32_inst_BITS_6_TO_5_20_EQ_0b0__ETC___d396 =
	      IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d360;
      2'b01:
	  IF_decoder_func_32_inst_BITS_6_TO_5_20_EQ_0b0__ETC___d396 =
	      IF_decoder_func_32_inst_BITS_4_TO_2_22_EQ_0b0__ETC___d373;
      2'b10:
	  IF_decoder_func_32_inst_BITS_6_TO_5_20_EQ_0b0__ETC___d396 =
	      CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q12;
      2'b11:
	  IF_decoder_func_32_inst_BITS_6_TO_5_20_EQ_0b0__ETC___d396 =
	      CASE_decoder_func_32_inst_BITS_4_TO_2_0b0_IF_N_ETC__q13;
    endcase
  end
endmodule  // module_decoder_func_32

