/*
 * Generated by Bluespec Compiler (build a026416)
 * 
 * On Tue Aug 11 13:45:56 IST 2020
 * 
 */
#ifndef __vpi_wrapper_send_tdo_h__
#define __vpi_wrapper_send_tdo_h__

#include <vpi_user.h>

/* registration function */
void send_tdo_vpi_register();

/* VPI wrapper function */
PLI_INT32 send_tdo_calltf(PLI_BYTE8 *user_data);

#endif /* ifndef __vpi_wrapper_send_tdo_h__ */
